export const ADMIN_PERMISSIONS = Object.freeze({
  DASHBOARD_READ: 'ADMIN_DASHBOARD_READ', USER_READ: 'USER_READ', USER_STATUS_UPDATE: 'USER_STATUS_UPDATE',
  USER_ROLE_UPDATE: 'USER_ROLE_UPDATE', USER_SESSION_REVOKE: 'USER_SESSION_REVOKE', PROJECT_READ_ALL: 'PROJECT_READ_ALL',
  PROJECT_ARCHIVE: 'PROJECT_ARCHIVE', AUDIT_LOG_READ: 'AUDIT_LOG_READ', SERVICE_SETTINGS_READ: 'SERVICE_SETTINGS_READ',
  SERVICE_SETTINGS_UPDATE: 'SERVICE_SETTINGS_UPDATE', AI_JOB_READ: 'AI_JOB_READ', AI_JOB_RETRY: 'AI_JOB_RETRY', AI_JOB_CANCEL: 'AI_JOB_CANCEL',
});

export function resolveUserPermissions(user) { return user?.role === 'ADMIN' ? Object.values(ADMIN_PERMISSIONS) : []; }
