export const ADMIN_AUDIT_ACTIONS = [
  'ADMIN_REAUTHENTICATION_SUCCEEDED',
  'ADMIN_REAUTHENTICATION_FAILED',
  'USER_ROLE_CHANGED',
  'USER_STATUS_CHANGED',
  'USER_SESSION_REVOKED',
  'USER_SELF_DELETED',
  'USER_DELETED_BY_ADMIN',
  'CLUSTER_PERSONA_POLICY_CHANGED',
  'CLUSTER_PERSONA_VISIBILITY_CHANGED',
  'CLUSTER_PERSONA_ORDER_CHANGED',
  'SERVICE_SETTING_CHANGED',
];

export const AUDIT_ACTION_LABELS = {
  ADMIN_REAUTHENTICATION_SUCCEEDED: '관리자 재인증 성공',
  ADMIN_REAUTHENTICATION_FAILED: '관리자 재인증 실패',
  USER_ROLE_CHANGED: '사용자 권한 변경',
  USER_STATUS_CHANGED: '사용자 상태 변경',
  USER_SESSION_REVOKED: '사용자 세션 종료',
  USER_SELF_DELETED: '사용자 본인 탈퇴',
  USER_DELETED_BY_ADMIN: '관리자 사용자 삭제',
  CLUSTER_PERSONA_POLICY_CHANGED: '군집 페르소나 기능 변경',
  CLUSTER_PERSONA_VISIBILITY_CHANGED: '군집 페르소나 노출 변경',
  CLUSTER_PERSONA_ORDER_CHANGED: '군집 페르소나 순서 변경',
  SERVICE_SETTING_CHANGED: '서비스 설정 변경',
  ADMIN_USER_ROLE_CHANGED: '사용자 권한 변경 (기존 기록)',
  ADMIN_USER_STATUS_CHANGED: '사용자 상태 변경 (기존 기록)',
  ADMIN_USER_SESSIONS_REVOKED: '사용자 세션 종료 (기존 기록)',
  ADMIN_SETTING_UPDATED: '서비스 설정 변경 (기존 기록)',
};

export function getAuditActionLabel(action) {
  return AUDIT_ACTION_LABELS[action] || action;
}
