package com.aivle.backend.pipeline.concept.domain;

public enum ConceptAttemptError {
    CANDIDATE_DOMAIN_REJECTION,
    LEGAL_DOMAIN_REJECTION,
    RESULT_SCHEMA_INVALID,
    LEGAL_SOURCE_FAILURE,
    NEEDS_FACTS,
    INTERNAL_STATE_FAILURE,
    SCHEMA_INVALID,
    TRANSIENT_PROVIDER_FAILURE,
    PERMANENT_PROVIDER_FAILURE,
    ORIGIN_INVALID,
    LEGAL_REDESIGN_REQUIRED,
    LEGAL_REJECTED,
    INSUFFICIENT_INFORMATION,
    INTERNAL_EXECUTION_ERROR
}
