package com.aivle.backend.pipeline.concept.domain;

public enum ConceptAttemptError {
    CANDIDATE_DOMAIN_REJECTION,
    LEGAL_DOMAIN_REJECTION,
    RESULT_SCHEMA_INVALID,
    LEGAL_SOURCE_FAILURE,
    NEEDS_FACTS,
    LEGAL_EXTERNAL_FACT_UNRESOLVED,
    INTERNAL_STATE_FAILURE,
    SCHEMA_INVALID,
    REQUEST_CONTRACT_INVALID,
    TRANSIENT_PROVIDER_FAILURE,
    PERMANENT_PROVIDER_FAILURE,
    ORIGIN_INVALID,
    LOCKED_CONSTRAINT_INVALID,
    DUPLICATE_CONCEPT,
    INSUFFICIENT_DISTINCT_CONCEPTS,
    SCHEMA_REPAIR_EXHAUSTED,
    DISTINCTNESS_EXHAUSTED,
    REPLACEMENT_EXHAUSTED,
    LEGAL_REDESIGN_EXHAUSTED,
    LEGAL_REDESIGN_REQUIRED,
    LEGAL_REJECTED,
    INSUFFICIENT_INFORMATION,
    INTERNAL_EXECUTION_ERROR
}
