package com.aivle.backend.pipeline.concept.domain;

public enum ConceptSlotStatus {
    QUEUED, GENERATING, GENERATED, SCHEMA_INVALID, VALIDATING_ORIGIN, VALIDATING_DISTINCTNESS, VALIDATING_LEGAL,
    REDESIGNING, REPLACING, REVIEW_RETRY_PENDING, ELIGIBLE, REJECTED, NEEDS_INPUT, FAILED, STALE
}
