package com.aivle.backend.journey.conceptcore;
import com.aivle.backend.jobevent.*;import com.aivle.backend.taskrun.domain.*;import com.aivle.backend.taskrun.integration.InternalAiExecutionClient;import com.aivle.backend.taskrun.integration.InternalAiExecutionClient.*;import com.aivle.backend.taskrun.service.TaskRunService;import java.time.*;import java.util.*;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;
@Component @lombok.extern.slf4j.Slf4j
public class ConceptExplorationWorker {private static final TaskType TYPE=TaskType.CONCEPT_EXPLORATION;private final TaskRunService tasks;private final InternalAiExecutionClient client;private final ConceptExplorationBatchRepository batches;private final ConceptExplorationCompletionService completion;private final JobEventPublisher events;private final String workerId="concept-core-"+UUID.randomUUID();public ConceptExplorationWorker(TaskRunService tasks,InternalAiExecutionClient client,ConceptExplorationBatchRepository batches,ConceptExplorationCompletionService completion,JobEventPublisher events){this.tasks=tasks;this.client=client;this.batches=batches;this.completion=completion;this.events=events;}
 @Scheduled(fixedDelayString="${app.task-run.concept-exploration-poll-interval-ms:1000}") public void poll(){processOne();}@Scheduled(fixedDelayString="${app.task-run.concept-exploration-recovery-interval-ms:5000}") public void recover(){for(String id:tasks.recoverExpiredTaskIds(Duration.ZERO,List.of(TYPE))){ConceptExplorationBatch batch=batches.findByTaskRunIdAndDeletedAtIsNull(id).orElseThrow();batch.requeue();batches.save(batch);publish(batch,"RECOVERY","job.concept.batch.recovered",JobEvent.Status.QUEUED,Map.of(),null);}}
 boolean processOne(){TaskRunService.Claim claim=tasks.claimNext(TYPE,workerId,Duration.ofMinutes(5),Duration.ofMinutes(3));if(claim==null)return false;ConceptExplorationBatch batch=batches.findByTaskRunIdAndDeletedAtIsNull(claim.taskRunId()).orElseThrow();batch.generating();batches.save(batch);publish(batch,"GENERATING","job.concept.slot.started",JobEvent.Status.RUNNING,Map.of("slotIndex",0,"attemptPhase","INITIAL","variationFocus","TARGET_AND_USER_EXPERIENCE"),null);tasks.startExecution(claim.taskRunId(),claim.taskAttemptId(),claim.claimToken());try{TaskRun task=tasks.getOwnedForWorker(claim.taskRunId());ExecutionResponse response=client.execute(task,claim.taskAttemptId(),LocalDateTime.now().plusMinutes(3));var done=completion.complete(claim,response);publishTerminal(done.batch());}catch(ExecutionFailure failure){handle(claim,failure.code(),failure.reason(),failure.retryable());}catch(RuntimeException failure){log.warn("Concept exploration contract failure taskRunId={} type={} message={}",claim.taskRunId(),failure.getClass().getSimpleName(),failure.getMessage());handle(claim,"RESULT_SCHEMA_INVALID","CONCEPT_EXPLORATION_RESULT_INVALID",false);}return true;}
 private void handle(TaskRunService.Claim claim,String code,String reason,boolean retryable){tasks.fail(claim.taskRunId(),claim.taskAttemptId(),claim.claimToken(),code,reason,retryable);ConceptExplorationBatch batch=batches.findByTaskRunIdAndDeletedAtIsNull(claim.taskRunId()).orElseThrow();TaskRun task=tasks.getOwnedForWorker(claim.taskRunId());if(retryable&&tasks.scheduleRetry(claim.taskRunId(),Duration.ofSeconds(Math.min(30,1L<<Math.max(0,task.getAttemptCount()-1))))){batch.requeue();batches.save(batch);publish(batch,"RETRY","job.concept.slot.retrying",JobEvent.Status.RUNNING,Map.of(),null);}else{batch.fail(code);batches.save(batch);publish(batch,"FAILED","job.concept.batch.failed",JobEvent.Status.FAILED,Map.of(),code);}}
 private void publishTerminal(ConceptExplorationBatch batch){JobEvent.Status status=batch.getStatus()==ConceptExplorationBatch.Status.COMPLETED?JobEvent.Status.COMPLETED:batch.getStatus()==ConceptExplorationBatch.Status.NEEDS_INPUT?JobEvent.Status.NEEDS_INPUT:JobEvent.Status.FAILED;String key=batch.getStatus()==ConceptExplorationBatch.Status.COMPLETED?"job.concept.batch.completed":batch.getStatus()==ConceptExplorationBatch.Status.NEEDS_INPUT?"job.concept.batch.needs_input":"job.concept.batch.failed";publish(batch,batch.getStatus().name(),key,status,Map.of("eligibleCount",batch.getEligibleCount()),null);}
 private void publish(ConceptExplorationBatch b,String stage,String type,JobEvent.Status status,Map<String,?> params,String code){events.publish(new JobEventPublisher.Command(b.getProject().getId(),b.getTaskRun().getId(),b.getTaskRun().getId(),stage,type,status,type,params,code));}
}
