package com.aivle.backend.journey.conceptcore;

import com.aivle.backend.journey.boundary.*;
import com.aivle.backend.journey.brief.*;
import com.aivle.backend.journey.foundation.SnapshotHasher;
import com.aivle.backend.jobevent.*;
import com.aivle.backend.taskrun.integration.InternalAiExecutionClient.ExecutionResponse;
import com.aivle.backend.taskrun.service.TaskRunService;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.*;
import tools.jackson.databind.node.*;

@Service
public class ConceptExplorationCompletionService {
 private static final Set<String> ROOT=Set.of("slots","acceptedSlotIndices","eligibleCandidateCount","exhausted");
 private static final Set<String> SLOT=Set.of("slotIndex","variationFocus","attempts","accepted");
 private static final Set<String> ATTEMPT=Set.of("attemptNumber","phase","outcome","candidate","safeFailureType","duplicateStatus","negativeConstraint");
 private static final Set<String> SKELETON=Set.of("conceptName","oneLineSummary","targetSegment","problemScenario","valueProposition","solutionMechanism","actorRoles","platformRole","transactionFlow","dataFlow","physicalActivities","partnerRequirements","featureSet","channelHypothesis","pricingHypothesis","revenueModelHypothesis","operatingModel","assumptions","risks","legalImplementationHypothesis");
 private static final Set<String> ACTOR=Set.of("actor","role","responsibilities","permissions","prohibitedResponsibilities");private static final Set<String> TRANSACTION=Set.of("step","actor","action","assetOrPayment","responsibility");private static final Set<String> DATA=Set.of("dataType","collector","purpose","processor","recipient","retentionHypothesis");private static final Set<String> PHYSICAL=Set.of("activity","performer","requiredQualificationHypothesis","partnerDependency");
 private final ConceptExplorationBatchRepository batches;private final ConceptSlotRepository slots;private final ConceptAttemptRepository attempts;private final ConceptOriginValidationRepository origins;private final ConceptLegalAssessmentRepository assessments;private final ConceptRuleTraceRepository traces;private final ExplorationConceptRepository concepts;private final OpportunityFieldValueRepository fields;private final BoundaryRuleRepository rules;private final TaskRunService tasks;private final SnapshotHasher hasher;private final JobEventPublisher events;private final ObjectMapper mapper;
 public ConceptExplorationCompletionService(ConceptExplorationBatchRepository batches,ConceptSlotRepository slots,ConceptAttemptRepository attempts,ConceptOriginValidationRepository origins,ConceptLegalAssessmentRepository assessments,ConceptRuleTraceRepository traces,ExplorationConceptRepository concepts,OpportunityFieldValueRepository fields,BoundaryRuleRepository rules,TaskRunService tasks,SnapshotHasher hasher,JobEventPublisher events,ObjectMapper mapper){this.batches=batches;this.slots=slots;this.attempts=attempts;this.origins=origins;this.assessments=assessments;this.traces=traces;this.concepts=concepts;this.fields=fields;this.rules=rules;this.tasks=tasks;this.hasher=hasher;this.events=events;this.mapper=mapper;}

 @Transactional
 public Result complete(TaskRunService.Claim claim,ExecutionResponse response){JsonNode result=response.result();validate(result);ConceptExplorationBatch batch=batches.findByTaskRunIdAndDeletedAtIsNull(claim.taskRunId()).orElseThrow();if(!slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(batch.getId()).isEmpty())return new Result(batch,batch.getStatus());tasks.adopt(claim.taskRunId(),claim.taskAttemptId(),claim.claimToken(),mapper.writeValueAsString(result),response.canonicalInputHash(),response.resultSchemaVersion());List<OpportunityFieldValue> briefFields=fields.findByBriefVersionIdAndDeletedAtIsNullOrderByFieldKey(batch.getBriefVersion().getId());List<BoundaryRule> boundaryRules=rules.findByBoundaryVersionIdAndDeletedAtIsNullOrderByRuleKey(batch.getBoundaryVersion().getId());List<JsonNode> eligibleStructures=new ArrayList<>();List<Eligible> eligible=new ArrayList<>();boolean needsInput=false;int inspected=0;
  for(JsonNode slotNode:result.path("slots")){int index=slotNode.path("slotIndex").asInt();ConceptSlot.Phase phase=ConceptSlot.Phase.valueOf(slotNode.path("attempts").get(slotNode.path("attempts").size()-1).path("phase").asText());ConceptSlot slot=slots.save(ConceptSlot.create(batch,index,ConceptSlot.Focus.valueOf(slotNode.path("variationFocus").asText()),phase));ConceptAttempt last=null;for(JsonNode attemptNode:slotNode.path("attempts")){inspected++;ConceptSlot.Phase attemptPhase=ConceptSlot.Phase.valueOf(attemptNode.path("phase").asText());ConceptAttempt.Outcome outcome=ConceptAttempt.Outcome.valueOf(attemptNode.path("outcome").asText());if(attemptPhase==ConceptSlot.Phase.REPAIR)publish(batch,index,attemptPhase,slot.getVariationFocus(),"job.concept.slot.repairing",JobEvent.Status.RUNNING,null);if(attemptPhase==ConceptSlot.Phase.REDESIGN)publish(batch,index,attemptPhase,slot.getVariationFocus(),"job.concept.slot.redesigning",JobEvent.Status.RUNNING,null);if(attemptPhase==ConceptSlot.Phase.REPLACEMENT)publish(batch,index,attemptPhase,slot.getVariationFocus(),"job.concept.slot.replacing",JobEvent.Status.RUNNING,null);JsonNode candidate=attemptNode.get("candidate");String json=candidate==null||candidate.isNull()?null:mapper.writeValueAsString(candidate);String conceptHash=json==null?null:hasher.hash(json);ConceptAttempt.DuplicateStatus duplicate=nullableEnum(ConceptAttempt.DuplicateStatus.class,attemptNode,"duplicateStatus");String duplicateKey=candidate==null||candidate.isNull()?null:dedupeKey(candidate);last=attempts.save(ConceptAttempt.create(slot,attemptNode.path("attemptNumber").asInt(),attemptPhase,outcome,nullableText(attemptNode,"safeFailureType"),json,conceptHash,duplicate,duplicateKey,attemptNode.path("negativeConstraint").toString()));String event=outcome==ConceptAttempt.Outcome.VALID?"job.concept.slot.generated":outcome==ConceptAttempt.Outcome.SCHEMA_INVALID?"job.concept.slot.schema_invalid":"job.concept.slot.retrying";publish(batch,index,attemptPhase,slot.getVariationFocus(),event,JobEvent.Status.RUNNING,null);}
   if(last==null)throw new IllegalArgumentException("slot attempt required");if(last.getOutcome()!=ConceptAttempt.Outcome.VALID){slot.failed(ConceptSlot.Status.valueOf(last.getOutcome().name()),last.getPhase(),slotNode.path("attempts").size());publish(batch,index,last.getPhase(),slot.getVariationFocus(),"job.concept.slot.rejected",JobEvent.Status.RUNNING,null);continue;}slot.generated(last.getPhase(),slotNode.path("attempts").size());JsonNode candidate=mapper.readTree(last.getCandidateJson());ConceptAttempt.DuplicateStatus systemDuplicate=duplicateStatus(candidate,eligibleStructures);last.classifyDuplicate(systemDuplicate,dedupeKey(candidate));if(systemDuplicate!=ConceptAttempt.DuplicateStatus.UNIQUE||last.getDuplicateStatus()==ConceptAttempt.DuplicateStatus.DUPLICATE){slot.reject(ConceptSlot.LegalState.REDESIGN_REQUIRED);publish(batch,index,last.getPhase(),slot.getVariationFocus(),"job.concept.slot.rejected",JobEvent.Status.RUNNING,slot.getLegalState());continue;}slot.validatingOrigin();publish(batch,index,last.getPhase(),slot.getVariationFocus(),"job.concept.slot.validating_origin",JobEvent.Status.RUNNING,null);OriginResult origin=originTrace(batch,briefFields,candidate);origins.save(ConceptOriginValidation.create(last,origin.passed(),origin.trace().toString()));slot.validatingBoundary();publish(batch,index,last.getPhase(),slot.getVariationFocus(),"job.concept.slot.validating_boundary",JobEvent.Status.RUNNING,null);AssessmentResult assessment=assessment(batch,boundaryRules,last,candidate,origin.trace(),origin.passed());if(assessment.state()==ConceptSlot.LegalState.INSUFFICIENT_INFORMATION)needsInput=true;if(origin.passed()&&(assessment.state()==ConceptSlot.LegalState.IMPLEMENTABLE||assessment.state()==ConceptSlot.LegalState.IMPLEMENTABLE_WITH_CONTROLS)){slot.eligible(assessment.state());eligibleStructures.add(candidate);eligible.add(new Eligible(slot,last,candidate,assessment));publish(batch,index,last.getPhase(),slot.getVariationFocus(),"job.concept.slot.eligible",JobEvent.Status.RUNNING,slot.getLegalState());}else{slot.reject(origin.passed()?assessment.state():ConceptSlot.LegalState.HARD_BLOCK);publish(batch,index,last.getPhase(),slot.getVariationFocus(),"job.concept.slot.rejected",JobEvent.Status.RUNNING,slot.getLegalState());}
  }
  batch.validating(Math.min(inspected,batch.getMaxInspectedCandidates()));if(eligible.size()==3){int order=1;for(Eligible item:eligible.stream().sorted(Comparator.comparingInt(v->v.slot().getSlotIndex())).limit(3).toList())concepts.save(ExplorationConcept.create(batch,item.slot(),item.attempt(),order++,item.candidate().path("conceptName").asText(),item.candidate().toString(),item.assessment().state(),item.assessment().validatedHash()));batch.complete(3);}else if(needsInput)batch.needsInput("[\"CONCEPT_INFORMATION_REQUIRED\"]");else batch.fail("CONCEPT_ELIGIBLE_COUNT_NOT_REACHED");return new Result(batch,batch.getStatus());}

 private OriginResult originTrace(ConceptExplorationBatch batch,List<OpportunityFieldValue> values,JsonNode concept){ArrayNode trace=mapper.createArrayNode();boolean passed=true;for(OpportunityFieldValue field:values){String pointer=path(field.getFieldKey());JsonNode conceptValue=concept.at(pointer);String sourceHash=field.getValueJson()==null?hasher.hash("null"):hasher.hash(field.getValueJson());String conceptHash=hasher.hash(conceptValue.isMissingNode()?"null":conceptValue.toString());String status=switch(field.getDecisionStatus()){case LOCKED->preserved(field.getValueJson(),conceptValue)?"PRESERVED":"VIOLATION";case PREFERRED->preserved(field.getValueJson(),conceptValue)?"PRESERVED":"VARIED_WITHIN_PREFERENCE";case OPEN->"OPEN_DECISION_USED";case ASSUMPTION->"ASSUMPTION_INTRODUCED";};if("VIOLATION".equals(status))passed=false;ObjectNode item=trace.addObject();item.put("fieldKey",field.getFieldKey());item.put("decisionStatus",field.getDecisionStatus().name());item.put("sourceType",field.getSourceType().name());item.put("sourceVersionId",batch.getBriefVersion().getId());item.put("sourceHash",batch.getBriefSnapshotHash());item.put("sourceValueHash",sourceHash);item.put("conceptFieldPath",pointer);item.put("conceptValueHash",conceptHash);item.put("preservationStatus",status);item.put("explanation",explain(status));}return new OriginResult(passed,trace);}
 private AssessmentResult assessment(ConceptExplorationBatch batch,List<BoundaryRule> boundaryRules,ConceptAttempt attempt,JsonNode concept,JsonNode originTrace,boolean originPassed){ArrayNode satisfied=mapper.createArrayNode(),controls=mapper.createArrayNode(),violated=mapper.createArrayNode(),unresolved=mapper.createArrayNode(),requiredControls=mapper.createArrayNode(),partners=mapper.createArrayNode(),disclosures=mapper.createArrayNode(),prohibited=mapper.createArrayNode(),evidence=mapper.createArrayNode(),review=mapper.createArrayNode();Set<String> evidenceSet=new TreeSet<>();ConceptSlot.LegalState state=originPassed?ConceptSlot.LegalState.IMPLEMENTABLE:ConceptSlot.LegalState.HARD_BLOCK;List<TraceDraft> traceDrafts=new ArrayList<>();for(BoundaryRule rule:boundaryRules){String pointer=boundaryPath(rule.getStructureKey());JsonNode value=concept.at(pointer);ConceptRuleTrace.ComplianceStatus compliance;switch(rule.getRuleType()){case UNRESOLVED_FACT->{compliance=ConceptRuleTrace.ComplianceStatus.INSUFFICIENT_INFORMATION;unresolved.add(rule.getRuleKey());state=max(state,ConceptSlot.LegalState.INSUFFICIENT_INFORMATION);}case REQUIRED_PARTNER->{if(concept.path("partnerRequirements").isEmpty()){compliance=ConceptRuleTrace.ComplianceStatus.REDESIGN_REQUIRED;violated.add(rule.getRuleKey());state=max(state,ConceptSlot.LegalState.REDESIGN_REQUIRED);}else{compliance=ConceptRuleTrace.ComplianceStatus.SATISFIED_WITH_CONTROLS;controls.add(rule.getRuleKey());partners.add(rule.getRequiredPartnerRole()==null?rule.getNormalizedRequirement():rule.getRequiredPartnerRole());state=max(state,ConceptSlot.LegalState.IMPLEMENTABLE_WITH_CONTROLS);}}case REQUIRED_CONTROL->{compliance=ConceptRuleTrace.ComplianceStatus.SATISFIED_WITH_CONTROLS;controls.add(rule.getRuleKey());requiredControls.add(rule.getNormalizedRequirement());state=max(state,ConceptSlot.LegalState.IMPLEMENTABLE_WITH_CONTROLS);}case REQUIRED_DISCLOSURE->{compliance=ConceptRuleTrace.ComplianceStatus.SATISFIED_WITH_CONTROLS;controls.add(rule.getRuleKey());disclosures.add(rule.getRequiredDisclosure()==null?rule.getNormalizedRequirement():rule.getRequiredDisclosure());state=max(state,ConceptSlot.LegalState.IMPLEMENTABLE_WITH_CONTROLS);}case PROHIBITED_ROLE,PROHIBITED_ACTIVITY->{if(mentions(value,rule.getStructureKey())){compliance=ConceptRuleTrace.ComplianceStatus.HARD_BLOCK;violated.add(rule.getRuleKey());prohibited.add(rule.getNormalizedRequirement());state=ConceptSlot.LegalState.HARD_BLOCK;}else{compliance=ConceptRuleTrace.ComplianceStatus.SATISFIED;satisfied.add(rule.getRuleKey());}}default->{compliance=ConceptRuleTrace.ComplianceStatus.SATISFIED;satisfied.add(rule.getRuleKey());}}JsonNode ids=mapper.readTree(rule.getEvidenceIdsJson());ids.forEach(id->evidenceSet.add(id.asText()));traceDrafts.add(new TraceDraft(rule,compliance,pointer,ids));if(rule.isProfessionalReviewRecommended())review.add(rule.getRuleKey());}
  evidenceSet.forEach(evidence::add);ObjectNode snapshot=mapper.createObjectNode();snapshot.set("conceptSkeleton",concept);snapshot.put("briefVersionId",batch.getBriefVersion().getId());snapshot.put("briefHash",batch.getBriefSnapshotHash());snapshot.put("boundaryVersionId",batch.getBoundaryVersion().getId());snapshot.put("boundaryHash",batch.getBoundarySnapshotHash());snapshot.set("originTrace",originTrace);ArrayNode boundaryTrace=snapshot.putArray("boundaryTrace");for(TraceDraft draft:traceDrafts){ObjectNode t=boundaryTrace.addObject();t.put("boundaryRuleId",draft.rule().getRuleKey());t.put("ruleType",draft.rule().getRuleType().name());t.put("structureKey",draft.rule().getStructureKey());t.putArray("conceptFieldPaths").add(draft.path());t.put("complianceStatus",draft.compliance().name());t.set("evidenceIds",draft.evidence());}String validatedHash=hasher.hash(snapshot.toString());ConceptLegalAssessment saved=assessments.save(ConceptLegalAssessment.create(attempt,state,batch.getBriefVersion(),batch.getBoundaryVersion(),attempt.getConceptSnapshotHash(),validatedHash,concept.path("physicalActivities").toString(),satisfied.toString(),controls.toString(),violated.toString(),unresolved.toString(),requiredControls.toString(),partners.toString(),disclosures.toString(),prohibited.toString(),concept.path("assumptions").toString(),evidence.toString(),review.toString()));for(TraceDraft draft:traceDrafts)traces.save(ConceptRuleTrace.create(saved,draft.rule(),draft.compliance(),"[\""+draft.path()+"\"]",requiredControls.toString(),partners.toString(),draft.compliance()==ConceptRuleTrace.ComplianceStatus.HARD_BLOCK?draft.rule().getNormalizedRequirement():null,draft.evidence().toString(),draft.rule().getUserFacingReason()));return new AssessmentResult(state,validatedHash);}
 private void validate(JsonNode root){exact(root,ROOT);if(!root.path("slots").isArray()||root.path("slots").size()<3||root.path("slots").size()>9)throw new IllegalArgumentException();Set<Integer> indices=new HashSet<>();for(JsonNode slot:root.path("slots")){exact(slot,SLOT);int index=slot.path("slotIndex").asInt(-1);if(index<0||!indices.add(index)||!slot.path("attempts").isArray()||slot.path("attempts").isEmpty())throw new IllegalArgumentException();int expected=1;for(JsonNode attempt:slot.path("attempts")){exact(attempt,ATTEMPT);if(attempt.path("attemptNumber").asInt()!=expected++)throw new IllegalArgumentException();String outcome=attempt.path("outcome").asText();if("VALID".equals(outcome)){validateSkeleton(attempt.path("candidate"));}else if(!attempt.path("candidate").isNull())throw new IllegalArgumentException();}}}
 private void validateSkeleton(JsonNode c){exact(c,SKELETON);for(String field:List.of("conceptName","oneLineSummary","problemScenario","valueProposition","solutionMechanism","platformRole","legalImplementationHypothesis"))if(!c.path(field).isTextual()||c.path(field).asText().isBlank())throw new IllegalArgumentException("concept text required");for(JsonNode item:array(c,"actorRoles",true))exact(item,ACTOR);for(JsonNode item:array(c,"transactionFlow",true))exact(item,TRANSACTION);for(JsonNode item:array(c,"dataFlow",false))exact(item,DATA);for(JsonNode item:array(c,"physicalActivities",false))exact(item,PHYSICAL);for(String field:List.of("partnerRequirements","featureSet","channelHypothesis","assumptions","risks"))array(c,field,"featureSet".equals(field)||"channelHypothesis".equals(field));rejectForbidden(c);}
 private Iterable<JsonNode> array(JsonNode c,String field,boolean required){JsonNode value=c.path(field);if(!value.isArray()||(required&&value.isEmpty()))throw new IllegalArgumentException("concept array required");return value;}
 private void rejectForbidden(JsonNode node){if(node.isObject()){for(String name:node.propertyNames()){String normalized=name.toLowerCase(Locale.ROOT);if(Set.of("sourcevalue","requiredorigintrace","origintrace","legaltrace","evidenceids","lawtext","citation","finallegalstatus").contains(normalized))throw new IllegalArgumentException("authoritative trace is forbidden");rejectForbidden(node.get(name));}}else if(node.isArray())node.forEach(this::rejectForbidden);}
 private static void exact(JsonNode n,Set<String> keys){if(!n.isObject()||!Set.copyOf(n.propertyNames()).equals(keys))throw new IllegalArgumentException("strict concept schema");}
 private String dedupeKey(JsonNode c){ObjectNode d=mapper.createObjectNode();for(String f:List.of("targetSegment","solutionMechanism","platformRole","actorRoles","operatingModel","revenueModelHypothesis","partnerRequirements"))d.set(f,c.path(f));return hasher.hash(d.toString());}
 private ConceptAttempt.DuplicateStatus duplicateStatus(JsonNode candidate,List<JsonNode> accepted){for(JsonNode other:accepted){int same=0;for(String field:List.of("targetSegment","solutionMechanism","platformRole","actorRoles","operatingModel","revenueModelHypothesis","partnerRequirements"))if(candidate.path(field).equals(other.path(field)))same++;if(same==7)return ConceptAttempt.DuplicateStatus.DUPLICATE;if(same>=5)return ConceptAttempt.DuplicateStatus.NEAR_DUPLICATE;}return ConceptAttempt.DuplicateStatus.UNIQUE;}
 private boolean preserved(String source,JsonNode value){if(source==null||value.isMissingNode())return false;String normalized=mapper.readTree(source).toString().replace("\"","").toLowerCase(Locale.ROOT);return value.toString().replace("\"","").toLowerCase(Locale.ROOT).contains(normalized);}
 private boolean mentions(JsonNode value,String key){return !value.isMissingNode()&&value.toString().toLowerCase(Locale.ROOT).contains(key.toLowerCase(Locale.ROOT));}
 private static String path(String field){return switch(field){case "problem","usageContext"->"/problemScenario";case "targetCustomer","beneficiaries"->"/targetSegment";case "desiredOutcome"->"/valueProposition";case "openDecisions","assumptions"->"/assumptions";case "prohibitedApproaches"->"/actorRoles";case "regulatorySensitiveActivities"->"/physicalActivities";default->"/operatingModel";};}
 private static String boundaryPath(String key){String k=key.toLowerCase(Locale.ROOT);if(k.contains("data")||k.contains("location"))return "/dataFlow";if(k.contains("physical")||k.contains("collect")||k.contains("transport"))return "/physicalActivities";if(k.contains("partner")||k.contains("qualification"))return "/partnerRequirements";if(k.contains("role"))return "/actorRoles";return "/operatingModel";}
 private static String explain(String status){return switch(status){case "PRESERVED"->"Confirmed Brief 의미가 보존되었습니다.";case "VARIED_WITHIN_PREFERENCE"->"선호 범위 안에서 후보별로 변형되었습니다.";case "OPEN_DECISION_USED"->"열린 결정을 후보 구조에서 사용했습니다.";case "ASSUMPTION_INTRODUCED"->"명시된 가정으로 연결했습니다.";default->"LOCKED 의미 보존을 확인하지 못했습니다.";};}
 private static ConceptSlot.LegalState max(ConceptSlot.LegalState a,ConceptSlot.LegalState b){List<ConceptSlot.LegalState> order=List.of(ConceptSlot.LegalState.IMPLEMENTABLE,ConceptSlot.LegalState.IMPLEMENTABLE_WITH_CONTROLS,ConceptSlot.LegalState.INSUFFICIENT_INFORMATION,ConceptSlot.LegalState.REDESIGN_REQUIRED,ConceptSlot.LegalState.HARD_BLOCK);return order.indexOf(a)>=order.indexOf(b)?a:b;}
 private static String nullableText(JsonNode n,String f){JsonNode v=n.get(f);return v==null||v.isNull()?null:v.asText();}private static <E extends Enum<E>> E nullableEnum(Class<E> type,JsonNode n,String f){String v=nullableText(n,f);return v==null?null:Enum.valueOf(type,v);}
 private void publish(ConceptExplorationBatch batch,int index,ConceptSlot.Phase phase,ConceptSlot.Focus focus,String key,JobEvent.Status status,ConceptSlot.LegalState legal){Map<String,Object> params=new LinkedHashMap<>();params.put("slotIndex",index);params.put("attemptPhase",phase.name());params.put("variationFocus",focus.name());if(legal!=null)params.put("legalState",legal.name());params.put("eligibleCount",batch.getEligibleCount());events.publish(new JobEventPublisher.Command(batch.getProject().getId(),batch.getTaskRun().getId(),batch.getTaskRun().getId(),"CONCEPT_SLOT",key,status,key,params,null));}
 record OriginResult(boolean passed,ArrayNode trace){}record AssessmentResult(ConceptSlot.LegalState state,String validatedHash){}record TraceDraft(BoundaryRule rule,ConceptRuleTrace.ComplianceStatus compliance,String path,JsonNode evidence){}record Eligible(ConceptSlot slot,ConceptAttempt attempt,JsonNode candidate,AssessmentResult assessment){}public record Result(ConceptExplorationBatch batch,ConceptExplorationBatch.Status status){}
}
