package com.aivle.backend.journey.conceptcore;
import com.aivle.backend.common.entity.BaseEntity;import com.aivle.backend.journey.boundary.RegulatoryBoundaryVersion;import com.aivle.backend.journey.brief.OpportunityBriefVersion;import jakarta.persistence.*;import java.time.LocalDateTime;import lombok.AccessLevel;import lombok.Getter;import lombok.NoArgsConstructor;
@Entity @Table(name="concept_legal_assessments") @Getter @NoArgsConstructor(access=AccessLevel.PROTECTED)
public class ConceptLegalAssessment extends BaseEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;@OneToOne(fetch=FetchType.LAZY) @JoinColumn(name="concept_attempt_id",nullable=false) private ConceptAttempt attempt;@Enumerated(EnumType.STRING) @Column(nullable=false,length=40) private ConceptSlot.LegalState status;
 @Column(nullable=false,columnDefinition="TEXT") private String regulatedActivitiesJson,satisfiedRuleIdsJson,controlRequiredRuleIdsJson,violatedRuleIdsJson,unresolvedRuleIdsJson,requiredControlsJson,requiredPartnersOrLicensesJson,requiredDisclosuresJson,prohibitedVariantsJson,unresolvedAssumptionsJson,evidenceIdsJson,professionalReviewFlagsJson;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="brief_version_id",nullable=false) private OpportunityBriefVersion briefVersion;@Column(nullable=false,length=71) private String briefHash;@ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="boundary_version_id",nullable=false) private RegulatoryBoundaryVersion boundaryVersion;@Column(nullable=false,length=71) private String boundaryHash;@Column(nullable=false,length=71) private String conceptSnapshotHash,validatedSnapshotHash;@Column(nullable=false) private LocalDateTime assessedAt;
 public static ConceptLegalAssessment create(ConceptAttempt a,ConceptSlot.LegalState s,OpportunityBriefVersion b,RegulatoryBoundaryVersion boundary,String conceptHash,String validatedHash,String regulated,String satisfied,String controls,String violated,String unresolved,String requiredControls,String partners,String disclosures,String prohibited,String assumptions,String evidence,String review){ConceptLegalAssessment v=new ConceptLegalAssessment();v.attempt=a;v.status=s;v.briefVersion=b;v.briefHash=b.getSnapshotHash();v.boundaryVersion=boundary;v.boundaryHash=boundary.getSnapshotHash();v.conceptSnapshotHash=conceptHash;v.validatedSnapshotHash=validatedHash;v.regulatedActivitiesJson=regulated;v.satisfiedRuleIdsJson=satisfied;v.controlRequiredRuleIdsJson=controls;v.violatedRuleIdsJson=violated;v.unresolvedRuleIdsJson=unresolved;v.requiredControlsJson=requiredControls;v.requiredPartnersOrLicensesJson=partners;v.requiredDisclosuresJson=disclosures;v.prohibitedVariantsJson=prohibited;v.unresolvedAssumptionsJson=assumptions;v.evidenceIdsJson=evidence;v.professionalReviewFlagsJson=review;v.assessedAt=LocalDateTime.now();return v;}
}
