package com.aivle.backend.journey.conceptcore;

import com.aivle.backend.journey.boundary.*;
import com.aivle.backend.journey.brief.*;
import com.aivle.backend.journey.foundation.FoundationProjectAccess;
import com.aivle.backend.journey.foundation.SnapshotHasher;
import com.aivle.backend.jobevent.*;
import com.aivle.backend.project.entity.Project;
import com.aivle.backend.taskrun.domain.*;
import com.aivle.backend.taskrun.service.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.*;
import tools.jackson.databind.node.*;

@Service
public class ConceptExplorationApplicationService {
 private final FoundationProjectAccess projects;private final OpportunityBriefVersionRepository briefs;private final OpportunityFieldValueRepository fields;private final RegulatoryBoundaryVersionRepository boundaries;private final BoundaryRuleRepository rules;private final ConceptExplorationBatchRepository batches;private final ConceptSlotRepository slots;private final ExplorationConceptRepository concepts;private final ConceptLegalAssessmentRepository assessments;private final TaskRunService tasks;private final CanonicalInputHasher taskHasher;private final SnapshotHasher snapshots;private final JobEventPublisher events;private final ObjectMapper mapper;
 public ConceptExplorationApplicationService(FoundationProjectAccess projects,OpportunityBriefVersionRepository briefs,OpportunityFieldValueRepository fields,RegulatoryBoundaryVersionRepository boundaries,BoundaryRuleRepository rules,ConceptExplorationBatchRepository batches,ConceptSlotRepository slots,ExplorationConceptRepository concepts,ConceptLegalAssessmentRepository assessments,TaskRunService tasks,CanonicalInputHasher taskHasher,SnapshotHasher snapshots,JobEventPublisher events,ObjectMapper mapper){this.projects=projects;this.briefs=briefs;this.fields=fields;this.boundaries=boundaries;this.rules=rules;this.batches=batches;this.slots=slots;this.concepts=concepts;this.assessments=assessments;this.tasks=tasks;this.taskHasher=taskHasher;this.snapshots=snapshots;this.events=events;this.mapper=mapper;}

 @Transactional
 public StartView start(Long ownerId,Long projectId,Long briefId,Long boundaryId){Project project=projects.requireOwnedForUpdate(ownerId,projectId);OpportunityBriefVersion brief=briefs.findByIdAndProjectIdAndDeletedAtIsNull(briefId,projectId).orElse(null);RegulatoryBoundaryVersion boundary=boundaries.findByIdAndProjectIdAndDeletedAtIsNull(boundaryId,projectId).orElse(null);StartView blocked=validateStart(projectId,brief,boundary);if(blocked!=null)return blocked;String input=buildInput(brief,boundary);String snapshotHash=snapshots.hash(input);ConceptExplorationBatch existing=batches.findByProjectIdAndBriefVersionIdAndBoundaryVersionIdAndInputSnapshotHashAndDeletedAtIsNull(projectId,briefId,boundaryId,snapshotHash).orElse(null);if(existing!=null)return view(existing);String taskHash=taskHasher.hash(TaskType.CONCEPT_EXPLORATION,"1.0","ko-KR",input);String key="concept-core-"+briefId+'-'+boundaryId+'-'+snapshotHash.substring(7,23);TaskRun task=tasks.create(ownerId,projectId,TaskType.CONCEPT_EXPLORATION,"REGULATORY_BOUNDARY_VERSION",boundaryId.toString(),input,taskHash,key,UUID.randomUUID().toString(),3);ConceptExplorationBatch batch=batches.save(ConceptExplorationBatch.queued(project,brief,boundary,task,snapshotHash));publish(batch,"BATCH","job.concept.batch.queued",JobEvent.Status.QUEUED,Map.of("eligibleCount",0),null);return view(batch);}
 private StartView validateStart(Long projectId,OpportunityBriefVersion brief,RegulatoryBoundaryVersion boundary){if(brief==null)return StartView.blocked("CONCEPT_BRIEF_NOT_FOUND","확정된 Opportunity Brief가 필요합니다.","MISSING_BRIEF","CONFIRM_BRIEF");if(brief.getState()!=OpportunityBriefVersion.State.CONFIRMED)return StartView.blocked("CONCEPT_BRIEF_NOT_CONFIRMED","Draft Brief로 Concept를 생성할 수 없습니다.","DRAFT_BRIEF","CONFIRM_BRIEF");OpportunityBriefVersion current=briefs.findTopByProjectIdAndStateAndDeletedAtIsNullOrderByVersionNumberDesc(projectId,OpportunityBriefVersion.State.CONFIRMED).orElse(null);if(current==null||!current.getId().equals(brief.getId())||!current.getSnapshotHash().equals(brief.getSnapshotHash()))return StartView.blocked("CONCEPT_BRIEF_STALE","최신 확정 Brief를 사용해 주세요.","STALE","SELECT_CURRENT_BRIEF");if(boundary==null)return StartView.blocked("CONCEPT_BOUNDARY_NOT_FOUND","READY Regulatory Boundary가 필요합니다.","MISSING_BOUNDARY","RUN_BOUNDARY");if(boundary.getStatus()!=RegulatoryBoundaryVersion.Status.READY)return StartView.blocked("CONCEPT_BOUNDARY_NOT_READY","READY Boundary에서만 Concept를 생성할 수 있습니다.",boundary.getStatus().name(),"RESOLVE_BOUNDARY");if(!boundary.getBriefVersion().getId().equals(brief.getId())||!boundary.getBriefSnapshotHash().equals(brief.getSnapshotHash()))return StartView.blocked("CONCEPT_INPUT_MISMATCH","Brief와 Boundary Version 또는 Hash가 일치하지 않습니다.","STALE","RUN_BOUNDARY");return null;}
 private String buildInput(OpportunityBriefVersion brief,RegulatoryBoundaryVersion boundary){ObjectNode root=mapper.createObjectNode();root.put("confirmedBriefVersionId",brief.getId());root.put("confirmedBriefHash",brief.getSnapshotHash());root.put("regulatoryBoundaryVersionId",boundary.getId());root.put("regulatoryBoundaryHash",boundary.getSnapshotHash());ArrayNode fs=root.putArray("briefFields");for(OpportunityFieldValue field:fields.findByBriefVersionIdAndDeletedAtIsNullOrderByFieldKey(brief.getId())){ObjectNode item=fs.addObject();item.put("fieldKey",field.getFieldKey());item.set("value",field.getValueJson()==null?mapper.nullNode():mapper.readTree(field.getValueJson()));item.put("decisionStatus",field.getDecisionStatus().name());item.put("sourceType",field.getSourceType().name());}ArrayNode rs=root.putArray("boundaryRules");for(BoundaryRule rule:rules.findByBoundaryVersionIdAndDeletedAtIsNullOrderByRuleKey(boundary.getId())){ObjectNode item=rs.addObject();item.put("ruleId",rule.getRuleKey());item.put("ruleType",rule.getRuleType().name());item.put("structureKey",rule.getStructureKey());item.put("normalizedRequirement",rule.getNormalizedRequirement());item.set("appliesWhen",mapper.readTree(rule.getAppliesWhenJson()));item.set("evidenceIds",mapper.readTree(rule.getEvidenceIdsJson()));item.set("alternatives",mapper.readTree(rule.getAlternativesJson()));if(rule.getRequiredPartnerRole()==null)item.putNull("requiredPartnerRole");else item.put("requiredPartnerRole",rule.getRequiredPartnerRole());if(rule.getRequiredDisclosure()==null)item.putNull("requiredDisclosure");else item.put("requiredDisclosure",rule.getRequiredDisclosure());}
 root.put("desiredCount",3);root.put("maxInspectedCandidates",9);root.put("maxReplacementRounds",2);root.putArray("negativeConstraints");String text="concept-core-input";ObjectNode content=root.putArray("textContents").addObject();content.put("contentKey","concept-core-"+brief.getId()+'-'+boundary.getId());content.put("contentType","TEXT");content.put("language","ko-KR");content.put("totalCharacters",text.length());content.put("contentHash",sha(text));ObjectNode chunk=content.putArray("chunks").addObject();chunk.put("index",0);chunk.put("text",text);chunk.put("characterCount",text.length());chunk.put("chunkHash",sha(text));return mapper.writeValueAsString(root);}
 @Transactional public CurrentView current(Long ownerId,Long projectId){projects.requireOwned(ownerId,projectId);ConceptExplorationBatch batch=batches.findTopByProjectIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(projectId).orElse(null);if(batch==null)return new CurrentView(null,List.of(),List.of());markStale(projectId,batch);return new CurrentView(view(batch),slotViews(batch),publicConcepts(batch));}
 @Transactional public StartView retry(Long ownerId,Long projectId,Long batchId,String idempotencyKey){projects.requireOwnedForUpdate(ownerId,projectId);ConceptExplorationBatch batch=batches.findByIdAndProjectIdAndDeletedAtIsNull(batchId,projectId).orElseThrow();if(batch.getStatus()!=ConceptExplorationBatch.Status.FAILED||!batch.getTaskRun().isRetryable())return view(batch);tasks.retry(ownerId,projectId,batch.getTaskRun().getId(),idempotencyKey);batch.requeue();batches.save(batch);publish(batch,"BATCH","job.concept.batch.queued",JobEvent.Status.QUEUED,Map.of("eligibleCount",0),null);return view(batch);}
 @Transactional public BatchDetail batch(Long ownerId,Long projectId,Long batchId){projects.requireOwned(ownerId,projectId);ConceptExplorationBatch batch=batches.findByIdAndProjectIdAndDeletedAtIsNull(batchId,projectId).orElseThrow();markStale(projectId,batch);return new BatchDetail(view(batch),slotViews(batch));}
 @Transactional public List<SlotView> slotViews(Long ownerId,Long projectId,Long batchId){projects.requireOwned(ownerId,projectId);ConceptExplorationBatch batch=batches.findByIdAndProjectIdAndDeletedAtIsNull(batchId,projectId).orElseThrow();markStale(projectId,batch);return slotViews(batch);}
 @Transactional public List<ConceptView> concepts(Long ownerId,Long projectId){projects.requireOwned(ownerId,projectId);ConceptExplorationBatch batch=batches.findTopByProjectIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(projectId).orElse(null);if(batch==null)return List.of();markStale(projectId,batch);return publicConcepts(batch);}
 private void markStale(Long projectId,ConceptExplorationBatch batch){OpportunityBriefVersion brief=briefs.findTopByProjectIdAndStateAndDeletedAtIsNullOrderByVersionNumberDesc(projectId,OpportunityBriefVersion.State.CONFIRMED).orElse(null);RegulatoryBoundaryVersion boundary=boundaries.findById(batch.getBoundaryVersion().getId()).orElse(null);RegulatoryBoundaryVersion currentBoundary=boundaries.findTopByProjectIdAndDeletedAtIsNullOrderByVersionNumberDesc(projectId).orElse(null);if(brief==null||boundary==null||currentBoundary==null||!currentBoundary.getId().equals(boundary.getId())||boundary.getStatus()!=RegulatoryBoundaryVersion.Status.READY||!batch.matches(brief,boundary)){batch.stale();slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(batch.getId()).forEach(ConceptSlot::stale);}}
 private List<SlotView> slotViews(ConceptExplorationBatch b){return slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(b.getId()).stream().map(s->new SlotView(s.getId(),s.getSlotIndex(),s.getVariationFocus().name(),s.getStatus().name(),s.getCurrentPhase().name(),s.getAttemptCount(),s.getSafeMessageKey(),s.getLegalState()==null?null:s.getLegalState().name(),s.isEligible(),s.getUpdatedAt())).toList();}
 private List<ConceptView> publicConcepts(ConceptExplorationBatch b){if(b.getStatus()!=ConceptExplorationBatch.Status.COMPLETED)return List.of();return concepts.findByProjectIdAndBatchIdAndDeletedAtIsNullOrderByDisplayOrder(b.getProject().getId(),b.getId()).stream().filter(c->c.getSlot().isEligible()).map(this::conceptView).toList();}
 private ConceptView conceptView(ExplorationConcept c){JsonNode s=mapper.readTree(c.getSkeletonJson());ConceptLegalAssessment a=assessments.findByAttemptId(c.getAttempt().getId()).orElseThrow();return new ConceptView(c.getId(),s.path("conceptName").asText(),s.path("oneLineSummary").asText(),s.path("targetSegment"),s.path("problemScenario").asText(),s.path("valueProposition").asText(),s.path("solutionMechanism").asText(),s.path("actorRoles"),s.path("platformRole").asText(),s.path("transactionFlow"),s.path("dataFlow"),s.path("physicalActivities"),s.path("partnerRequirements"),s.path("featureSet"),s.path("channelHypothesis"),s.path("pricingHypothesis"),s.path("operatingModel"),s.path("revenueModelHypothesis"),s.path("risks"),c.getLegalState().name(),mapper.readTree(a.getRequiredControlsJson()),mapper.readTree(a.getRequiredPartnersOrLicensesJson()),mapper.readTree(a.getRequiredDisclosuresJson()),mapper.readTree(a.getProhibitedVariantsJson()),mapper.readTree(a.getUnresolvedAssumptionsJson()),c.getAssessmentVersion(),c.getValidatedSnapshotHash(),c.getBatch().getBriefVersion().getId(),c.getBatch().getBriefSnapshotHash(),c.getBatch().getBoundaryVersion().getId(),c.getBatch().getBoundarySnapshotHash(),c.getBatch().getStatus()==ConceptExplorationBatch.Status.STALE,c.getAttempt().getDuplicateStatus()==null?null:c.getAttempt().getDuplicateStatus().name());}
 private StartView view(ConceptExplorationBatch b){return new StartView(b.getId(),b.getTaskRun().getId(),b.getStatus().name(),b.getBriefVersion().getId(),b.getBriefSnapshotHash(),b.getBoundaryVersion().getId(),b.getBoundarySnapshotHash(),b.getStatus()==ConceptExplorationBatch.Status.STALE,b.getTaskRun().isRetryable(),mapper.readTree(b.getNeedsInputJson()),null,null,null,null);}
 private void publish(ConceptExplorationBatch b,String stage,String type,JobEvent.Status status,Map<String,?> params,String code){events.publish(new JobEventPublisher.Command(b.getProject().getId(),b.getTaskRun().getId(),b.getTaskRun().getId(),stage,type,status,type,params,code));}
 private static String sha(String v){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception impossible){throw new IllegalStateException(impossible);}}
 public record StartView(Long batchId,String jobId,String status,Long confirmedBriefVersionId,String briefHash,Long regulatoryBoundaryVersionId,String boundaryHash,boolean stale,boolean retryable,JsonNode needsInput,String code,String userMessage,String blockingState,String nextAction){static StartView blocked(String code,String message,String state,String action){return new StartView(null,null,"REJECTED",null,null,null,null,false,false,null,code,message,state,action);}}
 public record CurrentView(StartView batch,List<SlotView> slots,List<ConceptView> concepts){} public record BatchDetail(StartView batch,List<SlotView> slots){}
 public record SlotView(Long slotId,int slotIndex,String variationFocus,String status,String currentPhase,int attemptCount,String safeMessageKey,String legalState,boolean eligible,java.time.LocalDateTime updatedAt){}
 public record ConceptView(Long conceptId,String conceptName,String oneLineSummary,JsonNode targetSegment,String problemScenario,String valueProposition,String solutionMechanism,JsonNode actorRoles,String platformRole,JsonNode transactionFlow,JsonNode dataFlow,JsonNode physicalActivities,JsonNode partnerRequirements,JsonNode featureSet,JsonNode channelHypothesis,JsonNode pricingHypothesis,JsonNode operatingModel,JsonNode revenueModelHypothesis,JsonNode risks,String legalState,JsonNode requiredControls,JsonNode requiredPartnersOrLicenses,JsonNode requiredDisclosures,JsonNode prohibitedVariants,JsonNode unresolvedAssumptions,int assessmentVersion,String validatedSnapshotHash,Long confirmedBriefVersionId,String briefHash,Long regulatoryBoundaryVersionId,String boundaryHash,boolean stale,String duplicateStatus){}
}
