package com.aivle.backend.taskrun.domain;
public enum TaskType {
    IDEA_ATTACHMENT_PARSE,
    IDEA_BRIEF_DERIVATION,
    CONCEPT_FACTORY_RUN,
    CONCEPT_CANDIDATE,
    CONCEPT_LEGAL_REVIEW,
    CONCEPT_REDESIGN,
    CONCEPT_HYPOTHESIS_ALTERNATIVE,
    MARKETING_CONTENT_GENERATION
}
