package com.aivle.backend.taskrun.domain;
public enum TaskType {
    IDEA_ATTACHMENT_PARSE,
    IDEA_BRIEF_DERIVATION,
    CONCEPT_PORTFOLIO_V2_RUN,
    CONCEPT_PORTFOLIO_V2_CONTINUE,
    CONCEPT_PORTFOLIO_V2_SELECTION_ACTION,
    CONCEPT_FACTORY_RUN,
    CONCEPT_CANDIDATE,
    CONCEPT_DISTINCTNESS_JUDGE,
    CONCEPT_LEGAL_REVIEW,
    CONCEPT_REDESIGN,
    CONCEPT_HYPOTHESIS_ALTERNATIVE,
    CONCEPT_DELTA_LEGAL_REVIEW,
    TECH_OPS_PROPOSAL,
    TECH_OPS_ADVISORY,
    FINANCE_ESTIMATE,
    FINANCE_ANALYSIS_REPORT,
    MARKETING_CONTENT_GENERATION,
    MARKETING_VISUAL_GENERATION,
    MARKET_RESEARCH,
    TWIN_SURVEY,
    TWIN_STIMULUS_DRAFT
}
