package com.aivle.backend.journey;
import com.aivle.backend.common.exception.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.JsonNode;import tools.jackson.databind.ObjectMapper;
@Service
public class MarketingReportPersistenceService{
 private final JourneyMarketingWorkspaceRepository workspaces;private final JourneyMarketingGenerationRunRepository generationRuns;private final JourneyMarketingAssetRepository assets;private final JourneyMarketingAssetVersionRepository versions;private final JourneyMarketingComparisonRunRepository comparisonRuns;private final JourneyMarketingComparisonRepository comparisons;private final JourneyFinalReportRepository reports;private final JourneyFinalReportVersionRepository reportVersions;private final ObjectMapper mapper;
 public MarketingReportPersistenceService(JourneyMarketingWorkspaceRepository workspaces,JourneyMarketingGenerationRunRepository generationRuns,JourneyMarketingAssetRepository assets,JourneyMarketingAssetVersionRepository versions,JourneyMarketingComparisonRunRepository comparisonRuns,JourneyMarketingComparisonRepository comparisons,JourneyFinalReportRepository reports,JourneyFinalReportVersionRepository reportVersions,ObjectMapper mapper){this.workspaces=workspaces;this.generationRuns=generationRuns;this.assets=assets;this.versions=versions;this.comparisonRuns=comparisonRuns;this.comparisons=comparisons;this.reports=reports;this.reportVersions=reportVersions;this.mapper=mapper;}
 @Transactional public void completeGeneration(Long runId,JsonNode result){JourneyMarketingGenerationRun run=generationRuns.findById(runId).orElseThrow(this::notFound);JourneyMarketingWorkspace workspace=workspaces.findById(run.getWorkspace().getId()).orElseThrow(this::notFound);if(run.getState()==JourneyMarketingGenerationRun.State.SUCCEEDED)return;if(assets.findByWorkspaceIdAndDeletedAtIsNullOrderByAssetTypeAscDisplayOrderAsc(workspace.getId()).isEmpty()){addSingle(run,JourneyMarketingAsset.Type.POSITIONING,"Positioning",mapper.valueToTree(result.get("positioning")));addSingle(run,JourneyMarketingAsset.Type.CORE_MESSAGE,"Core Message",mapper.valueToTree(result.get("coreMessage")));addMany(run,JourneyMarketingAsset.Type.SLOGAN,"Slogan",result.get("slogans"));addMany(run,JourneyMarketingAsset.Type.SOCIAL_COPY,"Social Copy",result.get("socialCopies"));addSingle(run,JourneyMarketingAsset.Type.LANDING_HERO,"Landing Hero",result.get("landingHero"));JsonNode emailCopies=result.get("emailCopies");if(emailCopies!=null&&!emailCopies.isEmpty())addMany(run,JourneyMarketingAsset.Type.EMAIL_COPY,"Email Copy",emailCopies);addMany(run,JourneyMarketingAsset.Type.CHANNEL_PLAN,"Channel Plan",result.get("channelPlan"));}run.succeed(result.toString());workspace.ready();}
 private void addSingle(JourneyMarketingGenerationRun run,JourneyMarketingAsset.Type type,String title,JsonNode content){JourneyMarketingAsset asset=assets.save(JourneyMarketingAsset.create(run.getProject(),run.getConceptVersion(),run.getWorkspace(),run,type,1));versions.save(JourneyMarketingAssetVersion.create(run.getProject(),run.getConceptVersion(),asset,title,content.toString()));}
 private void addMany(JourneyMarketingGenerationRun run,JourneyMarketingAsset.Type type,String title,JsonNode values){int order=1;for(JsonNode value:values){JourneyMarketingAsset asset=assets.save(JourneyMarketingAsset.create(run.getProject(),run.getConceptVersion(),run.getWorkspace(),run,type,order));versions.save(JourneyMarketingAssetVersion.create(run.getProject(),run.getConceptVersion(),asset,title+" "+order,value.toString()));order++;}}
 @Transactional public void selectAsset(Long projectId,Long workspaceId,Long assetId){JourneyMarketingAsset selected=assets.findById(assetId).filter(v->v.getProject().getId().equals(projectId)&&v.getWorkspace().getId().equals(workspaceId)).orElseThrow(this::notFound);for(JourneyMarketingAsset asset:assets.findByWorkspaceIdAndDeletedAtIsNullOrderByAssetTypeAscDisplayOrderAsc(workspaceId))if(asset.getAssetType()==selected.getAssetType())asset.select(asset.getId().equals(assetId));}
 @Transactional public void completeComparison(Long runId,JsonNode result){JourneyMarketingComparisonRun run=comparisonRuns.findById(runId).orElseThrow(this::notFound);if(run.getState()==JourneyMarketingComparisonRun.State.SUCCEEDED)return;if(comparisons.findByRunIdAndDeletedAtIsNull(runId).isEmpty())comparisons.save(JourneyMarketingComparison.create(run.getProject(),run.getConceptVersion(),run.getWorkspace(),run,result.toString()));run.succeed(result.toString());}
 @Transactional public void completeReport(Long reportId,JsonNode result){JourneyFinalReport report=reports.findById(reportId).orElseThrow(this::notFound);if(report.getState()==JourneyFinalReport.State.SUCCEEDED)return;report.succeed(JourneyFinalReport.Decision.valueOf(result.get("decision").asText()),result.toString());if(reportVersions.findTopByReportIdAndDeletedAtIsNullOrderByVersionNumberDesc(reportId).isEmpty())reportVersions.save(JourneyFinalReportVersion.create(report.getProject(),report.getConceptVersion(),report,result.toString()));}
 @Transactional public void decide(Long projectId,Long reportId,JourneyFinalReport.Decision decision,List<String> reasons){JourneyFinalReport report=reports.findById(reportId).filter(v->v.getProject().getId().equals(projectId)&&v.getState()==JourneyFinalReport.State.SUCCEEDED).orElseThrow(this::notFound);report.decide(decision,mapper.valueToTree(reasons).toString());}
 @Transactional public void failGeneration(Long runId,String error){generationRuns.findById(runId).ifPresent(v->{v.fail(error);workspaces.findById(v.getWorkspace().getId()).ifPresent(w->w.fail(error));});}
 @Transactional public void failComparison(Long runId,String error){comparisonRuns.findById(runId).ifPresent(v->v.fail(error));}
 @Transactional public void failReport(Long id,String error){reports.findById(id).ifPresent(v->v.fail(error));}
 private BusinessException notFound(){return new BusinessException(ErrorCode.RESOURCE_NOT_FOUND);}
}
