package com.aivle.backend.journey;

import com.aivle.backend.common.exception.BusinessException; import com.aivle.backend.common.exception.ErrorCode;
import com.aivle.backend.project.entity.Project; import com.aivle.backend.project.repository.ProjectRepository;
import com.aivle.backend.taskrun.domain.*; import com.aivle.backend.taskrun.integration.InternalAiExecutionClient; import com.aivle.backend.taskrun.integration.InternalAiExecutionClient.ExecutionFailure;
import com.aivle.backend.taskrun.service.CanonicalInputHasher; import com.aivle.backend.taskrun.service.TaskRunService;
import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import org.springframework.stereotype.Service;
import tools.jackson.databind.JsonNode; import tools.jackson.databind.ObjectMapper; import tools.jackson.databind.node.ObjectNode;

@Service
public class PersonaJourneyService {
    private final ProjectRepository projects; private final IdeaVersionRepository ideas; private final ConceptSelectionRepository selections; private final ConceptVersionRepository concepts;
    private final PersonaStudyRepository studies; private final PersonaCardVersionRepository personaVersions; private final PersonaInterviewRepository interviews;
    private final PersonaInterviewMessageRepository messages; private final InterviewSynthesisRunRepository synthesisRuns; private final InterviewSynthesisRepository syntheses;
    private final TaskRunService taskRuns; private final InternalAiExecutionClient ai; private final CanonicalInputHasher hasher; private final ObjectMapper mapper; private final PersonaJourneyPersistenceService persistence;
    public PersonaJourneyService(ProjectRepository projects,IdeaVersionRepository ideas,ConceptSelectionRepository selections,ConceptVersionRepository concepts,
            PersonaStudyRepository studies,PersonaCardVersionRepository personaVersions,PersonaInterviewRepository interviews,PersonaInterviewMessageRepository messages,
            InterviewSynthesisRunRepository synthesisRuns,InterviewSynthesisRepository syntheses,TaskRunService taskRuns,InternalAiExecutionClient ai,
            CanonicalInputHasher hasher,ObjectMapper mapper,PersonaJourneyPersistenceService persistence){this.projects=projects;this.ideas=ideas;this.selections=selections;this.concepts=concepts;this.studies=studies;this.personaVersions=personaVersions;this.interviews=interviews;this.messages=messages;this.synthesisRuns=synthesisRuns;this.syntheses=syntheses;this.taskRuns=taskRuns;this.ai=ai;this.hasher=hasher;this.mapper=mapper;this.persistence=persistence;}

    public StudyView createStudy(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy current=currentStudyEntity(projectId,c.concept().getId());if(current!=null)return studyView(current);return studyView(studies.save(PersonaStudy.create(c.project(),c.idea(),c.concept())));}
    public StudyView currentStudy(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy study=currentStudyEntity(projectId,c.concept().getId());return study==null?null:studyView(study);}

    public List<PersonaView> generate(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy study=currentStudyEntity(projectId,c.concept().getId());if(study==null)study=studies.save(PersonaStudy.create(c.project(),c.idea(),c.concept()));List<PersonaCardVersion> existing=personaVersions.findCurrentByStudy(study.getId());if(study.getState()==PersonaStudy.State.READY&&!existing.isEmpty())return existing.stream().map(this::personaView).toList();if(study.getState()==PersonaStudy.State.GENERATING)throw new BusinessException(ErrorCode.ANALYSIS_ALREADY_RUNNING);
        TaskRun task=createTask(ownerId,c.project(),TaskType.PERSONA_CARD_GENERATION,"CONCEPT_VERSION",c.concept().getId().toString(),personaGenerationInput(c.concept()));study.start(task);studies.save(study);Long studyId=study.getId();
        try{JsonNode result=execute(task,this::validatePersonas);persistence.completeStudy(studyId,result);}catch(ExecutionFailure f){persistence.failStudy(studyId,f.reason());throw publicFailure(f);}catch(RuntimeException f){persistence.failStudy(studyId,"AI_RESULT_INVALID");throw normalized(f);}return cards(ownerId,projectId);}

    public List<PersonaView> cards(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy study=currentStudyEntity(projectId,c.concept().getId());return study==null?List.of():personaVersions.findCurrentByStudy(study.getId()).stream().map(this::personaView).toList();}

    public List<InterviewView> interview(Long ownerId,Long projectId,InterviewRequest request){Context c=context(ownerId,projectId);PersonaStudy study=requireReadyStudy(projectId,c.concept().getId());List<Long> ids=distinct(request.personaCardVersionIds());List<PersonaCardVersion> selected=personaVersions.findByIdInAndProjectIdAndConceptVersionIdAndDeletedAtIsNull(ids,projectId,c.concept().getId());if(ids.isEmpty()||selected.size()!=ids.size()||selected.stream().anyMatch(v->!v.getPersonaCard().getStudy().getId().equals(study.getId())))throw new BusinessException(ErrorCode.ANALYSIS_INPUT_INVALID);persistence.selectPersonas(study.getId(),ids);
        Map<Long,PersonaInterview> current=currentInterviewMap(study.getId());BusinessException firstFailure=null;
        for(PersonaCardVersion persona:selected){PersonaInterview prior=current.get(persona.getId());if(prior!=null&&prior.getState()==PersonaInterview.State.SUCCEEDED)continue;if(prior!=null&&(prior.getState()==PersonaInterview.State.PENDING||prior.getState()==PersonaInterview.State.RUNNING))continue;PersonaInterview run=interviews.save(PersonaInterview.pending(c.project(),c.concept(),study,persona));TaskRun task=createTask(ownerId,c.project(),TaskType.PERSONA_INTERVIEW,"PERSONA_CARD_VERSION",persona.getId().toString(),interviewInput(c.concept(),persona));run.start(task);interviews.save(run);
            try{JsonNode result=execute(task,this::validateInterview);persistence.completeInterview(run.getId(),result);}catch(ExecutionFailure f){persistence.failInterview(run.getId(),f.reason());if(firstFailure==null)firstFailure=publicFailure(f);}catch(RuntimeException f){persistence.failInterview(run.getId(),"AI_RESULT_INVALID");if(firstFailure==null)firstFailure=normalized(f);}}
        if(firstFailure!=null)throw firstFailure;return interviews(ownerId,projectId);}

    public List<InterviewView> interviews(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy study=currentStudyEntity(projectId,c.concept().getId());if(study==null)return List.of();return currentInterviewMap(study.getId()).values().stream().map(this::interviewView).sorted(Comparator.comparing(InterviewView::personaDisplayOrder)).toList();}

    public SynthesisView synthesize(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy study=requireReadyStudy(projectId,c.concept().getId());List<PersonaCardVersion> selected=personaVersions.findCurrentByStudy(study.getId()).stream().filter(v->v.getPersonaCard().isSelected()).toList();if(selected.isEmpty())throw new BusinessException(ErrorCode.ANALYSIS_INPUT_INVALID);Map<Long,PersonaInterview> current=currentInterviewMap(study.getId());List<PersonaInterview> completed=selected.stream().map(v->current.get(v.getId())).filter(Objects::nonNull).filter(v->v.getState()==PersonaInterview.State.SUCCEEDED).toList();if(completed.size()!=selected.size())throw new BusinessException(ErrorCode.ANALYSIS_INPUT_INVALID);
        String interviewIds=mapper.valueToTree(completed.stream().map(PersonaInterview::getId).toList()).toString();InterviewSynthesisRun existing=synthesisRuns.findTopByStudyIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(study.getId()).orElse(null);if(existing!=null&&existing.getState()==InterviewSynthesisRun.State.SUCCEEDED&&existing.getInterviewIdsJson().equals(interviewIds))return synthesisView(existing);if(existing!=null&&(existing.getState()==InterviewSynthesisRun.State.PENDING||existing.getState()==InterviewSynthesisRun.State.RUNNING))throw new BusinessException(ErrorCode.ANALYSIS_ALREADY_RUNNING);
        InterviewSynthesisRun run=synthesisRuns.save(InterviewSynthesisRun.pending(c.project(),c.concept(),study,interviewIds));TaskRun task=createTask(ownerId,c.project(),TaskType.INTERVIEW_SYNTHESIS,"PERSONA_STUDY",study.getId().toString(),synthesisInput(c.concept(),completed));run.start(task);synthesisRuns.save(run);
        try{JsonNode result=execute(task,this::validateSynthesis);persistence.completeSynthesis(run.getId(),result);}catch(ExecutionFailure f){persistence.failSynthesis(run.getId(),f.reason());throw publicFailure(f);}catch(RuntimeException f){persistence.failSynthesis(run.getId(),"AI_RESULT_INVALID");throw normalized(f);}return currentSynthesis(ownerId,projectId);}

    public SynthesisView currentSynthesis(Long ownerId,Long projectId){Context c=context(ownerId,projectId);PersonaStudy study=currentStudyEntity(projectId,c.concept().getId());if(study==null)return null;InterviewSynthesisRun run=synthesisRuns.findTopByStudyIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(study.getId()).orElse(null);if(run==null)return null;List<PersonaCardVersion> selected=personaVersions.findCurrentByStudy(study.getId()).stream().filter(v->v.getPersonaCard().isSelected()).toList();Map<Long,PersonaInterview> current=currentInterviewMap(study.getId());List<Long> ids=selected.stream().map(v->current.get(v.getId())).filter(Objects::nonNull).filter(v->v.getState()==PersonaInterview.State.SUCCEEDED).map(PersonaInterview::getId).toList();String expected=mapper.valueToTree(ids).toString();return run.getInterviewIdsJson().equals(expected)?synthesisView(run):null;}

    private Context context(Long ownerId,Long projectId){Project p=projects.findByIdAndOwnerIdAndDeletedAtIsNull(projectId,ownerId).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_ACCESS_DENIED));IdeaVersion idea=ideas.findCurrent(projectId).filter(IdeaVersion::isConfirmed).orElseThrow(()->new BusinessException(ErrorCode.IDEA_NOT_CONFIRMED));ConceptSelection selection=selections.findTopByProjectIdAndIdeaVersionIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(projectId,idea.getId()).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_STAGE_INVALID));ConceptVersion concept=concepts.findByIdInAndProjectIdAndIdeaVersionIdAndDeletedAtIsNull(List.of(selection.getConceptVersion().getId()),projectId,idea.getId()).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.PROJECT_STAGE_INVALID));return new Context(p,idea,concept);}
    private PersonaStudy currentStudyEntity(Long p,Long c){return studies.findTopByProjectIdAndConceptVersionIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(p,c).orElse(null);}private PersonaStudy requireReadyStudy(Long p,Long c){PersonaStudy s=currentStudyEntity(p,c);if(s==null||s.getState()!=PersonaStudy.State.READY)throw new BusinessException(ErrorCode.ANALYSIS_INPUT_INVALID);return s;}
    private Map<Long,PersonaInterview> currentInterviewMap(Long studyId){Map<Long,PersonaInterview> result=new LinkedHashMap<>();for(PersonaInterview v:interviews.findByStudyIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(studyId))result.putIfAbsent(v.getPersonaCardVersion().getId(),v);return result;}
    private TaskRun createTask(Long ownerId,Project p,TaskType type,String subjectType,String subjectId,String input){String nonce=UUID.randomUUID().toString();return taskRuns.create(ownerId,p.getId(),type,subjectType,subjectId,input,hasher.hash(type,"1.0","ko-KR",input),nonce,nonce,1);}
    private JsonNode execute(TaskRun run,java.util.function.Consumer<JsonNode> validator){TaskRunService.Claim claim=taskRuns.claim(run.getId(),"journey-sync",Duration.ofMinutes(2),Duration.ofMinutes(2));taskRuns.startExecution(claim.taskRunId(),claim.taskAttemptId(),claim.claimToken());try{var response=ai.execute(taskRuns.getOwnedForWorker(run.getId()),claim.taskAttemptId(),LocalDateTime.now().plusMinutes(2));try{validator.accept(response.result());}catch(BusinessException invalid){taskRuns.rejectAndFail(run.getId(),claim.taskAttemptId(),claim.claimToken(),response.result().toString(),response.resultSchemaVersion(),"AI_RESULT_INVALID");throw invalid;}taskRuns.adopt(run.getId(),claim.taskAttemptId(),claim.claimToken(),response.result().toString(),response.canonicalInputHash(),response.resultSchemaVersion());return response.result();}catch(ExecutionFailure f){taskRuns.fail(run.getId(),claim.taskAttemptId(),claim.claimToken(),f.code(),f.reason(),f.retryable());throw f;}}
    private String personaGenerationInput(ConceptVersion c){ObjectNode n=conceptJson(c);return taskInput("selected-concept",n.toString());}
    private String interviewInput(ConceptVersion c,PersonaCardVersion p){ObjectNode root=mapper.createObjectNode();root.set("selectedConcept",conceptJson(c));ObjectNode persona=root.putObject("persona");persona.put("personaCardVersionId",p.getId());persona.put("name",p.getName());persona.put("shortLabel",p.getShortLabel());persona.set("roleAndContext",parse(p.getRoleAndContextJson()));persona.set("problemAndNeeds",parse(p.getProblemAndNeedsJson()));persona.set("behaviorAndDecision",parse(p.getBehaviorAndDecisionJson()));persona.set("interviewFocus",parse(p.getInterviewFocusJson()));return taskInput("independent-persona",root.toString());}
    private String synthesisInput(ConceptVersion c,List<PersonaInterview> values){ObjectNode root=mapper.createObjectNode();root.set("selectedConcept",conceptJson(c));var array=root.putArray("independentInterviews");for(PersonaInterview v:values){ObjectNode item=array.addObject();item.put("personaCardVersionId",v.getPersonaCardVersion().getId());item.put("personaName",v.getPersonaCardVersion().getName());item.set("messages",parse(v.getResultJson()).get("messages"));}return taskInput("completed-interviews",root.toString());}
    private ObjectNode conceptJson(ConceptVersion c){ObjectNode n=mapper.createObjectNode();n.put("conceptVersionId",c.getId());n.put("name",c.getName());n.put("summary",c.getOneLineSummary());n.put("targetCustomer",c.getTargetCustomer());n.put("problem",c.getProblem());n.put("solution",c.getSolution());n.put("valueProposition",c.getValueProposition());return n;}
    private String taskInput(String key,String text){ObjectNode content=mapper.createObjectNode();content.put("contentKey",key);content.put("contentType","TEXT");content.put("language","ko-KR");content.put("totalCharacters",text.codePointCount(0,text.length()));content.put("contentHash",sha256(text));var chunks=content.putArray("chunks");int offset=0,index=0;while(offset<text.length()){int count=Math.min(16000,text.codePointCount(offset,text.length()));int next=text.offsetByCodePoints(offset,count);String value=text.substring(offset,next);ObjectNode chunk=chunks.addObject();chunk.put("index",index++);chunk.put("text",value);chunk.put("characterCount",count);chunk.put("chunkHash",sha256(value));offset=next;}ObjectNode root=mapper.createObjectNode();root.putArray("textContents").add(content);return root.toString();}
    private String sha256(String text){try{return "sha256:"+HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private void validatePersonas(JsonNode r){if(r==null||!r.has("personas")||!r.get("personas").isArray()||r.get("personas").size()!=3)throw invalid();for(JsonNode p:r.get("personas")){text(p,"name");text(p,"shortLabel");if(p.get("name").asText().length()>200||p.get("shortLabel").asText().length()>200)throw invalid();object(p,"roleAndContext",List.of("role","situation"),List.of("goals","constraints"));object(p,"problemAndNeeds",List.of(),List.of("problems","unmetNeeds","desiredOutcomes"));object(p,"behaviorAndDecision",List.of(),List.of("currentBehavior","decisionCriteria","barriers","informationSources"));array(p,"interviewFocus");}}
    private void validateInterview(JsonNode r){if(r==null||!r.has("messages")||!r.get("messages").isArray()||r.get("messages").size()<5)throw invalid();Set<String> categories=new HashSet<>();for(JsonNode m:r.get("messages")){String category=text(m,"category");try{PersonaInterviewMessage.Category.valueOf(category);}catch(IllegalArgumentException e){throw invalid();}categories.add(category);text(m,"question");text(m,"answer");}if(categories.size()!=3)throw invalid();}
    private void validateSynthesis(JsonNode r){for(String f:List.of("commonThemes","conflictingViews","criticalNeeds","decisionBarriers","implications","researchNeeds"))array(r,f);}
    private void object(JsonNode n,String f,List<String> texts,List<String> arrays){JsonNode v=n.get(f);if(v==null||!v.isObject())throw invalid();texts.forEach(x->text(v,x));arrays.forEach(x->array(v,x));}private void array(JsonNode n,String f){if(n==null||!n.has(f)||!n.get(f).isArray())throw invalid();}private String text(JsonNode n,String f){if(n==null||!n.has(f)||!n.get(f).isTextual()||n.get(f).asText().isBlank())throw invalid();return n.get(f).asText();}
    private JsonNode parse(String value){return value==null?null:mapper.readTree(value);}private List<Long> distinct(List<Long> ids){return ids==null?List.of():ids.stream().filter(Objects::nonNull).distinct().toList();}private BusinessException invalid(){return new BusinessException(ErrorCode.AI_RESULT_INVALID);}private BusinessException normalized(RuntimeException f){return f instanceof BusinessException b?b:invalid();}private BusinessException publicFailure(ExecutionFailure f){if("AI_CONFIGURATION_INVALID".equals(f.reason()))return new BusinessException(ErrorCode.AI_CONFIGURATION_INVALID);if("AI_RESULT_INVALID".equals(f.reason())||"RESULT_SCHEMA_INVALID".equals(f.code()))return invalid();return new BusinessException(ErrorCode.EXTERNAL_AI_SERVICE_UNAVAILABLE);}
    private StudyView studyView(PersonaStudy s){return new StudyView(s.getId(),s.getConceptVersion().getId(),s.getConceptVersion().getName(),s.getState().name(),s.getSyntheticNotice(),s.getError(),s.getCreatedAt(),s.getCompletedAt());}
    private PersonaView personaView(PersonaCardVersion v){return new PersonaView(v.getId(),v.getPersonaCard().getId(),v.getPersonaCard().getDisplayOrder(),v.getName(),v.getShortLabel(),parse(v.getRoleAndContextJson()),parse(v.getProblemAndNeedsJson()),parse(v.getBehaviorAndDecisionJson()),parse(v.getInterviewFocusJson()),v.getPersonaCard().isSelected(),true);}
    private InterviewView interviewView(PersonaInterview v){List<MessageView> list=messages.findByInterviewIdAndDeletedAtIsNullOrderBySequenceNumber(v.getId()).stream().map(m->new MessageView(m.getSequenceNumber(),m.getCategory().name(),m.getQuestion(),m.getAnswer())).toList();return new InterviewView(v.getId(),v.getPersonaCardVersion().getId(),v.getPersonaCardVersion().getPersonaCard().getDisplayOrder(),v.getPersonaCardVersion().getName(),v.getState().name(),list,v.getError(),v.getCompletedAt());}
    private SynthesisView synthesisView(InterviewSynthesisRun run){InterviewSynthesis value=syntheses.findByRunIdAndDeletedAtIsNull(run.getId()).orElse(null);return new SynthesisView(run.getId(),run.getState().name(),value==null?null:parse(value.getCommonThemesJson()),value==null?null:parse(value.getConflictingViewsJson()),value==null?null:parse(value.getCriticalNeedsJson()),value==null?null:parse(value.getDecisionBarriersJson()),value==null?null:parse(value.getImplicationsJson()),value==null?null:parse(value.getResearchNeedsJson()),run.getError(),run.getCompletedAt());}
    private record Context(Project project,IdeaVersion idea,ConceptVersion concept){}
    public record InterviewRequest(List<Long> personaCardVersionIds){}
    public record StudyView(Long id,Long conceptVersionId,String conceptName,String state,String syntheticNotice,String error,LocalDateTime createdAt,LocalDateTime completedAt){}
    public record PersonaView(Long id,Long personaCardId,int displayOrder,String name,String shortLabel,JsonNode roleAndContext,JsonNode problemAndNeeds,JsonNode behaviorAndDecision,JsonNode interviewFocus,boolean selected,boolean synthetic){}
    public record MessageView(int sequenceNumber,String category,String question,String answer){}
    public record InterviewView(Long id,Long personaCardVersionId,int personaDisplayOrder,String personaName,String state,List<MessageView> messages,String error,LocalDateTime completedAt){}
    public record SynthesisView(Long id,String state,JsonNode commonThemes,JsonNode conflictingViews,JsonNode criticalNeeds,JsonNode decisionBarriers,JsonNode implications,JsonNode researchNeeds,String error,LocalDateTime completedAt){}
}
