package com.aivle.backend.common.entity;
public enum JobType {
    DOCUMENT_PARSE, LEGAL_REVIEW, FEASIBILITY_ANALYSIS, MARKET_ANALYSIS, BM_ANALYSIS,
    TECH_OPERATION_ANALYSIS, FINANCIAL_ANALYSIS, PERSONA_GENERATION, PERSONA_RECOMMENDATION,
    FGI_SIMULATION, FGD_SIMULATION, REPORT_GENERATION, MARKETING_GENERATION,
    SYSTEM_SMOKE_TEST, SYSTEM_ARTIFACT_SMOKE_TEST
}
