package com.aivle.backend.common.entity;
public enum PlanSectionType {
    OVERVIEW, PRODUCT_SERVICE, MARKET, TARGET_CUSTOMER, COMPETITION,
    BUSINESS_MODEL, TECHNOLOGY_OPERATION, FINANCIAL, LEGAL_REGULATION,
    SCHEDULE, RISK, EVIDENCE, OTHER
}
