package com.aivle.backend.common.entity;
public enum ProjectStage {
    DOCUMENT, STRUCTURING, LEGAL_REVIEW, FEASIBILITY, FINANCIAL,
    PERSONA_CONFIGURATION, PANEL_SURVEY, PANEL_DISCUSSION, REPORT,
    MARKETING, COMPLETED
}
