package com.aivle.backend.document.parsing;

public enum DocumentParseErrorCode {
    DOCUMENT_FORMAT_UNSUPPORTED,
    DOCUMENT_CORRUPTED,
    DOCUMENT_EMPTY,
    DOCUMENT_TOO_LARGE,
    DOCUMENT_LIMIT_EXCEEDED,
    DOCUMENT_ENCRYPTED,
    DOCUMENT_FILENAME_UNSAFE,
    DOCUMENT_PARSE_FAILED
}
