package com.aivle.backend.analysis.legal.entity;

public enum LegalCategory {
    BUSINESS_REGISTRATION,
    LICENSE_AND_PERMIT,
    PRIVACY_AND_DATA,
    TERMS_AND_CONTRACT,
    INTELLECTUAL_PROPERTY,
    CONSUMER_PROTECTION,
    ADVERTISING_AND_MARKETING,
    LABOR_AND_EMPLOYMENT,
    INDUSTRY_SPECIFIC,
    TAX_AND_FINANCIAL
}
