-- 시장조사 · BM 캔버스 (판 ㉝)
--
-- ⚠ **버전 번호 주의.** `AI_MODULE_INTEGRATION_GUIDE.md` 와 `시장조사/CLAUDE.md` 는
--    「다음 빈 버전은 V37」이라고 적어 두었지만 그것은 stale 이다. 커밋 0eb4f5f 가
--    V1~V36 을 `V1__baseline_schema.sql` 하나로 압축했고, 실제 다음 번호는 **V2** 다.
--
-- `task_runs.task_type` 은 `VARCHAR(50)` 이고 CHECK 제약이 없어 enum 값 추가에
-- 마이그레이션이 필요 없다 — 여기서 만드는 것은 **도메인 쪽 두 테이블**뿐이다.

CREATE TABLE market_research_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    -- FULL = 1단계(시장조사 전 구간) · BM = 2단계(캔버스). 한 TaskType 의 두 모드다.
    kind VARCHAR(10) NOT NULL,
    -- 2단계가 1단계 결과를 가리킨다. FULL 이면 NULL.
    source_run_id BIGINT,
    task_run_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_research_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_run_source FOREIGN KEY (source_run_id) REFERENCES market_research_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_research_run_task UNIQUE (task_run_id),
    CONSTRAINT ck_market_research_run_kind CHECK (kind IN ('FULL', 'BM')),
    CONSTRAINT ck_market_research_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX idx_market_research_runs_project ON market_research_runs(project_id, kind, created_at DESC);

CREATE TABLE market_research_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    kind VARCHAR(10) NOT NULL,
    version_number INTEGER NOT NULL,

    -- ⚠ 결과는 **통째로** 둔다. 쪼개면 그 순간 스키마가 두 곳(여기와 계약)에 생기고,
    --   계약이 바뀔 때마다 마이그레이션이 따라와야 한다. 아래 스칼라는 **목록·배지용 사본**이고
    --   판정의 근거가 아니다 — 판정은 언제나 result_json 을 읽는다.
    result_json TEXT NOT NULL,

    -- 목록에서 훑기 위한 값 (FULL)
    filled_count INTEGER,
    partial_count INTEGER,
    missing_count INTEGER,
    -- 목록에서 훑기 위한 값 (BM)
    decision VARCHAR(20),
    confidence VARCHAR(10),
    -- 두 모드 공통. **경계 수를 세어 둔다** — 0 으로 떨어지면 소실을 눈으로 본다.
    evidence_count INTEGER NOT NULL,
    caveat_count INTEGER NOT NULL,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_research_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_version_run FOREIGN KEY (source_run_id) REFERENCES market_research_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_research_version_run UNIQUE (source_run_id),
    CONSTRAINT ck_market_research_version_kind CHECK (kind IN ('FULL', 'BM'))
);

CREATE INDEX idx_market_research_versions_project ON market_research_versions(project_id, kind, version_number DESC);
