CREATE TABLE concept_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    selection_reason VARCHAR(2000) NOT NULL,
    request_hash VARCHAR(71) NOT NULL,
    selected_by_user_id BIGINT NOT NULL,
    selected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_selection_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_concept_selection_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_selection_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_selection_user FOREIGN KEY (selected_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_selection_hash CHECK (request_hash LIKE 'sha256:%')
);

CREATE UNIQUE INDEX uk_concept_selection_current ON concept_selections(project_id) WHERE is_current = TRUE AND deleted_at IS NULL;
CREATE INDEX idx_concept_selection_project ON concept_selections(project_id, selected_at DESC);

CREATE TABLE selected_concept_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    selection_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    sequence_number INTEGER NOT NULL,
    parent_snapshot_id VARCHAR(64),
    source_concept_hash VARCHAR(71) NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    selected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_selected_snapshot_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_selected_snapshot_selection UNIQUE (selection_id),
    CONSTRAINT uk_selected_snapshot_sequence UNIQUE (project_id, sequence_number),
    CONSTRAINT fk_selected_snapshot_selection FOREIGN KEY (selection_id, project_id) REFERENCES concept_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_selected_snapshot_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_selected_snapshot_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_selected_snapshot_parent FOREIGN KEY (parent_snapshot_id, project_id) REFERENCES selected_concept_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_selected_snapshot_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_selected_snapshot_sequence CHECK (sequence_number > 0),
    CONSTRAINT ck_selected_snapshot_hashes CHECK (source_concept_hash LIKE 'sha256:%' AND snapshot_hash LIKE 'sha256:%')
);

CREATE INDEX idx_selected_snapshot_project ON selected_concept_snapshots(project_id, sequence_number DESC);

CREATE TABLE module_handoffs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    module VARCHAR(40) NOT NULL,
    input_contract VARCHAR(100) NOT NULL,
    input_snapshot_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    requested_operation VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    callback_mode VARCHAR(30) NOT NULL,
    callback_reference VARCHAR(500) NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_module_handoff_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_module_handoff_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_module_handoff_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_snapshot FOREIGN KEY (input_snapshot_id, project_id) REFERENCES selected_concept_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_module_handoff_module CHECK (module IN ('MARKET_ANALYSIS')),
    CONSTRAINT ck_module_handoff_status CHECK (status IN ('PREPARED')),
    CONSTRAINT ck_module_handoff_hashes CHECK (input_snapshot_hash LIKE 'sha256:%' AND idempotency_key LIKE 'sha256:%')
);

CREATE INDEX idx_module_handoff_project ON module_handoffs(project_id, requested_at DESC);

CREATE TABLE module_runs (
    id VARCHAR(64) PRIMARY KEY,
    handoff_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    module VARCHAR(40) NOT NULL,
    input_snapshot_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    external_run_reference VARCHAR(500),
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    result_reference VARCHAR(1000),
    result_hash VARCHAR(71),
    safe_error_code VARCHAR(80),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_module_run_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_module_run_handoff UNIQUE (handoff_id),
    CONSTRAINT fk_module_run_handoff FOREIGN KEY (handoff_id, project_id) REFERENCES module_handoffs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_run_snapshot FOREIGN KEY (input_snapshot_id, project_id) REFERENCES selected_concept_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_module_run_module CHECK (module IN ('MARKET_ANALYSIS')),
    CONSTRAINT ck_module_run_status CHECK (status IN ('NOT_CONNECTED','READY','QUEUED','RUNNING','COMPLETED','FAILED','STALE')),
    CONSTRAINT ck_module_run_hashes CHECK (input_snapshot_hash LIKE 'sha256:%' AND (result_hash IS NULL OR result_hash LIKE 'sha256:%'))
);

CREATE INDEX idx_module_run_project ON module_runs(project_id, created_at DESC);
