-- 패널 트윈 조사 (TWIN_SURVEY)
--
-- `task_runs.task_type` 은 VARCHAR(50) 이고 CHECK 제약이 없어 enum 값 추가에
-- 마이그레이션이 필요 없다 — 여기서 만드는 것은 도메인 쪽 두 테이블뿐이다.
-- V10 까지가 기존이고 다음 빈 번호가 V11 임을 파일 목록으로 확인했다.

CREATE TABLE twin_survey_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_run_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    -- 표본 크기를 실행에 남긴다. 같은 자극이라도 n 이 다르면 「못 잼」과 「이김」이 갈린다 —
    -- 어떤 표본으로 잰 결과인지가 값과 떨어지면 그 결과는 해석할 수 없다.
    sample_size INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_twin_survey_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_twin_survey_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_twin_survey_run_task UNIQUE (task_run_id),
    CONSTRAINT ck_twin_survey_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    -- 화면이 고르는 세 값. MDE 표가 이 셋으로만 실측돼 있다.
    CONSTRAINT ck_twin_survey_run_sample_size CHECK (sample_size IN (50, 100, 300))
);

CREATE INDEX idx_twin_survey_runs_project ON twin_survey_runs(project_id, created_at DESC);

CREATE TABLE twin_survey_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,

    -- 결과는 통째로 둔다. 아래 스칼라는 목록·배지용 사본이고 판정의 근거가 아니다.
    result_json TEXT NOT NULL,

    sample_size INTEGER NOT NULL,
    pair_count INTEGER NOT NULL,
    -- 「못 잼」은 실패가 아니라 정직한 산출이다. 세어 두지 않으면 못 잰 결과가 잰 결과처럼 앉는다.
    measurable_count INTEGER NOT NULL,
    -- 경계 수. 0 이면 계약이 이미 막았어야 한다 — 그래도 눈으로 본다.
    caveat_count INTEGER NOT NULL,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_twin_survey_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_twin_survey_version_run FOREIGN KEY (source_run_id) REFERENCES twin_survey_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_twin_survey_version_run UNIQUE (source_run_id)
);

CREATE INDEX idx_twin_survey_versions_project ON twin_survey_versions(project_id, version_number DESC);
