ALTER TABLE concept_portfolio_concepts
    ADD CONSTRAINT uk_cp_concept_id_project UNIQUE (id, project_id);

CREATE TABLE concept_portfolio_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(200) NOT NULL,
    selected_concept_hash VARCHAR(71) NOT NULL,
    base_legal_hash VARCHAR(71) NOT NULL,
    selection_reason VARCHAR(1000) NOT NULL,
    status VARCHAR(50) NOT NULL,
    active_task_run_id VARCHAR(64),
    active_action VARCHAR(40),
    hypothesis_revision INTEGER NOT NULL DEFAULT 0,
    request_hash VARCHAR(71) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    selected_by_user_id BIGINT NOT NULL,
    selected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    failure_code VARCHAR(80),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cp_selection_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_cp_selection_idempotency UNIQUE (project_id, idempotency_key),
    CONSTRAINT fk_cp_selection_run FOREIGN KEY (run_id, project_id)
        REFERENCES concept_portfolio_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_selection_concept FOREIGN KEY (concept_id, project_id)
        REFERENCES concept_portfolio_concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_selection_task FOREIGN KEY (active_task_run_id)
        REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_selection_user FOREIGN KEY (selected_by_user_id)
        REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_cp_selection_hashes CHECK (
        selected_concept_hash LIKE 'sha256:%' AND base_legal_hash LIKE 'sha256:%'
        AND request_hash LIKE 'sha256:%'),
    CONSTRAINT ck_cp_selection_status CHECK (status IN (
        'HYPOTHESES_PREPARING', 'PENDING_HYPOTHESIS_CONFIRMATION',
        'DELTA_LEGAL_PENDING', 'DELTA_LEGAL_FAILED', 'READY_FOR_LEGAL_REPORT',
        'LEGAL_REPORT_READY', 'MARKET_SEED_FINALIZING', 'READY_FOR_MARKET',
        'FAILED', 'STALE'))
);
CREATE UNIQUE INDEX uk_cp_selection_current ON concept_portfolio_selections(project_id)
    WHERE is_current = TRUE AND deleted_at IS NULL;
CREATE INDEX idx_cp_selection_project ON concept_portfolio_selections(project_id, selected_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE concept_portfolio_hypothesis_decisions (
    id VARCHAR(64) PRIMARY KEY,
    selection_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    hypothesis_type VARCHAR(40) NOT NULL,
    proposed_value_json TEXT NOT NULL,
    final_value_json TEXT,
    source VARCHAR(40) NOT NULL,
    decision_status VARCHAR(40) NOT NULL,
    proposal_version INTEGER NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    semantic_status VARCHAR(30) NOT NULL,
    semantic_reason TEXT,
    legal_impact VARCHAR(40) NOT NULL,
    legal_review_status VARCHAR(40) NOT NULL,
    delta_legal_required BOOLEAN NOT NULL DEFAULT FALSE,
    decided_by_user_id BIGINT,
    decided_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cp_hypothesis_version UNIQUE (selection_id, hypothesis_type, proposal_version),
    CONSTRAINT fk_cp_hypothesis_selection FOREIGN KEY (selection_id, project_id)
        REFERENCES concept_portfolio_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_hypothesis_concept FOREIGN KEY (concept_id, project_id)
        REFERENCES concept_portfolio_concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_hypothesis_user FOREIGN KEY (decided_by_user_id)
        REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_cp_hypothesis_type CHECK (hypothesis_type IN (
        'TARGET_REGION', 'REVENUE_MODEL', 'PRICE', 'CHANNELS', 'DIFFERENTIATORS',
        'PRE_MARKET_SOM_SHARE', 'PRE_MARKET_SOM')),
    CONSTRAINT ck_cp_hypothesis_version CHECK (proposal_version > 0)
);
CREATE INDEX idx_cp_hypothesis_selection ON concept_portfolio_hypothesis_decisions
    (selection_id, hypothesis_type, proposal_version DESC) WHERE deleted_at IS NULL;

CREATE TABLE concept_portfolio_delta_legal_reviews (
    id VARCHAR(64) PRIMARY KEY,
    selection_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    task_run_id VARCHAR(64) NOT NULL,
    review_token VARCHAR(71) NOT NULL,
    hypothesis_types_json TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    approved BOOLEAN NOT NULL,
    legal_review_json TEXT NOT NULL,
    result_hash VARCHAR(71) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cp_delta_task UNIQUE (task_run_id),
    CONSTRAINT fk_cp_delta_selection FOREIGN KEY (selection_id, project_id)
        REFERENCES concept_portfolio_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_delta_concept FOREIGN KEY (concept_id, project_id)
        REFERENCES concept_portfolio_concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_delta_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT ck_cp_delta_hashes CHECK (review_token LIKE 'sha256:%' AND result_hash LIKE 'sha256:%')
);

CREATE TABLE concept_legal_regulatory_reports (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    selection_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    selected_concept_hash VARCHAR(71) NOT NULL,
    hypothesis_snapshot_hash VARCHAR(71) NOT NULL,
    base_legal_hash VARCHAR(71) NOT NULL,
    delta_legal_hash VARCHAR(71),
    official_evidence_hash VARCHAR(71) NOT NULL,
    report_json TEXT NOT NULL,
    report_hash VARCHAR(71) NOT NULL,
    basis_date DATE NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cp_legal_report_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_cp_legal_report_selection FOREIGN KEY (selection_id, project_id)
        REFERENCES concept_portfolio_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_legal_report_concept FOREIGN KEY (concept_id, project_id)
        REFERENCES concept_portfolio_concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_cp_legal_report_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_cp_legal_report_status CHECK (status IN ('CURRENT', 'STALE')),
    CONSTRAINT ck_cp_legal_report_hashes CHECK (
        selected_concept_hash LIKE 'sha256:%' AND hypothesis_snapshot_hash LIKE 'sha256:%'
        AND base_legal_hash LIKE 'sha256:%' AND (delta_legal_hash IS NULL OR delta_legal_hash LIKE 'sha256:%')
        AND official_evidence_hash LIKE 'sha256:%' AND report_hash LIKE 'sha256:%')
);
CREATE UNIQUE INDEX uk_cp_legal_report_current ON concept_legal_regulatory_reports(selection_id)
    WHERE status = 'CURRENT' AND deleted_at IS NULL;

ALTER TABLE market_analysis_seed_snapshots DROP CONSTRAINT fk_market_seed_snapshot_selection;
ALTER TABLE market_analysis_seed_snapshots DROP CONSTRAINT fk_market_seed_snapshot_concept;
ALTER TABLE market_analysis_seed_snapshots ALTER COLUMN selection_id DROP NOT NULL;
ALTER TABLE market_analysis_seed_snapshots ALTER COLUMN concept_id DROP NOT NULL;
ALTER TABLE market_analysis_seed_snapshots ADD COLUMN source_type VARCHAR(40) NOT NULL DEFAULT 'LEGACY';
ALTER TABLE market_analysis_seed_snapshots ADD COLUMN portfolio_selection_id BIGINT;
ALTER TABLE market_analysis_seed_snapshots ADD COLUMN portfolio_concept_id VARCHAR(64);
ALTER TABLE market_analysis_seed_snapshots ADD COLUMN legal_report_id VARCHAR(64);
ALTER TABLE market_analysis_seed_snapshots ADD COLUMN stale_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE market_analysis_seed_snapshots
    ADD CONSTRAINT fk_market_seed_snapshot_selection FOREIGN KEY (selection_id, project_id)
        REFERENCES concept_selections(id, project_id) ON DELETE NO ACTION,
    ADD CONSTRAINT fk_market_seed_snapshot_concept FOREIGN KEY (concept_id, project_id)
        REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    ADD CONSTRAINT fk_market_seed_portfolio_selection FOREIGN KEY (portfolio_selection_id, project_id)
        REFERENCES concept_portfolio_selections(id, project_id) ON DELETE NO ACTION,
    ADD CONSTRAINT fk_market_seed_portfolio_concept FOREIGN KEY (portfolio_concept_id, project_id)
        REFERENCES concept_portfolio_concepts(id, project_id) ON DELETE NO ACTION,
    ADD CONSTRAINT fk_market_seed_legal_report FOREIGN KEY (legal_report_id, project_id)
        REFERENCES concept_legal_regulatory_reports(id, project_id) ON DELETE NO ACTION,
    ADD CONSTRAINT ck_market_seed_source_type CHECK (source_type IN ('LEGACY', 'CONCEPT_PORTFOLIO_V2')),
    ADD CONSTRAINT ck_market_seed_source_authority CHECK (
        (source_type = 'LEGACY' AND selection_id IS NOT NULL AND concept_id IS NOT NULL
            AND portfolio_selection_id IS NULL AND portfolio_concept_id IS NULL AND legal_report_id IS NULL)
        OR
        (source_type = 'CONCEPT_PORTFOLIO_V2' AND selection_id IS NULL AND concept_id IS NULL
            AND portfolio_selection_id IS NOT NULL AND portfolio_concept_id IS NOT NULL
            AND legal_report_id IS NOT NULL));
CREATE UNIQUE INDEX uk_market_seed_portfolio_selection
    ON market_analysis_seed_snapshots(portfolio_selection_id)
    WHERE source_type = 'CONCEPT_PORTFOLIO_V2' AND deleted_at IS NULL;
