CREATE TABLE planning_change_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id VARCHAR(100) NOT NULL,
    project_id BIGINT NOT NULL,
    decision VARCHAR(30) NOT NULL,
    applied_value_json TEXT,
    decided_by_user_id BIGINT NOT NULL,
    decided_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_planning_decision_proposal UNIQUE (proposal_id),
    CONSTRAINT fk_planning_decision_proposal FOREIGN KEY (proposal_id) REFERENCES planning_change_proposals(id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_decision_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_decision_user FOREIGN KEY (decided_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_planning_decision CHECK (decision IN ('ADOPT','PARTIALLY_ADOPT','REJECT')),
    CONSTRAINT ck_planning_decision_value CHECK ((decision='PARTIALLY_ADOPT' AND applied_value_json IS NOT NULL) OR (decision<>'PARTIALLY_ADOPT' AND applied_value_json IS NULL))
);

INSERT INTO planning_change_decisions (
    proposal_id, project_id, decision, applied_value_json, decided_by_user_id, decided_at,
    created_at, updated_at, version
)
SELECT p.id, p.project_id, p.decision_status, p.modified_after_json, h.requested_by_user_id,
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
FROM planning_change_proposals p
JOIN module_results mr ON mr.module_run_id = p.module_run_id
JOIN module_runs r ON r.id = mr.module_run_id
JOIN module_handoffs h ON h.id = r.handoff_id
WHERE p.decision_status <> 'PENDING' AND p.deleted_at IS NULL;

CREATE TABLE planning_snapshots (
    id VARCHAR(64) PRIMARY KEY, project_id BIGINT NOT NULL, source_selection_snapshot_id VARCHAR(64) NOT NULL,
    sequence_number INTEGER NOT NULL, parent_snapshot_id VARCHAR(64), display_label VARCHAR(300) NOT NULL,
    planning_json TEXT NOT NULL, snapshot_hash VARCHAR(71) NOT NULL, created_by_user_id BIGINT NOT NULL,
    snapshotted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_planning_snapshot_project_sequence UNIQUE(project_id,sequence_number),
    CONSTRAINT fk_planning_snapshot_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_snapshot_source FOREIGN KEY(source_selection_snapshot_id,project_id) REFERENCES selected_concept_snapshots(id,project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_snapshot_parent FOREIGN KEY(parent_snapshot_id) REFERENCES planning_snapshots(id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_snapshot_user FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_planning_snapshot_hash CHECK(snapshot_hash LIKE 'sha256:%')
);

CREATE TABLE finalized_planning_snapshots (
    id VARCHAR(64) PRIMARY KEY, project_id BIGINT NOT NULL, planning_snapshot_id VARCHAR(64) NOT NULL,
    source_selection_snapshot_id VARCHAR(64) NOT NULL, sequence_number INTEGER NOT NULL, parent_snapshot_id VARCHAR(64),
    display_label VARCHAR(300) NOT NULL, snapshot_json TEXT NOT NULL, snapshot_hash VARCHAR(71) NOT NULL,
    finalized_by_user_id BIGINT NOT NULL, finalized_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_finalized_planning_project_sequence UNIQUE(project_id,sequence_number),
    CONSTRAINT uk_finalized_planning_source UNIQUE(project_id,source_selection_snapshot_id),
    CONSTRAINT fk_finalized_planning_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_finalized_planning_revision FOREIGN KEY(planning_snapshot_id) REFERENCES planning_snapshots(id) ON DELETE NO ACTION,
    CONSTRAINT fk_finalized_planning_source FOREIGN KEY(source_selection_snapshot_id,project_id) REFERENCES selected_concept_snapshots(id,project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_finalized_planning_parent FOREIGN KEY(parent_snapshot_id) REFERENCES finalized_planning_snapshots(id) ON DELETE NO ACTION,
    CONSTRAINT fk_finalized_planning_user FOREIGN KEY(finalized_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_finalized_planning_hash CHECK(snapshot_hash LIKE 'sha256:%')
);

ALTER TABLE module_handoffs DROP CONSTRAINT fk_module_handoff_snapshot;
ALTER TABLE module_runs DROP CONSTRAINT fk_module_run_snapshot;
ALTER TABLE module_handoffs DROP CONSTRAINT ck_module_handoff_module;
ALTER TABLE module_handoffs ADD CONSTRAINT ck_module_handoff_module CHECK (module IN ('MARKET_ANALYSIS','BUSINESS_FINANCIAL','PERSONA_RESPONSE_TEST'));
ALTER TABLE module_runs DROP CONSTRAINT ck_module_run_module;
ALTER TABLE module_runs ADD CONSTRAINT ck_module_run_module CHECK (module IN ('MARKET_ANALYSIS','BUSINESS_FINANCIAL','PERSONA_RESPONSE_TEST'));

CREATE INDEX idx_planning_decision_project ON planning_change_decisions(project_id,decided_at);
CREATE INDEX idx_planning_snapshot_project ON planning_snapshots(project_id,sequence_number DESC);
CREATE INDEX idx_finalized_planning_project ON finalized_planning_snapshots(project_id,sequence_number DESC);
