-- Feedback loop: plan versioning, review cycles, revision requests, confirmed facts, publications

-- structured_plans: plan-only versioning (REVISION_ACCEPT / ANSWER / USER_EDIT)
ALTER TABLE structured_plans ADD COLUMN parent_plan_id BIGINT;
ALTER TABLE structured_plans ADD COLUMN origin VARCHAR(30) DEFAULT 'UPLOAD' NOT NULL;
ALTER TABLE structured_plans ADD CONSTRAINT fk_plan_parent
    FOREIGN KEY (parent_plan_id) REFERENCES structured_plans(id);
-- derived versions share the root plan's document version; UPLOAD-uniqueness moves to the service layer
ALTER TABLE structured_plans DROP CONSTRAINT uk_plan_source_document_version;
CREATE INDEX idx_plan_source_doc_version ON structured_plans(source_document_version_id);

-- analysis_jobs: requested review mode (FULL | INCREMENTAL)
ALTER TABLE analysis_jobs ADD COLUMN requested_mode VARCHAR(20);

-- review_cycles: state machine DRAFT -> REVIEWING -> NEEDS_ACTION -> CONVERGED -> PUBLISHED
CREATE TABLE review_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    current_plan_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    latest_review_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_review_cycle_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_review_cycle_current_plan FOREIGN KEY (current_plan_id) REFERENCES structured_plans(id)
);
CREATE INDEX idx_review_cycle_project ON review_cycles(project_id, status);

-- legal_reviews: review-run metadata
ALTER TABLE legal_reviews ADD COLUMN review_cycle_id BIGINT;
ALTER TABLE legal_reviews ADD COLUMN parent_review_id BIGINT;
ALTER TABLE legal_reviews ADD COLUMN mode VARCHAR(20) DEFAULT 'FULL' NOT NULL;
ALTER TABLE legal_reviews ADD COLUMN changed_sections_json TEXT;
ALTER TABLE legal_reviews ADD COLUMN rerun_categories_json TEXT;
ALTER TABLE legal_reviews ADD COLUMN carried_categories_json TEXT;
ALTER TABLE legal_reviews ADD CONSTRAINT fk_legal_review_cycle
    FOREIGN KEY (review_cycle_id) REFERENCES review_cycles(id);
ALTER TABLE legal_reviews ADD CONSTRAINT fk_legal_review_parent
    FOREIGN KEY (parent_review_id) REFERENCES legal_reviews(id);

-- legal_findings: carried-forward marker for INCREMENTAL reruns
ALTER TABLE legal_findings ADD COLUMN carried BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE legal_findings ADD COLUMN carried_from_finding_id BIGINT;
ALTER TABLE legal_findings ADD CONSTRAINT fk_finding_carried_from
    FOREIGN KEY (carried_from_finding_id) REFERENCES legal_findings(id);

-- legal_review_questions: answer lifecycle + carry + category links
ALTER TABLE legal_review_questions ADD COLUMN answer_text TEXT;
ALTER TABLE legal_review_questions ADD COLUMN answered_at TIMESTAMP;
ALTER TABLE legal_review_questions ADD COLUMN confirmed_fact_id BIGINT;
ALTER TABLE legal_review_questions ADD COLUMN carried_from_question_id BIGINT;
ALTER TABLE legal_review_questions ADD COLUMN categories_json TEXT;
ALTER TABLE legal_review_questions ADD COLUMN resolved_in_version INTEGER;
ALTER TABLE legal_review_questions ADD CONSTRAINT fk_question_carried_from
    FOREIGN KEY (carried_from_question_id) REFERENCES legal_review_questions(id);

-- confirmed_facts: structured answers, never inserted into plan body text
CREATE TABLE confirmed_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_cycle_id BIGINT NOT NULL,
    created_in_plan_id BIGINT NOT NULL,
    fact_key VARCHAR(200) NOT NULL,
    fact_value TEXT NOT NULL,
    source VARCHAR(500),
    answered_at TIMESTAMP NOT NULL,
    from_question_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_confirmed_fact_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles(id),
    CONSTRAINT fk_confirmed_fact_plan FOREIGN KEY (created_in_plan_id) REFERENCES structured_plans(id),
    CONSTRAINT fk_confirmed_fact_question FOREIGN KEY (from_question_id) REFERENCES legal_review_questions(id)
);
CREATE INDEX idx_confirmed_fact_cycle ON confirmed_facts(review_cycle_id);

-- revision_requests: rows are never deleted; RESOLVED is recorded via resolved_in_version
CREATE TABLE revision_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_cycle_id BIGINT NOT NULL,
    raised_in_review_id BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL,
    anchor_section_code VARCHAR(80) NOT NULL,
    anchor_quote TEXT NOT NULL,
    rationale TEXT,
    status VARCHAR(20) NOT NULL,
    accepted_suggestion_id BIGINT,
    resolved_in_version INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_revision_request_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles(id),
    CONSTRAINT fk_revision_request_review FOREIGN KEY (raised_in_review_id) REFERENCES legal_reviews(id)
);
CREATE INDEX idx_revision_request_cycle ON revision_requests(review_cycle_id, status);

CREATE TABLE revision_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_request_id BIGINT NOT NULL,
    label VARCHAR(10) NOT NULL,
    new_text TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_revision_suggestion_request FOREIGN KEY (revision_request_id) REFERENCES revision_requests(id)
);
CREATE INDEX idx_revision_suggestion_request ON revision_suggestions(revision_request_id);

-- publications: snapshot preserved as of the published plan version
CREATE TABLE publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    review_cycle_id BIGINT NOT NULL,
    final_plan_id BIGINT NOT NULL,
    final_version_number INTEGER NOT NULL,
    snapshot_json TEXT NOT NULL,
    published_by_user_id BIGINT NOT NULL,
    published_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_publication_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_publication_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles(id),
    CONSTRAINT fk_publication_plan FOREIGN KEY (final_plan_id) REFERENCES structured_plans(id),
    CONSTRAINT fk_publication_user FOREIGN KEY (published_by_user_id) REFERENCES users(id),
    CONSTRAINT uk_publication_cycle UNIQUE (review_cycle_id)
);
CREATE INDEX idx_publication_project ON publications(project_id);
