CREATE TABLE market_research_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    kind VARCHAR(10) NOT NULL,
    source_run_id BIGINT,
    source_market_version_id BIGINT,
    source_market_seed_snapshot_id VARCHAR(64),
    source_portfolio_selection_id BIGINT,
    source_selection_revision INTEGER,
    source_bm_plan_revision INTEGER,
    task_run_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_research_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_run_source FOREIGN KEY (source_run_id) REFERENCES market_research_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_run_seed FOREIGN KEY (source_market_seed_snapshot_id) REFERENCES market_analysis_seed_snapshots(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_run_selection FOREIGN KEY (source_portfolio_selection_id) REFERENCES concept_portfolio_selections(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_research_run_task UNIQUE (task_run_id),
    CONSTRAINT ck_market_research_run_kind CHECK (kind IN ('FULL', 'BM')),
    CONSTRAINT ck_market_research_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_market_research_run_selection_revision CHECK (source_selection_revision IS NULL OR source_selection_revision >= 0),
    CONSTRAINT ck_market_research_run_plan_revision CHECK (source_bm_plan_revision IS NULL OR source_bm_plan_revision >= 0)
);
CREATE INDEX idx_market_research_runs_project ON market_research_runs(project_id, kind, created_at DESC);

CREATE TABLE market_research_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    kind VARCHAR(10) NOT NULL,
    version_number INTEGER NOT NULL,
    result_json TEXT NOT NULL,
    filled_count INTEGER,
    partial_count INTEGER,
    missing_count INTEGER,
    decision VARCHAR(20),
    confidence VARCHAR(10),
    evidence_count INTEGER NOT NULL,
    caveat_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_research_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_research_version_run FOREIGN KEY (source_run_id) REFERENCES market_research_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_research_version_run UNIQUE (source_run_id),
    CONSTRAINT uk_market_research_version_number UNIQUE (project_id, kind, version_number),
    CONSTRAINT ck_market_research_version_kind CHECK (kind IN ('FULL', 'BM'))
);
ALTER TABLE market_research_runs ADD CONSTRAINT fk_market_research_run_source_version
    FOREIGN KEY (source_market_version_id) REFERENCES market_research_versions(id) ON DELETE NO ACTION;
CREATE INDEX idx_market_research_versions_project ON market_research_versions(project_id, kind, version_number DESC);
