-- Flyway baseline cutover: 2026-08-04
-- PostgreSQL is the schema contract. This baseline intentionally contains no
-- legacy-row backfill, development seed, credential, or demonstration data.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(254) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    organization_name VARCHAR(120), department_name VARCHAR(120), job_title VARCHAR(120),
    role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP, locked_at TIMESTAMP, locked_reason VARCHAR(500),
    disabled_at TIMESTAMP, disabled_reason VARCHAR(500),
    last_login_at TIMESTAMP, password_changed_at TIMESTAMP, email_verified_at TIMESTAMP,
    role_updated_at TIMESTAMP, role_updated_by BIGINT,
    security_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uk_users_username ON users(username);
CREATE INDEX idx_users_role_status ON users(role, status);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL, description TEXT, industry_category VARCHAR(100),
    stage VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE NO ACTION
);
CREATE INDEX idx_project_owner_status ON projects(owner_id, status);

CREATE TABLE product_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL, category VARCHAR(100), target_price DECIMAL(19,2),
    target_audience VARCHAR(255), summary TEXT, currency VARCHAR(3), features_json TEXT,
    value_proposition TEXT, active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION
);

CREATE TABLE stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, storage_type VARCHAR(30) NOT NULL,
    storage_key VARCHAR(500) NOT NULL UNIQUE, original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL, extension VARCHAR(20) NOT NULL,
    mime_type VARCHAR(150) NOT NULL, size_bytes BIGINT NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL, status VARCHAR(30) NOT NULL,
    encrypted BOOLEAN NOT NULL, retention_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE project_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    document_type VARCHAR(30) NOT NULL, current_version INTEGER NOT NULL, status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_document_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION
);
CREATE UNIQUE INDEX uk_active_business_plan_per_project
    ON project_documents(project_id, document_type)
    WHERE deleted_at IS NULL AND status = 'ACTIVE' AND document_type = 'BUSINESS_PLAN';

CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, stored_file_id BIGINT NOT NULL UNIQUE,
    parse_status VARCHAR(30) NOT NULL, uploaded_by BIGINT NOT NULL, uploaded_at TIMESTAMP NOT NULL,
    parser_name VARCHAR(100), parser_version VARCHAR(100), parse_metadata_json TEXT,
    parser_artifact_stored_file_id BIGINT, parser_artifact_status VARCHAR(30),
    parser_block_count INTEGER, parser_artifact_checksum_sha256 VARCHAR(64),
    parser_artifact_schema_version VARCHAR(100), parsed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_document_version UNIQUE(document_id, version_number),
    CONSTRAINT uk_document_version_parser_artifact UNIQUE(parser_artifact_stored_file_id),
    CONSTRAINT fk_version_document FOREIGN KEY (document_id) REFERENCES project_documents(id) ON DELETE NO ACTION,
    CONSTRAINT fk_version_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION,
    CONSTRAINT fk_version_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_document_version_parser_artifact FOREIGN KEY (parser_artifact_stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION,
    CONSTRAINT ck_document_version_parser_checksum CHECK (
        parser_artifact_checksum_sha256 IS NULL OR parser_artifact_checksum_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_version_parser_block_count CHECK (
        (parser_artifact_stored_file_id IS NULL AND parser_block_count IS NULL)
        OR (parser_artifact_stored_file_id IS NOT NULL AND parser_block_count > 0)),
    CONSTRAINT ck_document_version_parser_metadata CHECK (
        (parser_artifact_stored_file_id IS NULL AND parser_artifact_checksum_sha256 IS NULL
            AND parser_artifact_schema_version IS NULL AND parsed_at IS NULL)
        OR (parser_artifact_stored_file_id IS NOT NULL AND parser_artifact_checksum_sha256 IS NOT NULL
            AND parser_artifact_schema_version IS NOT NULL AND parsed_at IS NOT NULL))
);
CREATE INDEX idx_document_version_parser_status ON document_versions(parser_artifact_status, parsed_at);

CREATE TABLE structured_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    source_document_version_id BIGINT NOT NULL, version_number INTEGER NOT NULL, status VARCHAR(30) NOT NULL,
    completion_rate INTEGER NOT NULL CHECK (completion_rate BETWEEN 0 AND 100), raw_extracted_json TEXT,
    confirmed_by_user BOOLEAN NOT NULL, confirmed_at TIMESTAMP, confirmed_by_user_id BIGINT,
    provider VARCHAR(100), model_name VARCHAR(100), prompt_version VARCHAR(100),
    parser_name VARCHAR(100), parser_version VARCHAR(100), raw_result_hash VARCHAR(64),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_plan_version UNIQUE(project_id, version_number),
    CONSTRAINT uk_plan_source_document_version UNIQUE(source_document_version_id),
    CONSTRAINT fk_plan_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_plan_source FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_plan_confirmed_by_user FOREIGN KEY (confirmed_by_user_id) REFERENCES users(id) ON DELETE NO ACTION
);
CREATE INDEX idx_plan_confirmed_by_user ON structured_plans(confirmed_by_user_id);

CREATE TABLE structured_plan_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, structured_plan_id BIGINT NOT NULL,
    section_type VARCHAR(40) NOT NULL, title VARCHAR(150) NOT NULL, content_json TEXT, source_text TEXT,
    confidence DECIMAL(5,4), section_code VARCHAR(80), item_status VARCHAR(20), reason TEXT,
    evidence_json TEXT, source_block_references_json TEXT, display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_section_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT uk_plan_section_code UNIQUE(structured_plan_id, section_code),
    CONSTRAINT ck_structured_section_code CHECK (section_code IS NULL OR section_code IN (
        'BUSINESS_OVERVIEW','MARKET_SIZE','TARGET_CUSTOMER','COMPETITIVE_ANALYSIS',
        'PRODUCT_SERVICE','BUSINESS_MODEL','COST_PROFITABILITY','SALES_GOALS_FINANCIAL_PROJECTIONS',
        'TECHNOLOGY_PRODUCTION','LEGAL_PERMITS','SCHEDULE_RISK','EVIDENCE_LIST')),
    CONSTRAINT ck_structured_item_status CHECK (item_status IS NULL OR item_status IN (
        'PRESENT','MISSING','PARTIAL','INVALID','UNKNOWN'))
);

CREATE TABLE missing_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, structured_plan_id BIGINT NOT NULL,
    field_code VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, required BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL, user_value_json TEXT, section_code VARCHAR(80), reason TEXT, priority VARCHAR(20),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_missing_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT ck_missing_field_section_code CHECK (section_code IS NULL OR section_code IN (
        'BUSINESS_OVERVIEW','MARKET_SIZE','TARGET_CUSTOMER','COMPETITIVE_ANALYSIS',
        'PRODUCT_SERVICE','BUSINESS_MODEL','COST_PROFITABILITY','SALES_GOALS_FINANCIAL_PROJECTIONS',
        'TECHNOLOGY_PRODUCTION','LEGAL_PERMITS','SCHEDULE_RISK','EVIDENCE_LIST'))
);

CREATE TABLE analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    job_type VARCHAR(40) NOT NULL, status VARCHAR(30) NOT NULL, progress INTEGER NOT NULL DEFAULT 0,
    current_step VARCHAR(200), request_json TEXT, external_request_id VARCHAR(100),
    result_reference_type VARCHAR(50), result_reference_id BIGINT, error_code VARCHAR(100),
    error_message VARCHAR(500), retry_count INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0, next_attempt_at TIMESTAMP, claimed_at TIMESTAMP,
    claimed_by VARCHAR(100), heartbeat_at TIMESTAMP, last_error_code VARCHAR(100), retryable BOOLEAN,
    claim_token VARCHAR(64), idempotency_key VARCHAR(100), request_fingerprint VARCHAR(64),
    source_document_version_id BIGINT, source_structured_plan_id BIGINT, source_legal_review_id BIGINT,
    source_feasibility_assessment_id BIGINT, rerun_of_job_id BIGINT,
    started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_job_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT uk_job_idempotency UNIQUE(project_id, job_type, idempotency_key),
    CONSTRAINT fk_job_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_job_source_document_version FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_job_source_structured_plan FOREIGN KEY (source_structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT fk_job_rerun_of FOREIGN KEY (rerun_of_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION
);
CREATE INDEX idx_job_project_type_status ON analysis_jobs(project_id, job_type, status);
CREATE INDEX idx_job_source_document_version ON analysis_jobs(source_document_version_id);
CREATE INDEX idx_job_source_structured_plan ON analysis_jobs(source_structured_plan_id);
CREATE INDEX idx_job_claim_candidates ON analysis_jobs(job_type, status, next_attempt_at);
CREATE INDEX idx_job_rerun_of ON analysis_jobs(rerun_of_job_id);

CREATE TABLE legal_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE, status VARCHAR(30) NOT NULL, decision VARCHAR(30),
    risk_level VARCHAR(20), summary TEXT, model_version VARCHAR(100), knowledge_base_version VARCHAR(100),
    raw_result_json TEXT, started_at TIMESTAMP, completed_at TIMESTAMP,
    structured_plan_id BIGINT, source_document_version_id BIGINT, version_number INTEGER,
    disclaimer TEXT, provider VARCHAR(100), model_name VARCHAR(100), prompt_version VARCHAR(100),
    prompt_hash VARCHAR(64), raw_result_hash VARCHAR(64), input_snapshot_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_legal_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_review_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_review_source_version FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_review_plan_prompt UNIQUE(structured_plan_id, prompt_version)
);
CREATE INDEX idx_legal_review_project_created ON legal_reviews(project_id, created_at);

ALTER TABLE analysis_jobs ADD CONSTRAINT fk_job_source_legal_review
    FOREIGN KEY (source_legal_review_id) REFERENCES legal_reviews(id) ON DELETE NO ACTION;
CREATE INDEX idx_job_source_legal_review ON analysis_jobs(source_legal_review_id);

CREATE TABLE legal_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legal_review_id BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL, severity VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL,
    description TEXT, legal_basis TEXT, source_name VARCHAR(255), source_url TEXT, recommendation TEXT,
    display_order INTEGER, applicability VARCHAR(40), rationale TEXT, evidence_json TEXT,
    source_section_codes_json TEXT, requires_professional_review BOOLEAN, confidence DECIMAL(5,4),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_finding_review FOREIGN KEY (legal_review_id) REFERENCES legal_reviews(id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_finding_review_category UNIQUE(legal_review_id, category)
);

CREATE TABLE feasibility_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE, analysis_type VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL,
    score DECIMAL(5,2), decision VARCHAR(30), summary TEXT, input_snapshot_json TEXT, raw_result_json TEXT,
    model_version VARCHAR(100), started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_feasibility_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION
);

CREATE TABLE analysis_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feasibility_analysis_id BIGINT NOT NULL,
    metric_key VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, numeric_value DECIMAL(19,4),
    text_value TEXT, unit VARCHAR(50), display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_metric_analysis FOREIGN KEY (feasibility_analysis_id) REFERENCES feasibility_analyses(id) ON DELETE NO ACTION
);
CREATE TABLE analysis_evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feasibility_analysis_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL, title VARCHAR(250) NOT NULL, source_url TEXT, summary TEXT, retrieved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_evidence_analysis FOREIGN KEY (feasibility_analysis_id) REFERENCES feasibility_analyses(id) ON DELETE NO ACTION
);
CREATE TABLE analysis_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feasibility_analysis_id BIGINT NOT NULL,
    priority VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT, display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_recommendation_analysis FOREIGN KEY (feasibility_analysis_id) REFERENCES feasibility_analyses(id) ON DELETE NO ACTION
);

CREATE TABLE financial_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    analysis_job_id BIGINT UNIQUE, status VARCHAR(30) NOT NULL, currency VARCHAR(3) NOT NULL,
    analysis_period_months INTEGER NOT NULL, expected_revenue DECIMAL(19,2), expected_cost DECIMAL(19,2),
    break_even_point_months INTEGER, roi DECIMAL(10,4), npv DECIMAL(19,2), irr DECIMAL(10,4),
    summary TEXT, assumptions_json TEXT NOT NULL, result_json TEXT,
    created_by_user_id BIGINT, feasibility_assessment_id BIGINT, structured_plan_id BIGINT,
    source_document_version_id BIGINT, version_number INTEGER NOT NULL, title VARCHAR(200) NOT NULL,
    scenarios_json TEXT NOT NULL DEFAULT '[]', summary_json TEXT,
    source_snapshot_json TEXT NOT NULL DEFAULT '{}', input_hash VARCHAR(64), result_hash VARCHAR(64),
    journey_idea_version_id BIGINT, journey_concept_version_id BIGINT,
    unit_price DECIMAL(19,2), monthly_customers INTEGER, variable_cost_per_customer DECIMAL(19,2),
    monthly_fixed_cost DECIMAL(19,2), initial_investment DECIMAL(19,2), monthly_revenue DECIMAL(19,2),
    monthly_variable_cost DECIMAL(19,2), monthly_total_cost DECIMAL(19,2),
    monthly_operating_profit DECIMAL(19,2), break_even_customers INTEGER, payback_months DECIMAL(10,2),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_financial_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_source_document FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id) ON DELETE NO ACTION
);
CREATE INDEX idx_financial_project_deleted ON financial_analyses(project_id, deleted_at);
CREATE INDEX idx_financial_project_status_updated ON financial_analyses(project_id, status, updated_at);

-- Preserved MVP simulation, report, persona, and marketing schema.

CREATE TABLE persona_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, segment_code VARCHAR(100) NOT NULL UNIQUE,
    segment_name VARCHAR(150) NOT NULL, age_group VARCHAR(50), gender VARCHAR(20), sample_count INTEGER,
    weighted_share DECIMAL(7,4), traits_json TEXT, source_dataset VARCHAR(200),
    cluster_model_version VARCHAR(100), active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE persona_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, segment_id BIGINT, owner_id BIGINT,
    name VARCHAR(100) NOT NULL, age INTEGER, gender VARCHAR(10), occupation VARCHAR(50),
    background TEXT, traits_json TEXT, is_system BOOLEAN NOT NULL, active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_segment FOREIGN KEY (segment_id) REFERENCES persona_segments(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE TABLE persona_prompt_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, persona_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, system_prompt TEXT NOT NULL, generation_model VARCHAR(100), parameters_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_persona_prompt_version UNIQUE(persona_id, version_number),
    CONSTRAINT fk_prompt_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id) ON DELETE NO ACTION
);

CREATE TABLE project_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL, persona_id BIGINT NOT NULL,
    weight DECIMAL(7,4), active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_project_persona UNIQUE(project_id, persona_id),
    CONSTRAINT fk_project_persona_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_project_persona_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id) ON DELETE NO ACTION
);

CREATE TABLE simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL, simulation_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL,
    total_rounds INTEGER, current_round INTEGER, progress INTEGER, configuration_json TEXT,
    started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_simulation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION
);

CREATE TABLE simulation_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL, persona_id BIGINT NOT NULL,
    role VARCHAR(50), weight DECIMAL(7,4), profile_snapshot_json TEXT, prompt_snapshot TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_simulation_persona UNIQUE(simulation_id, persona_id),
    CONSTRAINT fk_sim_persona_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_sim_persona_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id) ON DELETE NO ACTION
);

CREATE TABLE simulation_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL, status VARCHAR(30) NOT NULL, summary TEXT, started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_simulation_round UNIQUE(simulation_id, round_number),
    CONSTRAINT fk_round_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION
);

CREATE TABLE fgi_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL, question_type VARCHAR(20) NOT NULL, evaluation_axis VARCHAR(100),
    question_text TEXT NOT NULL, options_json TEXT, required BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_question_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION
);

CREATE TABLE fgi_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL, persona_id BIGINT NOT NULL, answer_text TEXT, score DECIMAL(7,2),
    sentiment VARCHAR(20), keywords_json TEXT, follow_up BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_response_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_response_question FOREIGN KEY (question_id) REFERENCES fgi_questions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_response_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id) ON DELETE NO ACTION
);

CREATE TABLE discussion_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    persona_id BIGINT NOT NULL, round_id BIGINT, round_number INTEGER, turn_number INTEGER,
    content TEXT NOT NULL, room_group VARCHAR(50), sentiment VARCHAR(20), keywords_json TEXT, reply_to_log_id BIGINT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_log_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_log_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id) ON DELETE NO ACTION,
    CONSTRAINT fk_log_round FOREIGN KEY (round_id) REFERENCES simulation_rounds(id) ON DELETE NO ACTION,
    CONSTRAINT fk_log_reply FOREIGN KEY (reply_to_log_id) REFERENCES discussion_logs(id) ON DELETE NO ACTION
);

CREATE TABLE simulation_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    insight_type VARCHAR(100) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT,
    supporting_data_json TEXT, display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_insight_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION
);

CREATE TABLE prediction_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    metric_key VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, metric_value DECIMAL(19,4),
    unit VARCHAR(50), segment_breakdown_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_prediction_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id) ON DELETE NO ACTION
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    report_type VARCHAR(40) NOT NULL, title VARCHAR(150) NOT NULL, status VARCHAR(20) NOT NULL,
    current_version INTEGER NOT NULL, summary TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION
);

CREATE TABLE report_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, content_json TEXT NOT NULL, generation_model VARCHAR(100), source_snapshot_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_report_version UNIQUE(report_id, version_number),
    CONSTRAINT fk_report_version_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE NO ACTION
);

CREATE TABLE report_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_version_id BIGINT NOT NULL,
    source_type VARCHAR(50) NOT NULL, source_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_source_version FOREIGN KEY (report_version_id) REFERENCES report_versions(id) ON DELETE NO ACTION
);

CREATE TABLE report_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_version_id BIGINT NOT NULL,
    stored_file_id BIGINT NOT NULL UNIQUE, file_format VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_file_version FOREIGN KEY (report_version_id) REFERENCES report_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_report_file_stored FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);

CREATE TABLE marketing_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    product_service_id BIGINT, material_type VARCHAR(40) NOT NULL, title VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL, target_persona_segment_id BIGINT, prompt TEXT, content_json TEXT,
    representative_file_id BIGINT UNIQUE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_material_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_material_product FOREIGN KEY (product_service_id) REFERENCES product_services(id) ON DELETE NO ACTION,
    CONSTRAINT fk_material_segment FOREIGN KEY (target_persona_segment_id) REFERENCES persona_segments(id) ON DELETE NO ACTION,
    CONSTRAINT fk_material_file FOREIGN KEY (representative_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);

CREATE TABLE marketing_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, marketing_material_id BIGINT NOT NULL,
    stored_file_id BIGINT NOT NULL UNIQUE, asset_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_asset_material FOREIGN KEY (marketing_material_id) REFERENCES marketing_materials(id) ON DELETE NO ACTION,
    CONSTRAINT fk_asset_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);

CREATE TABLE marketing_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, marketing_material_id BIGINT NOT NULL,
    variant_number INTEGER NOT NULL, content_json TEXT NOT NULL, stored_file_id BIGINT UNIQUE, score DECIMAL(5,2),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_marketing_variant UNIQUE(marketing_material_id, variant_number),
    CONSTRAINT fk_variant_material FOREIGN KEY (marketing_material_id) REFERENCES marketing_materials(id) ON DELETE NO ACTION,
    CONSTRAINT fk_variant_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);


CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    token_jti VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_refresh_token_jti UNIQUE (token_jti),
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE INDEX idx_refresh_token_user_revoked
    ON refresh_tokens(user_id, revoked_at);

CREATE INDEX idx_refresh_token_expires
    ON refresh_tokens(expires_at);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    project_id BIGINT,
    event_type VARCHAR(60) NOT NULL,
    aggregate_type VARCHAR(60),
    aggregate_id BIGINT,
    request_id VARCHAR(100),
    metadata_json TEXT,
    result VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    actor_role VARCHAR(20), error_code VARCHAR(100), ip_address VARCHAR(64),
    user_agent VARCHAR(500), target_label VARCHAR(255), reason VARCHAR(500),
    before_json TEXT, after_json TEXT,
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_audit_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION
);

CREATE INDEX idx_audit_actor_occurred
    ON audit_events(actor_user_id, occurred_at);

CREATE INDEX idx_audit_project_occurred
    ON audit_events(project_id, occurred_at);

CREATE INDEX idx_audit_event_occurred
    ON audit_events(event_type, occurred_at);


CREATE INDEX idx_audit_result_occurred ON audit_events(result, occurred_at);
CREATE INDEX idx_audit_request_id ON audit_events(request_id);

CREATE TABLE legal_review_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_review_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    question TEXT NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_legal_question_review FOREIGN KEY (legal_review_id) REFERENCES legal_reviews(id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_question_order UNIQUE (legal_review_id, display_order)
);
CREATE INDEX idx_legal_question_review ON legal_review_questions(legal_review_id);


CREATE TABLE feasibility_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE,
    structured_plan_id BIGINT NOT NULL,
    legal_review_id BIGINT NOT NULL,
    source_document_version_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    verdict VARCHAR(40) NOT NULL,
    overall_score INTEGER,
    confidence VARCHAR(20) NOT NULL,
    summary TEXT NOT NULL,
    key_strengths_json TEXT NOT NULL,
    key_risks_json TEXT NOT NULL,
    validation_tasks_summary_json TEXT NOT NULL,
    disclaimer TEXT NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(100) NOT NULL,
    catalog_version VARCHAR(100) NOT NULL,
    prompt_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    result_hash VARCHAR(64) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_assessment_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_feasibility_assessment_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_feasibility_assessment_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT fk_feasibility_assessment_legal FOREIGN KEY (legal_review_id) REFERENCES legal_reviews(id) ON DELETE NO ACTION,
    CONSTRAINT fk_feasibility_assessment_source FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id) ON DELETE NO ACTION,
    CONSTRAINT ck_feasibility_overall_score CHECK (overall_score IS NULL OR overall_score BETWEEN 0 AND 100),
    CONSTRAINT uk_feasibility_assessment_input
        UNIQUE (structured_plan_id, legal_review_id, prompt_version, catalog_version)
);
CREATE INDEX idx_feasibility_assessment_project_created
    ON feasibility_assessments(project_id, created_at);

CREATE TABLE feasibility_dimension_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feasibility_assessment_id BIGINT NOT NULL,
    dimension_code VARCHAR(60) NOT NULL,
    display_order INTEGER NOT NULL,
    score INTEGER,
    confidence VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    finding TEXT NOT NULL,
    rationale TEXT NOT NULL,
    strengths_json TEXT NOT NULL,
    risks_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    source_section_codes_json TEXT NOT NULL,
    legal_finding_ids_json TEXT NOT NULL,
    recommended_actions_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_dimension_assessment
        FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id) ON DELETE NO ACTION,
    CONSTRAINT ck_feasibility_dimension_score CHECK (score IS NULL OR score BETWEEN 0 AND 100),
    CONSTRAINT uk_feasibility_dimension UNIQUE (feasibility_assessment_id, dimension_code)
);
CREATE INDEX idx_feasibility_dimension_assessment
    ON feasibility_dimension_results(feasibility_assessment_id);

CREATE TABLE feasibility_validation_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feasibility_assessment_id BIGINT NOT NULL,
    task_code VARCHAR(100) NOT NULL,
    dimension_code VARCHAR(60) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    reason TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    validation_method TEXT NOT NULL,
    expected_evidence TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_task_assessment
        FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id) ON DELETE NO ACTION,
    CONSTRAINT uk_feasibility_task UNIQUE (feasibility_assessment_id, task_code)
);
CREATE INDEX idx_feasibility_task_assessment
    ON feasibility_validation_tasks(feasibility_assessment_id);


ALTER TABLE analysis_jobs ADD CONSTRAINT fk_job_source_feasibility_assessment
    FOREIGN KEY (source_feasibility_assessment_id) REFERENCES feasibility_assessments(id) ON DELETE NO ACTION;
CREATE INDEX idx_job_source_feasibility_assessment ON analysis_jobs(source_feasibility_assessment_id);

CREATE TABLE baseline_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_code VARCHAR(100) NOT NULL,
    cluster_id VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    short_name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    age_group VARCHAR(40) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    sample_size INTEGER,
    weighted_share DECIMAL(7,4),
    data_source VARCHAR(200) NOT NULL,
    data_version VARCHAR(100) NOT NULL,
    catalog_version VARCHAR(100) NOT NULL,
    key_traits_json TEXT NOT NULL,
    consumption_traits_json TEXT NOT NULL,
    technology_traits_json TEXT NOT NULL,
    channel_traits_json TEXT NOT NULL,
    subscription_traits_json TEXT NOT NULL,
    financial_traits_json TEXT NOT NULL,
    ai_usage_traits_json TEXT NOT NULL,
    demographic_summary_json TEXT NOT NULL,
    evidence_metrics_json TEXT NOT NULL,
    limitations_json TEXT NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_baseline_persona_code_catalog UNIQUE (persona_code, catalog_version),
    CONSTRAINT uk_baseline_persona_cluster_catalog UNIQUE (cluster_id, catalog_version),
    CONSTRAINT ck_baseline_persona_share
        CHECK (weighted_share IS NULL OR weighted_share BETWEEN 0 AND 1),
    CONSTRAINT ck_baseline_persona_sample
        CHECK (sample_size IS NULL OR sample_size >= 0)
);
CREATE INDEX idx_baseline_persona_catalog_order
    ON baseline_personas(catalog_version, display_order);

CREATE TABLE persona_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE,
    structured_plan_id BIGINT NOT NULL,
    feasibility_assessment_id BIGINT NOT NULL,
    source_document_version_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    primary_persona_code VARCHAR(100),
    secondary_persona_code VARCHAR(100),
    confidence VARCHAR(20) NOT NULL,
    summary TEXT NOT NULL,
    disclaimer TEXT NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(100) NOT NULL,
    catalog_version VARCHAR(100) NOT NULL,
    prompt_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    result_hash VARCHAR(64) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_recommendation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_recommendation_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_recommendation_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_recommendation_feasibility
        FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_recommendation_source
        FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_persona_recommendation_input
        UNIQUE (structured_plan_id, feasibility_assessment_id, prompt_version, catalog_version)
);
CREATE INDEX idx_persona_recommendation_project_created
    ON persona_recommendations(project_id, created_at);

CREATE TABLE persona_recommendation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    baseline_persona_id BIGINT NOT NULL,
    recommendation_rank INTEGER NOT NULL,
    recommendation_level VARCHAR(40) NOT NULL,
    fit_score INTEGER,
    confidence VARCHAR(20) NOT NULL,
    match_reasons_json TEXT NOT NULL,
    mismatch_risks_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    verification_questions_json TEXT NOT NULL,
    interpretation TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_item_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_item_baseline
        FOREIGN KEY (baseline_persona_id) REFERENCES baseline_personas(id) ON DELETE NO ACTION,
    CONSTRAINT uk_persona_item_persona UNIQUE (recommendation_id, baseline_persona_id),
    CONSTRAINT uk_persona_item_rank UNIQUE (recommendation_id, recommendation_rank),
    CONSTRAINT ck_persona_item_rank CHECK (recommendation_rank > 0),
    CONSTRAINT ck_persona_item_fit CHECK (fit_score IS NULL OR fit_score BETWEEN 0 AND 100)
);
CREATE INDEX idx_persona_item_recommendation
    ON persona_recommendation_items(recommendation_id);

CREATE TABLE customer_hypotheses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    persona_code VARCHAR(100) NOT NULL,
    hypothesis_type VARCHAR(40) NOT NULL,
    statement TEXT NOT NULL,
    rationale TEXT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_reference VARCHAR(200),
    confidence VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    validation_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_customer_hypothesis_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id) ON DELETE NO ACTION
);
CREATE INDEX idx_customer_hypothesis_recommendation
    ON customer_hypotheses(recommendation_id);

CREATE TABLE customer_validation_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    persona_code VARCHAR(100) NOT NULL,
    method VARCHAR(40) NOT NULL,
    objective TEXT NOT NULL,
    target_participant_description TEXT NOT NULL,
    suggested_sample_size INTEGER,
    recruitment_channel TEXT NOT NULL,
    success_criteria_json TEXT NOT NULL,
    expected_evidence_json TEXT NOT NULL,
    interview_questions_json TEXT NOT NULL,
    survey_questions_json TEXT NOT NULL,
    linked_feasibility_task_ids_json TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    disclaimer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_customer_validation_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id) ON DELETE NO ACTION,
    CONSTRAINT uk_customer_validation_persona UNIQUE (recommendation_id, persona_code),
    CONSTRAINT ck_customer_validation_sample
        CHECK (suggested_sample_size IS NULL OR suggested_sample_size > 0)
);
CREATE INDEX idx_customer_validation_recommendation
    ON customer_validation_plans(recommendation_id);

CREATE TABLE persona_validation_task_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    feasibility_validation_task_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_task_link_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_task_link_feasibility_task
        FOREIGN KEY (feasibility_validation_task_id) REFERENCES feasibility_validation_tasks(id) ON DELETE NO ACTION,
    CONSTRAINT uk_persona_task_link
        UNIQUE (recommendation_id, feasibility_validation_task_id)
);
CREATE INDEX idx_persona_task_link_recommendation
    ON persona_validation_task_links(recommendation_id);


CREATE TABLE service_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(500) NOT NULL,
    updated_by BIGINT,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_service_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE NO ACTION
);


CREATE TABLE admin_action_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    purpose VARCHAR(60) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    security_version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_admin_action_token_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE NO ACTION
);
CREATE INDEX idx_admin_action_token_actor ON admin_action_tokens(actor_user_id, purpose, expires_at);


CREATE TABLE cluster_persona_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baseline_persona_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL,
    updated_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cluster_persona_policy_persona UNIQUE (baseline_persona_id),
    CONSTRAINT fk_cluster_persona_policy_persona
        FOREIGN KEY (baseline_persona_id) REFERENCES baseline_personas(id) ON DELETE NO ACTION,
    CONSTRAINT fk_cluster_persona_policy_updater
        FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_cluster_persona_policy_order CHECK (display_order > 0)
);

CREATE INDEX idx_cluster_persona_policy_visible_order
    ON cluster_persona_policies(enabled, display_order);

CREATE TABLE project_persona_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    baseline_persona_id BIGINT NOT NULL,
    selected_by_user_id BIGINT NOT NULL,
    selected_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_project_persona_selection_project UNIQUE (project_id),
    CONSTRAINT fk_project_persona_selection_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_project_persona_selection_persona
        FOREIGN KEY (baseline_persona_id) REFERENCES baseline_personas(id) ON DELETE NO ACTION,
    CONSTRAINT fk_project_persona_selection_user
        FOREIGN KEY (selected_by_user_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE INDEX idx_project_persona_selection_persona
    ON project_persona_selections(baseline_persona_id);


CREATE TABLE persona_panel_interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    purpose VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    persona_ids_json TEXT NOT NULL,
    questions_json TEXT NOT NULL,
    answers_json TEXT NOT NULL,
    summary_json TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_panel_interview_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_panel_interview_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE INDEX idx_panel_interview_project_updated
    ON persona_panel_interviews(project_id, deleted_at, updated_at);

CREATE TABLE market_response_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    panel_interview_id BIGINT,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    persona_ids_json TEXT NOT NULL,
    message_variants_json TEXT NOT NULL,
    price_context VARCHAR(300),
    primary_channel VARCHAR(80),
    result_json TEXT NOT NULL,
    summary_json TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_market_response_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_response_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_response_panel FOREIGN KEY (panel_interview_id) REFERENCES persona_panel_interviews(id) ON DELETE NO ACTION
);

CREATE INDEX idx_market_response_project_updated
    ON market_response_predictions(project_id, deleted_at, updated_at);


CREATE TABLE marketing_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    purpose VARCHAR(40) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    format VARCHAR(40) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    selected_persona_id BIGINT,
    recommended_persona_code VARCHAR(100),
    source_snapshot_json TEXT NOT NULL,
    current_version INTEGER NOT NULL,
    panel_interview_id BIGINT, market_response_id BIGINT,
    source_snapshot_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_marketing_content_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_content_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_content_persona
        FOREIGN KEY (selected_persona_id) REFERENCES baseline_personas(id) ON DELETE NO ACTION,
    CONSTRAINT ck_marketing_content_width CHECK (width BETWEEN 320 AND 4096),
    CONSTRAINT ck_marketing_content_height CHECK (height BETWEEN 320 AND 4096),
    CONSTRAINT ck_marketing_content_current_version CHECK (current_version > 0),
    CONSTRAINT fk_marketing_content_panel FOREIGN KEY (panel_interview_id) REFERENCES persona_panel_interviews(id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_content_market FOREIGN KEY (market_response_id) REFERENCES market_response_predictions(id) ON DELETE NO ACTION
);

CREATE INDEX idx_marketing_content_project_updated
    ON marketing_contents(project_id, deleted_at, updated_at);

CREATE TABLE marketing_content_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketing_content_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    headline VARCHAR(160) NOT NULL,
    subheadline VARCHAR(240),
    body_copy TEXT,
    call_to_action VARCHAR(80),
    supporting_text VARCHAR(240),
    visual_style VARCHAR(30) NOT NULL,
    color_theme VARCHAR(30) NOT NULL,
    layout_template VARCHAR(30) NOT NULL,
    background_type VARCHAR(30) NOT NULL,
    background_value VARCHAR(500),
    accent_color VARCHAR(20),
    text_color VARCHAR(20),
    text_alignment VARCHAR(20) NOT NULL,
    headline_size INTEGER NOT NULL,
    show_cta BOOLEAN NOT NULL,
    show_persona_tag BOOLEAN NOT NULL,
    content_json TEXT NOT NULL,
    source_snapshot_version INTEGER NOT NULL DEFAULT 1,
    source_changed BOOLEAN NOT NULL DEFAULT FALSE,
    copy_changed BOOLEAN NOT NULL DEFAULT TRUE,
    analysis_job_id BIGINT,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_marketing_content_version
        UNIQUE (marketing_content_id, version_number),
    CONSTRAINT fk_marketing_content_version_content
        FOREIGN KEY (marketing_content_id) REFERENCES marketing_contents(id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_content_version_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_content_version_job
        FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_marketing_content_version_job UNIQUE (analysis_job_id)
);

CREATE INDEX idx_marketing_content_version_content
    ON marketing_content_versions(marketing_content_id, version_number);


CREATE INDEX idx_marketing_content_validation_sources
    ON marketing_contents(project_id, panel_interview_id, market_response_id);

ALTER TABLE financial_analyses ADD CONSTRAINT fk_financial_feasibility
    FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id) ON DELETE NO ACTION;
CREATE INDEX idx_financial_feasibility ON financial_analyses(feasibility_assessment_id);

CREATE TABLE ai_task_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_job_id BIGINT NOT NULL UNIQUE,
    task_type VARCHAR(40) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    request_id VARCHAR(100) NOT NULL,
    result_json TEXT NOT NULL,
    handler VARCHAR(100) NOT NULL,
    handler_version VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_ai_task_result_job
        FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION
);


CREATE TABLE ai_task_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL,
    ai_task_result_id BIGINT,
    stored_file_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_task_artifact_job_role
        UNIQUE (analysis_job_id, role),
    CONSTRAINT uk_ai_task_artifact_file UNIQUE (stored_file_id),
    CONSTRAINT fk_ai_task_artifact_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_ai_task_artifact_job
        FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_ai_task_artifact_result
        FOREIGN KEY (ai_task_result_id) REFERENCES ai_task_results(id) ON DELETE NO ACTION,
    CONSTRAINT fk_ai_task_artifact_file
        FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);

CREATE INDEX idx_ai_task_artifact_project
    ON ai_task_artifacts(project_id);
CREATE INDEX idx_ai_task_artifact_job
    ON ai_task_artifacts(analysis_job_id);
CREATE INDEX idx_ai_task_artifact_result
    ON ai_task_artifacts(ai_task_result_id);


CREATE TABLE task_runs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_type VARCHAR(50) NOT NULL,
    subject_type VARCHAR(80) NOT NULL,
    subject_id VARCHAR(64) NOT NULL,
    state VARCHAR(20) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    canonical_input_hash VARCHAR(71) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    idempotency_scope VARCHAR(200) NOT NULL,
    last_retry_idempotency_key VARCHAR(128),
    correlation_id VARCHAR(128) NOT NULL,
    contract_version VARCHAR(20) NOT NULL,
    task_schema_version VARCHAR(20) NOT NULL,
    locale VARCHAR(20) NOT NULL,
    retryable BOOLEAN NOT NULL,
    cancel_requested BOOLEAN NOT NULL,
    max_attempts INTEGER NOT NULL,
    attempt_count INTEGER NOT NULL,
    current_attempt_id VARCHAR(64),
    final_result_id VARCHAR(64),
    last_error_code VARCHAR(80),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_task_runs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT uk_task_runs_idempotency UNIQUE (project_id, idempotency_scope, idempotency_key),
    CONSTRAINT ck_task_runs_attempts CHECK (max_attempts > 0 AND attempt_count >= 0 AND attempt_count <= max_attempts),
    CONSTRAINT ck_task_runs_input_hash CHECK (canonical_input_hash LIKE 'sha256:%')
);

CREATE TABLE task_attempts (
    id VARCHAR(64) PRIMARY KEY,
    task_run_id VARCHAR(64) NOT NULL,
    attempt_number INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    claim_token VARCHAR(64),
    claimed_by VARCHAR(128),
    claimed_at TIMESTAMP,
    lease_expires_at TIMESTAMP,
    heartbeat_at TIMESTAMP,
    deadline_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    normalized_error_code VARCHAR(80),
    normalized_error_reason VARCHAR(100),
    retryable BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_task_attempts_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_task_attempt_number UNIQUE (task_run_id, attempt_number),
    CONSTRAINT uk_task_attempt_claim_token UNIQUE (claim_token),
    CONSTRAINT ck_task_attempt_number CHECK (attempt_number > 0)
);

CREATE TABLE task_results (
    id VARCHAR(64) PRIMARY KEY,
    task_run_id VARCHAR(64) NOT NULL,
    task_attempt_id VARCHAR(64) NOT NULL,
    validation_state VARCHAR(20) NOT NULL,
    contract_version VARCHAR(20) NOT NULL,
    task_schema_version VARCHAR(20) NOT NULL,
    result_schema_version VARCHAR(20) NOT NULL,
    result_json TEXT NOT NULL,
    result_hash VARCHAR(71) NOT NULL,
    rejection_code VARCHAR(100),
    received_at TIMESTAMP NOT NULL,
    validated_at TIMESTAMP,
    adopted_at TIMESTAMP,
    rejected_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_task_results_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_task_results_attempt FOREIGN KEY (task_attempt_id) REFERENCES task_attempts(id) ON DELETE NO ACTION,
    CONSTRAINT ck_task_results_hash CHECK (result_hash LIKE 'sha256:%')
);

ALTER TABLE task_runs ADD CONSTRAINT fk_task_runs_current_attempt
    FOREIGN KEY (current_attempt_id) REFERENCES task_attempts(id) ON DELETE NO ACTION;
ALTER TABLE task_runs ADD CONSTRAINT fk_task_runs_final_result
    FOREIGN KEY (final_result_id) REFERENCES task_results(id) ON DELETE NO ACTION;

CREATE INDEX idx_task_runs_claim ON task_runs(state, created_at);
CREATE INDEX idx_task_runs_project_history ON task_runs(project_id, created_at, id);
CREATE INDEX idx_task_runs_subject ON task_runs(project_id, subject_type, subject_id);
CREATE INDEX idx_task_runs_active_conflict ON task_runs(project_id, task_type, subject_type, subject_id, canonical_input_hash, state);
CREATE INDEX idx_task_attempts_lease ON task_attempts(state, lease_expires_at);
CREATE INDEX idx_task_results_run ON task_results(task_run_id, created_at);
CREATE INDEX idx_task_results_attempt ON task_results(task_attempt_id, validation_state);


CREATE TABLE idea_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_type VARCHAR(10) NOT NULL,
    title VARCHAR(200),
    original_text TEXT NOT NULL,
    original_file_reference VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_sources_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT ck_idea_sources_type CHECK (source_type IN ('TEXT', 'FILE'))
);

CREATE TABLE idea_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    normalized_description TEXT NOT NULL,
    facts_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    constraints_json TEXT NOT NULL,
    open_questions_json TEXT NOT NULL,
    readiness VARCHAR(30) NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_versions_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_versions_source FOREIGN KEY (source_id) REFERENCES idea_sources(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_versions_number UNIQUE (project_id, version_number),
    CONSTRAINT ck_idea_versions_readiness CHECK (readiness IN ('UNDER_SPECIFIED', 'APPROPRIATE', 'OVER_SPECIFIED'))
);

CREATE TABLE idea_interpretation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL,
    result_json TEXT,
    error VARCHAR(100),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_interpretation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_interpretation_source FOREIGN KEY (source_id) REFERENCES idea_sources(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_interpretation_task_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE legal_review_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    idea_version_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL,
    legal_status VARCHAR(40),
    result_json TEXT,
    source_verified BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_review_runs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_review_runs_idea_version FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_review_runs_task_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT ck_legal_review_source_unverified CHECK (source_verified = FALSE)
);

CREATE INDEX idx_idea_sources_current ON idea_sources(project_id, created_at DESC, id DESC);
CREATE INDEX idx_idea_versions_current ON idea_versions(project_id, version_number DESC);
CREATE INDEX idx_idea_interpretation_current ON idea_interpretation_runs(project_id, created_at DESC, id DESC);
CREATE INDEX idx_legal_review_current ON legal_review_runs(project_id, created_at DESC, id DESC);


CREATE TABLE concept_generation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_generation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_generation_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_generation_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, generation_run_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concepts_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concepts_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concepts_generation FOREIGN KEY (generation_run_id) REFERENCES concept_generation_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_concepts_generation_order UNIQUE (generation_run_id, display_order)
);

CREATE TABLE concept_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, name VARCHAR(200) NOT NULL, one_line_summary TEXT NOT NULL,
    target_customer TEXT NOT NULL, problem TEXT NOT NULL, solution TEXT NOT NULL,
    value_proposition TEXT NOT NULL, revenue_model TEXT NOT NULL,
    key_features_json TEXT NOT NULL, differentiators_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL, risks_json TEXT NOT NULL,
    eligibility_batch_id BIGINT, eligibility_status VARCHAR(20) NOT NULL DEFAULT 'LEGACY',
    target_segment_json TEXT NOT NULL DEFAULT '{}', positioning TEXT NOT NULL DEFAULT '',
    pricing_json TEXT NOT NULL DEFAULT '{}', channels_json TEXT NOT NULL DEFAULT '[]',
    operating_model_json TEXT NOT NULL DEFAULT '{}', new_business_activities_json TEXT NOT NULL DEFAULT '[]',
    origin_trace_json TEXT NOT NULL DEFAULT '[]', legal_trace_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_versions_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_versions_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_versions_concept FOREIGN KEY (concept_id) REFERENCES concepts(id) ON DELETE NO ACTION,
    CONSTRAINT uk_concept_versions_number UNIQUE (concept_id, version_number),
    CONSTRAINT ck_concept_version_eligibility CHECK (eligibility_status IN ('LEGACY','ELIGIBLE'))
);

CREATE TABLE quick_assessment_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_quick_runs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_quick_runs_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_quick_runs_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE quick_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, run_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL,
    market_score INTEGER NOT NULL, customer_value_score INTEGER NOT NULL, feasibility_score INTEGER NOT NULL,
    differentiation_score INTEGER NOT NULL, revenue_potential_score INTEGER NOT NULL, legal_risk_score INTEGER NOT NULL,
    overall_score DECIMAL(5,2) NOT NULL, summary TEXT NOT NULL, strengths_json TEXT NOT NULL, weaknesses_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_quick_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_quick_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_quick_run FOREIGN KEY (run_id) REFERENCES quick_assessment_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_quick_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_quick_run_concept UNIQUE (run_id, concept_version_id)
);

CREATE TABLE shortlist_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL,
    selected_concept_version_ids_json TEXT NOT NULL, reason TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_shortlist_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_shortlist_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION
);

CREATE TABLE detailed_analysis_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_detailed_runs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_detailed_runs_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_detailed_runs_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE detailed_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, run_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL,
    market_analysis TEXT NOT NULL, customer_analysis TEXT NOT NULL, business_model_analysis TEXT NOT NULL,
    operation_analysis TEXT NOT NULL, risk_analysis TEXT NOT NULL, recommendation TEXT NOT NULL,
    assumptions_json TEXT NOT NULL, research_needs_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_detailed_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_detailed_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_detailed_run FOREIGN KEY (run_id) REFERENCES detailed_analysis_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_detailed_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_detailed_run_concept UNIQUE (run_id, concept_version_id)
);

CREATE TABLE concept_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_selection_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_selection_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_selection_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION
);

CREATE INDEX idx_concept_generation_current ON concept_generation_runs(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_concepts_current ON concepts(project_id, idea_version_id, display_order);
CREATE INDEX idx_quick_current ON quick_assessment_runs(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_shortlist_current ON shortlist_decisions(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_detailed_current ON detailed_analysis_runs(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_selection_current ON concept_selections(project_id, idea_version_id, created_at DESC, id DESC);


ALTER TABLE financial_analyses ADD CONSTRAINT fk_financial_journey_idea
    FOREIGN KEY (journey_idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION;
ALTER TABLE financial_analyses ADD CONSTRAINT fk_financial_journey_concept
    FOREIGN KEY (journey_concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION;
CREATE INDEX idx_financial_journey_concept ON financial_analyses(journey_concept_version_id)
    WHERE journey_concept_version_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE persona_studies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL,
    generation_task_run_id VARCHAR(64), state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100),
    synthetic_notice VARCHAR(300) NOT NULL, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_study_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_study_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_study_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_study_task FOREIGN KEY (generation_task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE persona_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL, selected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_card_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_card_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_card_study FOREIGN KEY (study_id) REFERENCES persona_studies(id) ON DELETE NO ACTION,
    CONSTRAINT uk_persona_card_order UNIQUE (study_id, display_order)
);

CREATE TABLE persona_card_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, persona_card_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, name VARCHAR(200) NOT NULL, short_label VARCHAR(200) NOT NULL,
    role_and_context_json TEXT NOT NULL, problem_and_needs_json TEXT NOT NULL,
    behavior_and_decision_json TEXT NOT NULL, interview_focus_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_version_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_version_card FOREIGN KEY (persona_card_id) REFERENCES persona_cards(id) ON DELETE NO ACTION,
    CONSTRAINT uk_persona_version_number UNIQUE (persona_card_id, version_number)
);

CREATE TABLE persona_interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL,
    persona_card_version_id BIGINT NOT NULL, task_run_id VARCHAR(64), state VARCHAR(20) NOT NULL,
    result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_interview_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_interview_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_interview_study FOREIGN KEY (study_id) REFERENCES persona_studies(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_interview_card_version FOREIGN KEY (persona_card_version_id) REFERENCES persona_card_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_persona_interview_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE persona_interview_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, interview_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL, category VARCHAR(40) NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_interview_message_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_interview_message_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_interview_message_interview FOREIGN KEY (interview_id) REFERENCES persona_interviews(id) ON DELETE NO ACTION,
    CONSTRAINT uk_interview_message_sequence UNIQUE (interview_id, sequence_number)
);

CREATE TABLE interview_synthesis_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL,
    task_run_id VARCHAR(64), interview_ids_json TEXT NOT NULL, state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_synthesis_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_synthesis_run_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_synthesis_run_study FOREIGN KEY (study_id) REFERENCES persona_studies(id) ON DELETE NO ACTION,
    CONSTRAINT fk_synthesis_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);

CREATE TABLE interview_syntheses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL, run_id BIGINT NOT NULL,
    common_themes_json TEXT NOT NULL, conflicting_views_json TEXT NOT NULL, critical_needs_json TEXT NOT NULL,
    decision_barriers_json TEXT NOT NULL, implications_json TEXT NOT NULL, research_needs_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_synthesis_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_synthesis_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_synthesis_study FOREIGN KEY (study_id) REFERENCES persona_studies(id) ON DELETE NO ACTION,
    CONSTRAINT fk_synthesis_run FOREIGN KEY (run_id) REFERENCES interview_synthesis_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_synthesis_run UNIQUE (run_id)
);

CREATE INDEX idx_persona_study_current ON persona_studies(project_id, concept_version_id, created_at DESC, id DESC);
CREATE INDEX idx_persona_cards_study ON persona_cards(study_id, display_order);
CREATE INDEX idx_persona_interviews_study ON persona_interviews(study_id, persona_card_version_id, created_at DESC, id DESC);
CREATE INDEX idx_synthesis_current ON interview_synthesis_runs(study_id, created_at DESC, id DESC);


CREATE TABLE marketing_workspaces (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, synthesis_id BIGINT NOT NULL,
 state VARCHAR(20) NOT NULL, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_workspace_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_workspace_idea FOREIGN KEY(idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_workspace_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_workspace_synthesis FOREIGN KEY(synthesis_id) REFERENCES interview_syntheses(id) ON DELETE NO ACTION
);
CREATE TABLE marketing_generation_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, task_run_id VARCHAR(64),
 state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_run_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_run_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_run_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_run_task FOREIGN KEY(task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);
CREATE TABLE journey_marketing_assets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, generation_run_id BIGINT NOT NULL,
 asset_type VARCHAR(30) NOT NULL, display_order INTEGER NOT NULL, selected BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_asset_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_asset_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_asset_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_asset_run FOREIGN KEY(generation_run_id) REFERENCES marketing_generation_runs(id) ON DELETE NO ACTION,
 CONSTRAINT ck_marketing_asset_type CHECK(asset_type IN('POSITIONING','CORE_MESSAGE','SLOGAN','SOCIAL_COPY','LANDING_HERO','EMAIL_COPY','CHANNEL_PLAN'))
);
CREATE TABLE marketing_asset_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, asset_id BIGINT NOT NULL,
 version_number INTEGER NOT NULL, title VARCHAR(300) NOT NULL, content_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_version_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_version_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_version_asset FOREIGN KEY(asset_id) REFERENCES journey_marketing_assets(id) ON DELETE NO ACTION,
 CONSTRAINT uk_marketing_version_number UNIQUE(asset_id,version_number)
);
CREATE TABLE marketing_comparison_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, task_run_id VARCHAR(64),
 asset_version_ids_json TEXT NOT NULL, state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_comparison_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_comparison_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_comparison_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_comparison_task FOREIGN KEY(task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);
CREATE TABLE marketing_comparisons (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, run_id BIGINT NOT NULL,
 result_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_comparison_result_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_comparison_result_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_comparison_result_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id) ON DELETE NO ACTION,
 CONSTRAINT fk_marketing_comparison_result_run FOREIGN KEY(run_id) REFERENCES marketing_comparison_runs(id) ON DELETE NO ACTION,
 CONSTRAINT uk_marketing_comparison_result_run UNIQUE(run_id)
);
CREATE TABLE final_reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL,
 task_run_id VARCHAR(64), source_reference_json TEXT NOT NULL, state VARCHAR(20) NOT NULL, ai_decision VARCHAR(30), user_decision VARCHAR(30),
 user_decision_reasons_json TEXT, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_final_report_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_final_report_idea FOREIGN KEY(idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_final_report_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_final_report_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id) ON DELETE NO ACTION,
 CONSTRAINT fk_final_report_task FOREIGN KEY(task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION
);
CREATE TABLE final_report_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, report_id BIGINT NOT NULL,
 version_number INTEGER NOT NULL, content_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_final_report_version_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE NO ACTION,
 CONSTRAINT fk_final_report_version_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id) ON DELETE NO ACTION,
 CONSTRAINT fk_final_report_version_report FOREIGN KEY(report_id) REFERENCES final_reports(id) ON DELETE NO ACTION,
 CONSTRAINT uk_final_report_version_number UNIQUE(report_id,version_number)
);
CREATE INDEX idx_marketing_workspace_current ON marketing_workspaces(project_id,concept_version_id,created_at DESC,id DESC);
CREATE INDEX idx_marketing_assets_workspace ON journey_marketing_assets(workspace_id,asset_type,display_order);
CREATE INDEX idx_marketing_comparison_current ON marketing_comparison_runs(workspace_id,created_at DESC,id DESC);
CREATE INDEX idx_final_report_current ON final_reports(project_id,concept_version_id,created_at DESC,id DESC);


CREATE TABLE idea_origin_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    source_idea_version_id BIGINT NOT NULL,
    based_on_origin_version_id BIGINT,
    version_number INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    snapshot_json TEXT NOT NULL,
    confirmed_values_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    missing_fields_json TEXT NOT NULL,
    metadata_json TEXT NOT NULL,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_origin_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_origin_source FOREIGN KEY (source_id) REFERENCES idea_sources(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_origin_source_version FOREIGN KEY (source_idea_version_id) REFERENCES idea_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_origin_based_on FOREIGN KEY (based_on_origin_version_id) REFERENCES idea_origin_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_origin_version UNIQUE (project_id, version_number),
    CONSTRAINT ck_idea_origin_state CHECK (state IN ('DRAFT', 'CONFIRMED'))
);

CREATE TABLE idea_clarification_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    origin_draft_version_id BIGINT NOT NULL,
    target_field VARCHAR(160) NOT NULL,
    requirement VARCHAR(40) NOT NULL,
    question TEXT NOT NULL,
    reason TEXT NOT NULL,
    answer TEXT,
    answer_source VARCHAR(300),
    status VARCHAR(30) NOT NULL,
    answered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_clarification_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_clarification_origin FOREIGN KEY (origin_draft_version_id) REFERENCES idea_origin_versions(id) ON DELETE NO ACTION,
    CONSTRAINT ck_idea_clarification_requirement CHECK (requirement IN ('REQUIRED_FOR_IDEA_ORIGIN', 'REQUIRED_FOR_LEGAL_PRECHECK')),
    CONSTRAINT ck_idea_clarification_status CHECK (status IN ('MISSING', 'USER_CONFIRMED'))
);

CREATE INDEX idx_idea_origin_current ON idea_origin_versions(project_id, source_id, created_at DESC, id DESC);
CREATE INDEX idx_idea_origin_state ON idea_origin_versions(project_id, state, version_number DESC);
CREATE INDEX idx_idea_clarification_origin ON idea_clarification_questions(origin_draft_version_id, id);


CREATE TABLE legal_precheck_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    idea_origin_version_id BIGINT NOT NULL,
    task_run_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    registry_version VARCHAR(40) NOT NULL,
    prompt_version VARCHAR(40) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_precheck_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_precheck_run_origin FOREIGN KEY (idea_origin_version_id) REFERENCES idea_origin_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_precheck_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_precheck_run_task UNIQUE (task_run_id),
    CONSTRAINT ck_legal_precheck_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE TABLE legal_precheck_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    idea_origin_version_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    status VARCHAR(40) NOT NULL,
    source_status VARCHAR(30) NOT NULL,
    summary TEXT NOT NULL,
    findings_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    questions_json TEXT NOT NULL,
    revision_suggestions_json TEXT NOT NULL,
    concept_builder_allowed BOOLEAN NOT NULL,
    source_verified BOOLEAN NOT NULL,
    registry_version VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_precheck_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_precheck_version_origin FOREIGN KEY (idea_origin_version_id) REFERENCES idea_origin_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_precheck_version_run FOREIGN KEY (source_run_id) REFERENCES legal_precheck_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_precheck_version_run UNIQUE (source_run_id),
    CONSTRAINT uk_legal_precheck_version_number UNIQUE (project_id, version_number),
    CONSTRAINT ck_legal_precheck_status CHECK (status IN ('PASS', 'PASS_WITH_CONDITIONS', 'REVISION_REQUIRED', 'PROHIBITED', 'INSUFFICIENT_INFORMATION', 'EXPERT_REVIEW_REQUIRED')),
    CONSTRAINT ck_legal_precheck_source_status CHECK (source_status IN ('SOURCE_COMPLETE', 'SOURCE_PARTIAL', 'REGISTRY_GAP'))
);

CREATE TABLE legal_guardrail_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    legal_precheck_version_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    hard_constraints_json TEXT NOT NULL,
    prohibited_patterns_json TEXT NOT NULL,
    conditional_constraints_json TEXT NOT NULL,
    required_disclosures_json TEXT NOT NULL,
    required_operational_controls_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_guardrail_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_guardrail_precheck FOREIGN KEY (legal_precheck_version_id) REFERENCES legal_precheck_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_guardrail_run FOREIGN KEY (source_run_id) REFERENCES legal_precheck_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_guardrail_precheck UNIQUE (legal_precheck_version_id),
    CONSTRAINT uk_legal_guardrail_version UNIQUE (project_id, version_number)
);

CREATE INDEX idx_legal_precheck_run_current ON legal_precheck_runs(project_id, created_at DESC, id DESC);
CREATE INDEX idx_legal_precheck_version_current ON legal_precheck_versions(project_id, version_number DESC);
CREATE INDEX idx_legal_guardrail_current ON legal_guardrail_sets(project_id, version_number DESC);


CREATE TABLE concept_eligibility_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_origin_version_id BIGINT NOT NULL, legal_guardrail_set_id BIGINT NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL, prompt_version VARCHAR(40) NOT NULL, schema_version VARCHAR(20) NOT NULL,
    state VARCHAR(30) NOT NULL, current_round INTEGER NOT NULL, inspected_candidates INTEGER NOT NULL,
    eligible_candidates INTEGER NOT NULL, target_eligible_count INTEGER NOT NULL,
    max_replacement_rounds INTEGER NOT NULL, max_inspected_candidates INTEGER NOT NULL,
    needs_input_json TEXT NOT NULL, error_code VARCHAR(100), retryable BOOLEAN NOT NULL DEFAULT FALSE, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_batch_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_batch_origin FOREIGN KEY (idea_origin_version_id) REFERENCES idea_origin_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_batch_guardrail FOREIGN KEY (legal_guardrail_set_id) REFERENCES legal_guardrail_sets(id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_batch_state CHECK (state IN ('GENERATING','VALIDATING_ORIGIN','VALIDATING_LEGAL','COMPLETED','NEEDS_INPUT','FAILED'))
);

CREATE TABLE concept_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, generation_task_run_id VARCHAR(64) NOT NULL,
    round_number INTEGER NOT NULL, sequence_number INTEGER NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL, prompt_version VARCHAR(40) NOT NULL, schema_version VARCHAR(20) NOT NULL,
    fingerprint VARCHAR(71) NOT NULL, draft_json TEXT NOT NULL,
    origin_status VARCHAR(20) NOT NULL, origin_reasons_json TEXT NOT NULL,
    legal_status VARCHAR(20), legal_reasons_json TEXT NOT NULL, violated_structure_keys_json TEXT NOT NULL,
    eligibility_status VARCHAR(20) NOT NULL, user_comment TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_draft_batch FOREIGN KEY (batch_id) REFERENCES concept_eligibility_batches(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_draft_task FOREIGN KEY (generation_task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_concept_draft_batch_sequence UNIQUE (batch_id, sequence_number),
    CONSTRAINT ck_concept_draft_origin CHECK (origin_status IN ('PASS','FAIL_ORIGIN')),
    CONSTRAINT ck_concept_draft_legal CHECK (legal_status IS NULL OR legal_status IN ('PASS','FAIL_LEGAL')),
    CONSTRAINT ck_concept_draft_eligibility CHECK (eligibility_status IN ('PENDING','ELIGIBLE','REJECTED'))
);



ALTER TABLE concept_versions ADD CONSTRAINT fk_concept_version_batch
    FOREIGN KEY (eligibility_batch_id) REFERENCES concept_eligibility_batches(id) ON DELETE NO ACTION;
CREATE INDEX idx_concept_batch_current ON concept_eligibility_batches(project_id, created_at DESC, id DESC);
CREATE INDEX idx_concept_draft_batch ON concept_drafts(batch_id, sequence_number);
CREATE INDEX idx_concept_version_batch ON concept_versions(eligibility_batch_id, eligibility_status);
