-- R7A clean baseline for the new six-stage pipeline.
-- Destructive cutover: existing development databases/volumes must be reset.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(254) UNIQUE,
    organization_name VARCHAR(120),
    department_name VARCHAR(120),
    job_title VARCHAR(120),
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    last_login_at TIMESTAMP,
    password_changed_at TIMESTAMP,
    email_verified_at TIMESTAMP,
    locked_at TIMESTAMP,
    locked_reason VARCHAR(500),
    disabled_at TIMESTAMP,
    disabled_reason VARCHAR(500),
    role_updated_at TIMESTAMP,
    role_updated_by BIGINT,
    security_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    token_jti VARCHAR(100) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    industry_category VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE NO ACTION
);
CREATE INDEX idx_projects_owner_updated ON projects(owner_id, updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_type VARCHAR(30) NOT NULL,
    storage_key VARCHAR(500) NOT NULL UNIQUE,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    mime_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    encrypted BOOLEAN NOT NULL,
    retention_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    actor_role VARCHAR(20),
    project_id BIGINT,
    event_type VARCHAR(60) NOT NULL,
    aggregate_type VARCHAR(60),
    aggregate_id BIGINT,
    request_id VARCHAR(100),
    metadata_json TEXT,
    result VARCHAR(20) NOT NULL,
    error_code VARCHAR(100),
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    target_label VARCHAR(255),
    reason VARCHAR(500),
    before_json TEXT,
    after_json TEXT,
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_audit_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION
);
CREATE INDEX idx_audit_occurred ON audit_events(occurred_at DESC);

CREATE TABLE service_settings (
    setting_key VARCHAR(255) PRIMARY KEY,
    setting_value VARCHAR(255),
    updated_by BIGINT,
    updated_at TIMESTAMP,
    CONSTRAINT fk_service_setting_user FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE TABLE admin_action_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    purpose VARCHAR(60) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    security_version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_admin_action_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE TABLE task_runs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_type VARCHAR(50) NOT NULL,
    subject_type VARCHAR(80) NOT NULL,
    subject_id VARCHAR(64) NOT NULL,
    state VARCHAR(20) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    canonical_input_hash VARCHAR(71) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    idempotency_scope VARCHAR(200) NOT NULL,
    last_retry_idempotency_key VARCHAR(128),
    correlation_id VARCHAR(128) NOT NULL,
    contract_version VARCHAR(20) NOT NULL,
    task_schema_version VARCHAR(20) NOT NULL,
    locale VARCHAR(20) NOT NULL,
    retryable BOOLEAN NOT NULL,
    cancel_requested BOOLEAN NOT NULL,
    max_attempts INTEGER NOT NULL,
    attempt_count INTEGER NOT NULL,
    current_attempt_id VARCHAR(64),
    final_result_id VARCHAR(64),
    last_error_code VARCHAR(80),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    next_attempt_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_task_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT uk_task_runs_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_task_run_idempotency UNIQUE (project_id, idempotency_scope, idempotency_key)
);
CREATE INDEX idx_task_run_claim ON task_runs(state, next_attempt_at, created_at);

CREATE TABLE task_attempts (
    id VARCHAR(64) PRIMARY KEY,
    task_run_id VARCHAR(64) NOT NULL,
    attempt_number INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    claim_token VARCHAR(64),
    claimed_by VARCHAR(128),
    claimed_at TIMESTAMP,
    lease_expires_at TIMESTAMP,
    heartbeat_at TIMESTAMP,
    deadline_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    normalized_error_code VARCHAR(80),
    normalized_error_reason VARCHAR(100),
    retryable BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_task_attempt_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_task_attempt_sequence UNIQUE (task_run_id, attempt_number)
);

CREATE TABLE task_results (
    id VARCHAR(64) PRIMARY KEY,
    task_run_id VARCHAR(64) NOT NULL,
    task_attempt_id VARCHAR(64) NOT NULL,
    validation_state VARCHAR(20) NOT NULL,
    contract_version VARCHAR(20) NOT NULL,
    task_schema_version VARCHAR(20) NOT NULL,
    result_schema_version VARCHAR(20) NOT NULL,
    result_json TEXT NOT NULL,
    result_hash VARCHAR(71) NOT NULL,
    rejection_code VARCHAR(100),
    received_at TIMESTAMP NOT NULL,
    validated_at TIMESTAMP,
    adopted_at TIMESTAMP,
    rejected_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_task_result_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_task_result_attempt FOREIGN KEY (task_attempt_id) REFERENCES task_attempts(id) ON DELETE NO ACTION
);

CREATE TABLE job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    stage VARCHAR(50) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message_key VARCHAR(120) NOT NULL,
    message_params_json TEXT NOT NULL,
    technical_code VARCHAR(80),
    sequence BIGINT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_job_event_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_job_event_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_job_event_sequence UNIQUE (job_id, sequence)
);
CREATE INDEX idx_job_events_project_sequence ON job_events(project_id, id);

-- R2B canonical Idea Brief persistence. Confirmed rows are immutable snapshots;
-- later edits create a new draft row linked by parent_brief_id.

CREATE TABLE idea_briefs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    brief_sequence BIGINT NOT NULL,
    parent_brief_id VARCHAR(64),
    overview_text TEXT,
    active_task_run_id VARCHAR(64),
    confirmed_snapshot_id VARCHAR(64),
    snapshot_hash VARCHAR(71),
    user_facing_summary TEXT,
    contradictions_json TEXT NOT NULL DEFAULT '[]',
    missing_field_keys_json TEXT NOT NULL DEFAULT '[]',
    ai_readiness_status VARCHAR(30),
    readiness_score INTEGER NOT NULL DEFAULT 0,
    clarification_round INTEGER NOT NULL DEFAULT 0,
    assessment_input_hash VARCHAR(71),
    safety_decision VARCHAR(40),
    safety_categories_json TEXT NOT NULL DEFAULT '[]',
    safety_restrictions_json TEXT NOT NULL DEFAULT '[]',
    safety_user_facing_reason VARCHAR(1000),
    interpretation_json TEXT NOT NULL DEFAULT '{}',
    interpretation_confirmed_at TIMESTAMP,
    created_by_user_id BIGINT NOT NULL,
    last_command VARCHAR(30),
    last_idempotency_key VARCHAR(100),
    last_request_hash VARCHAR(71),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_brief_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_parent FOREIGN KEY (parent_brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_confirmed FOREIGN KEY (confirmed_snapshot_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_task FOREIGN KEY (active_task_run_id, project_id) REFERENCES task_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_brief_sequence UNIQUE (project_id, brief_sequence),
    CONSTRAINT ck_idea_brief_sequence_positive CHECK (brief_sequence > 0),
    CONSTRAINT ck_idea_brief_status CHECK (status IN ('DRAFT', 'DERIVING', 'NEEDS_INPUT', 'READY_FOR_REVIEW', 'SAFETY_BLOCKED', 'CONFIRMED', 'FAILED', 'STALE')),
    CONSTRAINT ck_idea_safety_decision CHECK (safety_decision IS NULL OR safety_decision IN ('ALLOW', 'ALLOW_WITH_RESTRICTIONS', 'BLOCK_OR_REFRAME')),
    CONSTRAINT ck_idea_brief_snapshot_hash CHECK (snapshot_hash IS NULL OR snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_idea_brief_request_hash CHECK (last_request_hash IS NULL OR last_request_hash LIKE 'sha256:%'),
    CONSTRAINT ck_idea_brief_assessment_hash CHECK (assessment_input_hash IS NULL OR assessment_input_hash LIKE 'sha256:%'),
    CONSTRAINT ck_idea_brief_confirmed_snapshot CHECK (
        (status = 'CONFIRMED' AND confirmed_snapshot_id = id AND snapshot_hash IS NOT NULL)
        OR status <> 'CONFIRMED'
    )
);

CREATE INDEX idx_idea_brief_project_current ON idea_briefs(project_id, brief_sequence DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_idea_brief_active_task ON idea_briefs(active_task_run_id) WHERE active_task_run_id IS NOT NULL;

CREATE TABLE idea_brief_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id VARCHAR(64) NOT NULL,
    field_key VARCHAR(80) NOT NULL,
    field_value TEXT,
    decision_state VARCHAR(20) NOT NULL,
    provenance VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_field_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_field_key UNIQUE (brief_id, field_key),
    CONSTRAINT ck_idea_field_decision CHECK (decision_state IN ('LOCKED', 'REVIEWABLE', 'OPEN', 'PREFERRED', 'ASSUMPTION')),
    CONSTRAINT ck_idea_field_provenance CHECK (provenance IN ('USER_INPUT', 'AI_DERIVED', 'USER_CONFIRMED', 'SOURCE_EXTRACTED', 'AI_PROPOSED', 'MISSING'))
);

CREATE INDEX idx_idea_field_brief ON idea_brief_fields(brief_id, id);

CREATE TABLE idea_questions (
    id VARCHAR(64) PRIMARY KEY,
    brief_id VARCHAR(64) NOT NULL,
    target_field_key VARCHAR(80),
    question_type VARCHAR(30) NOT NULL,
    prompt TEXT NOT NULL,
    options_json TEXT,
    display_order INTEGER NOT NULL,
    answered BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    clarification_round INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_question_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_question_order UNIQUE (brief_id, clarification_round, display_order),
    CONSTRAINT ck_idea_question_type CHECK (question_type IN ('FREE_TEXT', 'SINGLE_SELECT', 'MULTI_SELECT', 'UNDECIDED')),
    CONSTRAINT ck_idea_question_order CHECK (display_order >= 0)
);

CREATE INDEX idx_idea_question_brief ON idea_questions(brief_id, display_order);

CREATE TABLE idea_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id VARCHAR(64) NOT NULL,
    question_id VARCHAR(64) NOT NULL,
    answer_json TEXT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_answer_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_answer_question FOREIGN KEY (question_id) REFERENCES idea_questions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_answer_idempotency UNIQUE (brief_id, question_id, idempotency_key)
);

CREATE INDEX idx_idea_answer_brief ON idea_answers(brief_id, id);

CREATE TABLE idea_brief_attachments (
    brief_id VARCHAR(64) NOT NULL,
    stored_file_id BIGINT NOT NULL,
    PRIMARY KEY (brief_id, stored_file_id),
    CONSTRAINT fk_idea_attachment_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_attachment_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);

-- R3A five-slot Concept Factory and legal evidence persistence.
-- Composite foreign keys bind every child row to the same project as its immutable source snapshot.

ALTER TABLE idea_briefs ADD CONSTRAINT uk_idea_briefs_id_project UNIQUE (id, project_id);

CREATE TABLE legal_context_packs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_snapshot_id VARCHAR(64) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    canonical_context_json TEXT NOT NULL,
    provenance_json TEXT NOT NULL,
    registry_version VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_legal_context_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_legal_context_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_legal_context_snapshot FOREIGN KEY (source_snapshot_id, project_id) REFERENCES idea_briefs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_legal_context_hash CHECK (source_snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_legal_context_status CHECK (status IN ('PENDING', 'READY', 'FAILED', 'STALE'))
);

CREATE TABLE legal_evidence (
    id VARCHAR(64) PRIMARY KEY,
    context_pack_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    law_id VARCHAR(100),
    official_identifier VARCHAR(100) NOT NULL,
    law_name VARCHAR(500) NOT NULL,
    article_reference VARCHAR(200) NOT NULL,
    title VARCHAR(500) NOT NULL,
    official_source_uri VARCHAR(1000) NOT NULL,
    jurisdiction VARCHAR(10) NOT NULL,
    promulgation_date VARCHAR(20),
    effective_date VARCHAR(20),
    retrieved_at TIMESTAMP NOT NULL,
    content_hash VARCHAR(71) NOT NULL,
    bounded_provision_summary VARCHAR(1000) NOT NULL,
    query_key VARCHAR(71) NOT NULL,
    registry_version VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_legal_evidence_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_legal_evidence_context FOREIGN KEY (context_pack_id, project_id) REFERENCES legal_context_packs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT uk_legal_evidence_cache UNIQUE (context_pack_id, query_key, article_reference, content_hash),
    CONSTRAINT ck_legal_evidence_hash CHECK (content_hash LIKE 'sha256:%' AND query_key LIKE 'sha256:%'),
    CONSTRAINT ck_legal_evidence_source CHECK (source_type = 'OFFICIAL_LAW' AND jurisdiction = 'KR'),
    CONSTRAINT ck_legal_evidence_official_uri CHECK (official_source_uri LIKE 'https://www.law.go.kr/%' AND official_source_uri <> 'https://www.law.go.kr/')
);

CREATE TABLE concept_factory_runs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_idea_brief_snapshot_id VARCHAR(64) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    status VARCHAR(24) NOT NULL,
    replacement_rounds INTEGER NOT NULL DEFAULT 0,
    inspected_candidate_count INTEGER NOT NULL DEFAULT 0,
    provider_transient_retry_count INTEGER NOT NULL DEFAULT 0,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_run_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_concept_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_run_snapshot FOREIGN KEY (source_idea_brief_snapshot_id, project_id) REFERENCES idea_briefs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_run_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_run_hash CHECK (source_snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_concept_run_status CHECK (status IN ('QUEUED','GENERATING','VALIDATING','REPLACING','NEEDS_INPUT','COMPLETED','FAILED','STALE')),
    CONSTRAINT ck_concept_run_replacements CHECK (replacement_rounds BETWEEN 0 AND 2),
    CONSTRAINT ck_concept_run_inspected CHECK (inspected_candidate_count BETWEEN 0 AND 15),
    CONSTRAINT ck_concept_run_provider_retry CHECK (provider_transient_retry_count BETWEEN 0 AND 1)
);

CREATE INDEX idx_concept_run_project_current ON concept_factory_runs(project_id, created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE concept_slots (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    slot_number INTEGER NOT NULL,
    variation_focus VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    legal_redesign_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_slot_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_concept_slot_number UNIQUE (run_id, slot_number),
    CONSTRAINT uk_concept_slot_focus UNIQUE (run_id, variation_focus),
    CONSTRAINT fk_concept_slot_run FOREIGN KEY (run_id, project_id) REFERENCES concept_factory_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_slot_number CHECK (slot_number BETWEEN 1 AND 5),
    CONSTRAINT ck_concept_slot_focus CHECK (variation_focus IN ('CUSTOMER_EXPERIENCE','OPERATING_MODEL_AND_PARTNERS','REVENUE_AND_PRICING','CHANNEL_AND_SCALE','LOW_RISK_FAST_EXECUTION')),
    CONSTRAINT ck_concept_slot_status CHECK (status IN ('QUEUED','GENERATING','GENERATED','SCHEMA_INVALID','VALIDATING_ORIGIN','VALIDATING_DISTINCTNESS','VALIDATING_LEGAL','REDESIGNING','REPLACING','REVIEW_RETRY_PENDING','ELIGIBLE','REJECTED','NEEDS_INPUT','FAILED','STALE')),
    CONSTRAINT ck_concept_slot_redesign CHECK (legal_redesign_count BETWEEN 0 AND 1)
);

CREATE TABLE concept_attempts (
    id VARCHAR(64) PRIMARY KEY,
    slot_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL,
    phase VARCHAR(20) NOT NULL,
    task_run_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_attempt_number UNIQUE (slot_id, attempt_number),
    CONSTRAINT fk_concept_attempt_slot FOREIGN KEY (slot_id, project_id) REFERENCES concept_slots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_attempt_task FOREIGN KEY (task_run_id, project_id) REFERENCES task_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_attempt_number CHECK (attempt_number > 0),
    CONSTRAINT ck_concept_attempt_phase CHECK (phase IN ('INITIAL','REPAIR','REDESIGN','REPLACEMENT','LEGAL_REVIEW'))
);

CREATE TABLE concepts (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    slot_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    source_idea_brief_snapshot_id VARCHAR(64) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary TEXT NOT NULL,
    canonical_hash VARCHAR(71) NOT NULL,
    major_field_hash VARCHAR(71) NOT NULL,
    legal_status VARCHAR(40) NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_concept_run_slot UNIQUE (run_id, slot_id),
    CONSTRAINT uk_concept_run_canonical UNIQUE (run_id, canonical_hash),
    CONSTRAINT uk_concept_run_major_fields UNIQUE (run_id, major_field_hash),
    CONSTRAINT fk_concept_run FOREIGN KEY (run_id, project_id) REFERENCES concept_factory_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_slot FOREIGN KEY (slot_id, project_id) REFERENCES concept_slots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_snapshot FOREIGN KEY (source_idea_brief_snapshot_id, project_id) REFERENCES idea_briefs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_hashes CHECK (source_snapshot_hash LIKE 'sha256:%' AND canonical_hash LIKE 'sha256:%' AND major_field_hash LIKE 'sha256:%'),
    CONSTRAINT ck_concept_legal_status CHECK (legal_status IN ('IMPLEMENTABLE','IMPLEMENTABLE_WITH_CONTROLS','NEEDS_FACTS','REDESIGNABLE','REJECTED')),
    CONSTRAINT ck_concept_public_legal CHECK (published = FALSE OR legal_status IN ('IMPLEMENTABLE','IMPLEMENTABLE_WITH_CONTROLS'))
);

CREATE TABLE concept_legal_assessments (
    id VARCHAR(64) PRIMARY KEY,
    concept_id VARCHAR(64) NOT NULL,
    context_pack_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    safe_summary VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_assessment_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_concept_assessment_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_assessment_context FOREIGN KEY (context_pack_id, project_id) REFERENCES legal_context_packs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_assessment_status CHECK (status IN ('IMPLEMENTABLE','IMPLEMENTABLE_WITH_CONTROLS','NEEDS_FACTS','REDESIGNABLE','REJECTED'))
);

CREATE TABLE concept_legal_evidence_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id VARCHAR(64) NOT NULL,
    evidence_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_legal_evidence UNIQUE (assessment_id, evidence_id),
    CONSTRAINT fk_concept_legal_link_assessment FOREIGN KEY (assessment_id, project_id) REFERENCES concept_legal_assessments(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_legal_link_evidence FOREIGN KEY (evidence_id, project_id) REFERENCES legal_evidence(id, project_id) ON DELETE NO ACTION
);

CREATE TABLE concept_rejection_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    safe_summary VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_concept_rejection_slot FOREIGN KEY (slot_id, project_id) REFERENCES concept_slots(id, project_id) ON DELETE NO ACTION
);

ALTER TABLE concept_factory_runs ADD COLUMN task_run_id VARCHAR(64);
ALTER TABLE concept_factory_runs ADD COLUMN last_retry_idempotency_key VARCHAR(128);
ALTER TABLE concept_factory_runs ADD CONSTRAINT fk_concept_factory_task FOREIGN KEY (task_run_id, project_id) REFERENCES task_runs(id, project_id) ON DELETE NO ACTION;

ALTER TABLE concept_attempts ADD COLUMN error_classification VARCHAR(40);
ALTER TABLE concept_attempts ADD COLUMN safe_error_code VARCHAR(80);
ALTER TABLE concept_attempts ADD COLUMN retryable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE concept_attempts ADD COLUMN result_json TEXT;
ALTER TABLE concept_attempts ADD CONSTRAINT ck_concept_attempt_error CHECK (error_classification IS NULL OR error_classification IN (
    'SCHEMA_INVALID','TRANSIENT_PROVIDER_FAILURE','PERMANENT_PROVIDER_FAILURE','ORIGIN_INVALID','LOCKED_CONSTRAINT_INVALID','DUPLICATE_CONCEPT','INSUFFICIENT_DISTINCT_CONCEPTS',
    'LEGAL_REDESIGN_REQUIRED','LEGAL_REJECTED','INSUFFICIENT_INFORMATION','INTERNAL_EXECUTION_ERROR'
    ,'CANDIDATE_DOMAIN_REJECTION','LEGAL_DOMAIN_REJECTION','RESULT_SCHEMA_INVALID','LEGAL_SOURCE_FAILURE',
    'NEEDS_FACTS','INTERNAL_STATE_FAILURE'
));

ALTER TABLE concepts ADD COLUMN candidate_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE concepts ADD COLUMN origin_trace_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE concept_legal_assessments ADD COLUMN assessment_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE concept_legal_assessments ADD COLUMN legal_trace_json TEXT NOT NULL DEFAULT '{}';

CREATE TABLE concept_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    selection_reason VARCHAR(2000) NOT NULL,
    request_hash VARCHAR(71) NOT NULL,
    selected_by_user_id BIGINT NOT NULL,
    selected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_selection_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_concept_selection_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_selection_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_selection_user FOREIGN KEY (selected_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_selection_hash CHECK (request_hash LIKE 'sha256:%')
);

CREATE UNIQUE INDEX uk_concept_selection_current ON concept_selections(project_id) WHERE is_current = TRUE AND deleted_at IS NULL;
CREATE INDEX idx_concept_selection_project ON concept_selections(project_id, selected_at DESC);

CREATE TABLE concept_hypothesis_decisions (
    id VARCHAR(64) PRIMARY KEY,
    selection_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    hypothesis_type VARCHAR(40) NOT NULL,
    proposed_value_json TEXT NOT NULL,
    source VARCHAR(30) NOT NULL,
    decision_status VARCHAR(40) NOT NULL,
    final_value_json TEXT,
    proposal_version INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    decided_at TIMESTAMP WITH TIME ZONE,
    legal_impact VARCHAR(30) NOT NULL,
    legal_review_status VARCHAR(30) NOT NULL,
    legal_review_result_json TEXT,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_concept_hypothesis_version UNIQUE (selection_id, hypothesis_type, proposal_version),
    CONSTRAINT fk_concept_hypothesis_selection FOREIGN KEY (selection_id, project_id) REFERENCES concept_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_hypothesis_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_hypothesis_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_concept_hypothesis_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_concept_hypothesis_type CHECK (hypothesis_type IN ('REVENUE_MODEL','PRICE','CHANNELS','DIFFERENTIATORS','PRE_MARKET_SOM_SHARE','PRE_MARKET_SOM')),
    CONSTRAINT ck_concept_hypothesis_decision CHECK (decision_status IN ('PROPOSED','ACCEPTED','USER_EDITED_ACCEPTED','REJECTED','ALTERNATIVE_PROPOSED')),
    CONSTRAINT ck_concept_hypothesis_impact CHECK (legal_impact IN ('LEGAL_SENSITIVE','NON_LEGAL')),
    CONSTRAINT ck_concept_hypothesis_legal_status CHECK (legal_review_status IN ('NOT_REQUIRED','PENDING','PASSED','FAILED')),
    CONSTRAINT ck_concept_hypothesis_version CHECK (proposal_version > 0)
);

CREATE INDEX idx_concept_hypothesis_selection ON concept_hypothesis_decisions(selection_id, hypothesis_type, proposal_version DESC);

CREATE TABLE market_analysis_seed_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    selection_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    finalized_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_market_seed_snapshot_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_market_seed_snapshot_selection UNIQUE (selection_id),
    CONSTRAINT fk_market_seed_snapshot_selection FOREIGN KEY (selection_id, project_id) REFERENCES concept_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_seed_snapshot_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_seed_snapshot_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_seed_snapshot_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_market_seed_snapshot_hashes CHECK (source_snapshot_hash LIKE 'sha256:%' AND snapshot_hash LIKE 'sha256:%')
);

CREATE INDEX idx_market_seed_snapshot_project ON market_analysis_seed_snapshots(project_id, finalized_at DESC);

CREATE TABLE module_handoffs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    module VARCHAR(40) NOT NULL,
    input_contract VARCHAR(100) NOT NULL,
    input_snapshot_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    requested_operation VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    callback_mode VARCHAR(30) NOT NULL,
    callback_reference VARCHAR(500) NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_module_handoff_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_module_handoff_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_module_handoff_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_snapshot FOREIGN KEY (input_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_module_handoff_module CHECK (module IN ('MARKET_ANALYSIS')),
    CONSTRAINT ck_module_handoff_status CHECK (status IN ('PREPARED')),
    CONSTRAINT ck_module_handoff_hashes CHECK (input_snapshot_hash LIKE 'sha256:%' AND idempotency_key LIKE 'sha256:%')
);

CREATE INDEX idx_module_handoff_project ON module_handoffs(project_id, requested_at DESC);

CREATE TABLE module_runs (
    id VARCHAR(64) PRIMARY KEY,
    handoff_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    module VARCHAR(40) NOT NULL,
    input_snapshot_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    external_run_reference VARCHAR(500),
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    result_reference VARCHAR(1000),
    result_hash VARCHAR(71),
    safe_error_code VARCHAR(80),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_module_run_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_module_run_handoff UNIQUE (handoff_id),
    CONSTRAINT fk_module_run_handoff FOREIGN KEY (handoff_id, project_id) REFERENCES module_handoffs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_run_snapshot FOREIGN KEY (input_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_module_run_module CHECK (module IN ('MARKET_ANALYSIS')),
    CONSTRAINT ck_module_run_status CHECK (status IN ('NOT_CONNECTED','READY','QUEUED','RUNNING','COMPLETED','FAILED','STALE')),
    CONSTRAINT ck_module_run_hashes CHECK (input_snapshot_hash LIKE 'sha256:%' AND (result_hash IS NULL OR result_hash LIKE 'sha256:%'))
);

CREATE INDEX idx_module_run_project ON module_runs(project_id, created_at DESC);

ALTER TABLE module_runs DROP CONSTRAINT ck_module_run_status;
ALTER TABLE module_runs ADD CONSTRAINT ck_module_run_status
    CHECK (status IN ('NOT_CONNECTED','READY','QUEUED','RUNNING','NEEDS_INPUT','COMPLETED','FAILED','STALE'));

CREATE TABLE module_results (
    module_run_id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    input_snapshot_id VARCHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    result_reference VARCHAR(1000) NOT NULL,
    summary_json TEXT NOT NULL,
    competitors_json TEXT NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    result_hash VARCHAR(71) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_module_result_run FOREIGN KEY (module_run_id, project_id) REFERENCES module_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_result_snapshot FOREIGN KEY (input_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT ck_module_result_status CHECK (status IN ('COMPLETED','FAILED','NEEDS_INPUT')),
    CONSTRAINT ck_module_result_hash CHECK (result_hash LIKE 'sha256:%')
);

CREATE INDEX idx_module_result_project ON module_results(project_id, completed_at DESC);

ALTER TABLE module_handoffs DROP CONSTRAINT fk_module_handoff_snapshot;
ALTER TABLE module_runs DROP CONSTRAINT fk_module_run_snapshot;
ALTER TABLE module_handoffs DROP CONSTRAINT ck_module_handoff_module;
ALTER TABLE module_handoffs ADD CONSTRAINT ck_module_handoff_module CHECK (module IN ('MARKET_ANALYSIS','BUSINESS_MODEL','TECH_OPS','FINANCIAL_ANALYSIS','PERSONA_RESPONSE'));
ALTER TABLE module_runs DROP CONSTRAINT ck_module_run_module;
ALTER TABLE module_runs ADD CONSTRAINT ck_module_run_module CHECK (module IN ('MARKET_ANALYSIS','BUSINESS_MODEL','TECH_OPS','FINANCIAL_ANALYSIS','PERSONA_RESPONSE'));

CREATE TABLE tech_ops_input_preparations (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    required_facts_json TEXT NOT NULL,
    proposal_decisions_json TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    updated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_tech_ops_preparation_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_tech_ops_preparation_source UNIQUE (project_id, source_market_seed_snapshot_id),
    CONSTRAINT fk_tech_ops_preparation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_preparation_source FOREIGN KEY (source_market_seed_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_preparation_user FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_tech_ops_preparation_hash CHECK (source_snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_tech_ops_preparation_revision CHECK (revision > 0)
);

CREATE INDEX idx_tech_ops_preparation_project ON tech_ops_input_preparations(project_id, updated_at DESC);

CREATE TABLE tech_ops_evidence_references (
    id VARCHAR(64) PRIMARY KEY,
    preparation_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    evidence_type VARCHAR(30) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    artifact_ref VARCHAR(1000) NOT NULL,
    description VARCHAR(1000),
    provided_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_tech_ops_evidence_preparation FOREIGN KEY (preparation_id, project_id) REFERENCES tech_ops_input_preparations(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_evidence_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_evidence_user FOREIGN KEY (provided_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_tech_ops_evidence_type CHECK (evidence_type IN ('QUOTE','BOM','SUPPLIER','SPECIFICATION','PILOT'))
);

CREATE INDEX idx_tech_ops_evidence_preparation ON tech_ops_evidence_references(preparation_id, created_at);

CREATE TABLE tech_ops_input_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    preparation_id VARCHAR(64) NOT NULL,
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    finalized_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_tech_ops_snapshot_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_tech_ops_snapshot_preparation UNIQUE (preparation_id),
    CONSTRAINT uk_tech_ops_snapshot_source UNIQUE (project_id, source_market_seed_snapshot_id),
    CONSTRAINT fk_tech_ops_snapshot_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_snapshot_preparation FOREIGN KEY (preparation_id, project_id) REFERENCES tech_ops_input_preparations(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_snapshot_source FOREIGN KEY (source_market_seed_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_tech_ops_snapshot_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_tech_ops_snapshot_hash CHECK (snapshot_hash LIKE 'sha256:%')
);

CREATE INDEX idx_tech_ops_snapshot_project ON tech_ops_input_snapshots(project_id, finalized_at DESC);

CREATE TABLE financial_input_preparations (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_tech_ops_snapshot_id VARCHAR(64) NOT NULL,
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    financial_fields_json TEXT NOT NULL,
    upstream_references_json TEXT NOT NULL,
    assistance_json TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    updated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_financial_preparation_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_financial_preparation_source UNIQUE (project_id, source_tech_ops_snapshot_id),
    CONSTRAINT fk_financial_preparation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_preparation_tech_ops FOREIGN KEY (source_tech_ops_snapshot_id, project_id) REFERENCES tech_ops_input_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_preparation_market_seed FOREIGN KEY (source_market_seed_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_preparation_user FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_financial_preparation_hash CHECK (source_snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_financial_preparation_revision CHECK (revision > 0)
);

CREATE INDEX idx_financial_preparation_project ON financial_input_preparations(project_id, updated_at DESC);

CREATE TABLE financial_input_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    preparation_id VARCHAR(64) NOT NULL,
    source_tech_ops_snapshot_id VARCHAR(64) NOT NULL,
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    finalized_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_financial_snapshot_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_financial_snapshot_preparation UNIQUE (preparation_id),
    CONSTRAINT uk_financial_snapshot_source UNIQUE (project_id, source_tech_ops_snapshot_id),
    CONSTRAINT fk_financial_snapshot_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_snapshot_preparation FOREIGN KEY (preparation_id, project_id) REFERENCES financial_input_preparations(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_snapshot_tech_ops FOREIGN KEY (source_tech_ops_snapshot_id, project_id) REFERENCES tech_ops_input_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_snapshot_market_seed FOREIGN KEY (source_market_seed_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_financial_snapshot_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_financial_snapshot_hash CHECK (snapshot_hash LIKE 'sha256:%')
);

CREATE INDEX idx_financial_snapshot_project ON financial_input_snapshots(project_id, finalized_at DESC);

CREATE TABLE marketing_source_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL,
    selection_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    finalized_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_marketing_source_id_project UNIQUE (id, project_id),
    CONSTRAINT uk_marketing_source_market_seed UNIQUE (source_market_seed_snapshot_id),
    CONSTRAINT fk_marketing_source_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_source_market_seed FOREIGN KEY (source_market_seed_snapshot_id, project_id) REFERENCES market_analysis_seed_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_source_selection FOREIGN KEY (selection_id, project_id) REFERENCES concept_selections(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_source_concept FOREIGN KEY (concept_id, project_id) REFERENCES concepts(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_marketing_source_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_marketing_source_hash CHECK (snapshot_hash LIKE 'sha256:%')
);

CREATE INDEX idx_marketing_source_project ON marketing_source_snapshots(project_id, finalized_at DESC);

CREATE TABLE pipeline_marketing_contents (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    marketing_source_snapshot_id VARCHAR(64) NOT NULL,
    source_snapshot_hash VARCHAR(71) NOT NULL,
    source_snapshot_json TEXT NOT NULL,
    request_json TEXT NOT NULL,
    content_type VARCHAR(30) NOT NULL,
    channel VARCHAR(120) NOT NULL,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    task_run_id VARCHAR(64),
    current_revision_number INTEGER NOT NULL DEFAULT 0,
    finalized_revision_number INTEGER,
    created_by_user_id BIGINT NOT NULL,
    finalized_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pipeline_marketing_content_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_pipeline_marketing_content_source FOREIGN KEY (marketing_source_snapshot_id, project_id) REFERENCES marketing_source_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_pipeline_marketing_content_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_pipeline_marketing_content_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT ck_pipeline_marketing_content_type CHECK (content_type IN ('SOCIAL_POST','AD_COPY','LANDING_PAGE','BLOG_INTRO','EMAIL','BANNER','POSTER','IMAGE_BRIEF')),
    CONSTRAINT ck_pipeline_marketing_content_status CHECK (status IN ('QUEUED','RUNNING','COMPLETED','FAILED','FINALIZED'))
);

CREATE INDEX idx_pipeline_marketing_contents_project ON pipeline_marketing_contents(project_id, created_at DESC);

CREATE TABLE pipeline_marketing_content_revisions (
    id VARCHAR(64) PRIMARY KEY, content_id VARCHAR(64) NOT NULL, revision_number INTEGER NOT NULL,
    revision_type VARCHAR(30) NOT NULL, origin VARCHAR(10) NOT NULL, result_json TEXT NOT NULL,
    created_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pipeline_marketing_revision_content FOREIGN KEY (content_id) REFERENCES pipeline_marketing_contents(id) ON DELETE NO ACTION,
    CONSTRAINT fk_pipeline_marketing_revision_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT uk_pipeline_marketing_revision_number UNIQUE (content_id, revision_number),
    CONSTRAINT ck_pipeline_marketing_revision_type CHECK (revision_type IN ('GENERATED','TONE_EDITED','SHORTENED','LEGAL_NOTICE_APPLIED','USER_EDITED','FINALIZED')),
    CONSTRAINT ck_pipeline_marketing_revision_origin CHECK (origin IN ('AI','USER','SYSTEM'))
);

CREATE TABLE pipeline_marketing_assets (
    id VARCHAR(64) PRIMARY KEY, content_id VARCHAR(64) NOT NULL, revision_id VARCHAR(64) NOT NULL,
    artifact_ref VARCHAR(300) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pipeline_marketing_asset_content FOREIGN KEY (content_id) REFERENCES pipeline_marketing_contents(id) ON DELETE NO ACTION,
    CONSTRAINT fk_pipeline_marketing_asset_revision FOREIGN KEY (revision_id) REFERENCES pipeline_marketing_content_revisions(id) ON DELETE NO ACTION
);
