CREATE TABLE market_research_ledger_artifacts (
    id VARCHAR(36) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    concept_id VARCHAR(64) NOT NULL,
    source_run_id VARCHAR(64) NOT NULL,
    market_task_run_id VARCHAR(64) NOT NULL,
    task_attempt_id VARCHAR(64) NOT NULL,
    canonical_input_hash VARCHAR(71) NOT NULL,
    concept_snapshot_hash VARCHAR(71) NOT NULL,
    as_of_date VARCHAR(20) NOT NULL,
    object_key VARCHAR(1000) NOT NULL,
    content_type VARCHAR(80) NOT NULL,
    size_bytes BIGINT NOT NULL,
    object_checksum_sha256 VARCHAR(64) NOT NULL,
    manifest_hash VARCHAR(64) NOT NULL,
    manifest_json TEXT NOT NULL,
    state VARCHAR(20) NOT NULL,
    market_research_version_id BIGINT,
    committed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_ledger_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_ledger_task FOREIGN KEY (market_task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_ledger_attempt FOREIGN KEY (task_attempt_id) REFERENCES task_attempts(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_ledger_version FOREIGN KEY (market_research_version_id) REFERENCES market_research_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_ledger_attempt UNIQUE (market_task_run_id, task_attempt_id),
    CONSTRAINT uk_market_ledger_version UNIQUE (market_research_version_id),
    CONSTRAINT uk_market_ledger_object UNIQUE (object_key),
    CONSTRAINT ck_market_ledger_state CHECK (state IN ('STAGED', 'COMMITTED')),
    CONSTRAINT ck_market_ledger_size CHECK (size_bytes > 0)
);
CREATE INDEX idx_market_ledger_project_source
    ON market_research_ledger_artifacts(project_id, concept_id, source_run_id, created_at DESC);
