-- G1 Conversational Validation Workspace domain foundation.
-- Additive only: existing journey and task-run tables remain unchanged.

CREATE TABLE idea_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT,
    status VARCHAR(20) NOT NULL,
    closed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_conversation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_conversation_source FOREIGN KEY (source_id) REFERENCES idea_sources(id) ON DELETE NO ACTION,
    CONSTRAINT ck_idea_conversation_status CHECK (status IN ('ACTIVE', 'CLOSED'))
);
CREATE INDEX idx_idea_conversation_current
    ON idea_conversations(project_id, created_at DESC, id DESC);

CREATE TABLE idea_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_message_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_message_conversation FOREIGN KEY (conversation_id) REFERENCES idea_conversations(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_message_sequence UNIQUE (conversation_id, sequence_number),
    CONSTRAINT ck_idea_message_sequence CHECK (sequence_number > 0),
    CONSTRAINT ck_idea_message_role CHECK (role IN ('USER', 'ASSISTANT'))
);
CREATE INDEX idx_idea_message_conversation
    ON idea_messages(conversation_id, sequence_number);

CREATE TABLE idea_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    message_id BIGINT,
    stored_file_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    failure_code VARCHAR(80),
    extracted_text_hash VARCHAR(71),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_attachment_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_attachment_conversation FOREIGN KEY (conversation_id) REFERENCES idea_conversations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_attachment_message FOREIGN KEY (message_id) REFERENCES idea_messages(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_attachment_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION,
    CONSTRAINT ck_idea_attachment_status CHECK (status IN ('UPLOADED', 'PROCESSING', 'EXTRACTED', 'FAILED')),
    CONSTRAINT ck_idea_attachment_hash CHECK (extracted_text_hash IS NULL OR extracted_text_hash LIKE 'sha256:%')
);
CREATE INDEX idx_idea_attachment_conversation
    ON idea_attachments(conversation_id, created_at, id);

CREATE TABLE opportunity_brief_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    based_on_version_id BIGINT,
    version_number INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    snapshot_json TEXT NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_opportunity_brief_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_opportunity_brief_conversation FOREIGN KEY (conversation_id) REFERENCES idea_conversations(id) ON DELETE NO ACTION,
    CONSTRAINT fk_opportunity_brief_based_on FOREIGN KEY (based_on_version_id) REFERENCES opportunity_brief_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_opportunity_brief_version UNIQUE (project_id, version_number),
    CONSTRAINT ck_opportunity_brief_version CHECK (version_number > 0),
    CONSTRAINT ck_opportunity_brief_state CHECK (state IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_opportunity_brief_hash CHECK (snapshot_hash LIKE 'sha256:%')
);
CREATE INDEX idx_opportunity_brief_current
    ON opportunity_brief_versions(project_id, state, version_number DESC);

CREATE TABLE opportunity_field_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    brief_version_id BIGINT NOT NULL,
    field_key VARCHAR(100) NOT NULL,
    value_json TEXT,
    decision_status VARCHAR(20) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_reference VARCHAR(500),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_opportunity_field_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_opportunity_field_brief FOREIGN KEY (brief_version_id) REFERENCES opportunity_brief_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_opportunity_field_key UNIQUE (brief_version_id, field_key),
    CONSTRAINT ck_opportunity_field_decision CHECK (decision_status IN ('LOCKED', 'PREFERRED', 'OPEN', 'ASSUMPTION')),
    CONSTRAINT ck_opportunity_field_source CHECK (source_type IN ('USER_CONFIRMED', 'SOURCE_EXTRACTED', 'AI_PROPOSED', 'DEFAULT_ASSUMPTION', 'MISSING')),
    CONSTRAINT ck_opportunity_field_missing CHECK (
        (source_type = 'MISSING' AND value_json IS NULL)
        OR (source_type <> 'MISSING' AND value_json IS NOT NULL)
    )
);
CREATE INDEX idx_opportunity_field_brief
    ON opportunity_field_values(brief_version_id, field_key);

CREATE TABLE regulatory_boundary_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    brief_version_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    input_snapshot_hash VARCHAR(71) NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_regulatory_boundary_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_regulatory_boundary_run_brief FOREIGN KEY (brief_version_id) REFERENCES opportunity_brief_versions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_regulatory_boundary_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT ck_regulatory_boundary_run_hash CHECK (input_snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_regulatory_boundary_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);
CREATE INDEX idx_regulatory_boundary_run_current
    ON regulatory_boundary_runs(project_id, created_at DESC, id DESC);

CREATE TABLE regulatory_boundary_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    brief_version_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    snapshot_json TEXT NOT NULL,
    snapshot_hash VARCHAR(71) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_regulatory_boundary_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_regulatory_boundary_version_run FOREIGN KEY (run_id) REFERENCES regulatory_boundary_runs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_regulatory_boundary_version_brief FOREIGN KEY (brief_version_id) REFERENCES opportunity_brief_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_regulatory_boundary_run UNIQUE (run_id),
    CONSTRAINT uk_regulatory_boundary_version UNIQUE (project_id, version_number),
    CONSTRAINT ck_regulatory_boundary_version_number CHECK (version_number > 0),
    CONSTRAINT ck_regulatory_boundary_status CHECK (status IN ('READY', 'NEEDS_INPUT', 'BLOCKED', 'FAILED')),
    CONSTRAINT ck_regulatory_boundary_hash CHECK (snapshot_hash LIKE 'sha256:%')
);
CREATE INDEX idx_regulatory_boundary_current
    ON regulatory_boundary_versions(project_id, version_number DESC);

CREATE TABLE boundary_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    boundary_version_id BIGINT NOT NULL,
    evidence_key VARCHAR(100) NOT NULL,
    law_name VARCHAR(300) NOT NULL,
    article VARCHAR(200),
    title VARCHAR(500),
    excerpt TEXT NOT NULL,
    effective_date VARCHAR(40),
    source_url VARCHAR(1000) NOT NULL,
    source_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_boundary_evidence_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_boundary_evidence_version FOREIGN KEY (boundary_version_id) REFERENCES regulatory_boundary_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_boundary_evidence_key UNIQUE (boundary_version_id, evidence_key)
);
CREATE INDEX idx_boundary_evidence_version
    ON boundary_evidence(boundary_version_id, evidence_key);

CREATE TABLE boundary_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    boundary_version_id BIGINT NOT NULL,
    rule_key VARCHAR(100) NOT NULL,
    rule_type VARCHAR(40) NOT NULL,
    statement TEXT NOT NULL,
    rationale TEXT NOT NULL,
    affected_brief_fields_json TEXT NOT NULL,
    evidence_ids_json TEXT NOT NULL,
    severity VARCHAR(20),
    user_action_options_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_boundary_rule_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_boundary_rule_version FOREIGN KEY (boundary_version_id) REFERENCES regulatory_boundary_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_boundary_rule_key UNIQUE (boundary_version_id, rule_key),
    CONSTRAINT ck_boundary_rule_type CHECK (rule_type IN ('PROHIBITED_ROLE', 'PROHIBITED_ACTIVITY', 'ALLOWED_PATTERN', 'REQUIRED_CONTROL', 'REQUIRED_PARTNER', 'REQUIRED_DISCLOSURE', 'UNRESOLVED_FACT'))
);
CREATE INDEX idx_boundary_rule_version
    ON boundary_rules(boundary_version_id, rule_type);

CREATE TABLE boundary_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    boundary_version_id BIGINT NOT NULL,
    question_key VARCHAR(100) NOT NULL,
    question TEXT NOT NULL,
    reason TEXT NOT NULL,
    target_brief_field VARCHAR(100),
    state VARCHAR(20) NOT NULL,
    answer_json TEXT,
    answered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_boundary_question_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_boundary_question_version FOREIGN KEY (boundary_version_id) REFERENCES regulatory_boundary_versions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_boundary_question_key UNIQUE (boundary_version_id, question_key),
    CONSTRAINT ck_boundary_question_state CHECK (state IN ('OPEN', 'ANSWERED')),
    CONSTRAINT ck_boundary_question_answer CHECK (
        (state = 'OPEN' AND answer_json IS NULL AND answered_at IS NULL)
        OR (state = 'ANSWERED' AND answer_json IS NOT NULL AND answered_at IS NOT NULL)
    )
);
CREATE INDEX idx_boundary_question_version
    ON boundary_questions(boundary_version_id, state);

CREATE TABLE job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    stage VARCHAR(50) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message_key VARCHAR(120) NOT NULL,
    message_params_json TEXT NOT NULL,
    technical_code VARCHAR(80),
    sequence BIGINT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_job_event_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_job_event_task_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_job_event_sequence UNIQUE (job_id, sequence),
    CONSTRAINT ck_job_event_sequence CHECK (sequence > 0),
    CONSTRAINT ck_job_event_status CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'NEEDS_INPUT'))
);
CREATE INDEX idx_job_event_replay ON job_events(job_id, sequence);
CREATE INDEX idx_job_event_project ON job_events(project_id, occurred_at, id);
