CREATE TABLE concept_refinement_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    selection_id BIGINT NOT NULL REFERENCES concept_portfolio_selections(id),
    business_validation_session_id VARCHAR(64) NOT NULL REFERENCES business_validation_sessions(id),
    source_market_version_id BIGINT NOT NULL REFERENCES market_research_versions(id),
    source_bm_version_id BIGINT NOT NULL REFERENCES market_research_versions(id),
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL REFERENCES market_analysis_seed_snapshots(id),
    source_selection_revision INTEGER NOT NULL,
    source_bm_plan_revision INTEGER NOT NULL,
    round_number INTEGER NOT NULL,
    policy_version VARCHAR(40) NOT NULL,
    task_run_id VARCHAR(64) NOT NULL REFERENCES task_runs(id),
    attempt INTEGER NOT NULL,
    state VARCHAR(24) NOT NULL,
    command_idempotency_key VARCHAR(128) NOT NULL,
    canonical_material_hash VARCHAR(71) NOT NULL,
    proposal_json TEXT,
    drift_rejections_json TEXT,
    last_error_code VARCHAR(80),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_concept_refinement_state CHECK (
        state IN ('PROPOSING', 'AWAITING_DECISION', 'NO_CHANGES', 'FAILED', 'STALE')),
    CONSTRAINT ck_concept_refinement_round CHECK (round_number BETWEEN 1 AND 3),
    CONSTRAINT ck_concept_refinement_attempt CHECK (attempt BETWEEN 1 AND 3),
    CONSTRAINT ck_concept_refinement_hash CHECK (canonical_material_hash LIKE 'sha256:%')
);

CREATE UNIQUE INDEX uq_concept_refinement_source_round
    ON concept_refinement_rounds(business_validation_session_id, round_number)
    WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_concept_refinement_task_run
    ON concept_refinement_rounds(task_run_id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_concept_refinement_project_current
    ON concept_refinement_rounds(project_id, created_at DESC)
    WHERE deleted_at IS NULL;
