DROP INDEX uk_market_seed_portfolio_selection;
CREATE UNIQUE INDEX uk_market_seed_portfolio_selection
    ON market_analysis_seed_snapshots(portfolio_selection_id)
    WHERE source_type='CONCEPT_PORTFOLIO_V2' AND deleted_at IS NULL AND stale_at IS NULL;

CREATE TABLE concept_refinement_finals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    round_id BIGINT NOT NULL UNIQUE REFERENCES concept_refinement_rounds(id),
    selection_id BIGINT NOT NULL REFERENCES concept_portfolio_selections(id),
    outcome VARCHAR(30) NOT NULL,
    source_business_validation_session_id VARCHAR(64) NOT NULL REFERENCES business_validation_sessions(id),
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL REFERENCES market_analysis_seed_snapshots(id),
    final_market_seed_snapshot_id VARCHAR(64) NOT NULL REFERENCES market_analysis_seed_snapshots(id),
    source_selection_revision INTEGER NOT NULL, source_bm_plan_revision INTEGER NOT NULL,
    final_selection_revision INTEGER NOT NULL, final_bm_plan_revision INTEGER NOT NULL,
    decision_hash VARCHAR(71), application_hash VARCHAR(71), overlay_json TEXT NOT NULL,
    final_json TEXT NOT NULL, final_hash VARCHAR(71) NOT NULL,
    finalized_by_user_id BIGINT NOT NULL REFERENCES users(id), finalized_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_concept_refinement_final_outcome CHECK(outcome IN('REFINED','KEEP_CURRENT','NO_CHANGES')),
    CONSTRAINT ck_concept_refinement_final_hash CHECK(final_hash LIKE 'sha256:%'),
    CONSTRAINT ck_concept_refinement_final_decision_hash CHECK(decision_hash IS NULL OR decision_hash LIKE 'sha256:%'),
    CONSTRAINT ck_concept_refinement_final_application_hash CHECK(application_hash IS NULL OR application_hash LIKE 'sha256:%')
);

ALTER TABLE concept_refinement_rounds DROP CONSTRAINT ck_concept_refinement_state;
ALTER TABLE concept_refinement_rounds
    ADD COLUMN finalization_idempotency_key VARCHAR(128), ADD COLUMN finalization_hash VARCHAR(71),
    ADD COLUMN finalization_task_run_id VARCHAR(64) REFERENCES task_runs(id), ADD COLUMN finalization_attempt INTEGER,
    ADD COLUMN finalization_error_code VARCHAR(80), ADD COLUMN final_market_seed_snapshot_id VARCHAR(64) REFERENCES market_analysis_seed_snapshots(id),
    ADD COLUMN final_id BIGINT REFERENCES concept_refinement_finals(id), ADD COLUMN finalized_at TIMESTAMP;
ALTER TABLE concept_refinement_rounds
    ADD CONSTRAINT ck_concept_refinement_state CHECK(state IN('PROPOSING','AWAITING_DECISION','NO_CHANGES','FAILED','STALE','DECISION_RECORDED','KEEP_CURRENT','APPLYING_HYPOTHESES','APPLY_FAILED','LEGAL_REVIEW_PENDING','LEGAL_REVIEW_FAILED','LEGAL_BLOCKED','APPLIED_PENDING_FINALIZATION','FINALIZING','FINALIZATION_FAILED','FINALIZED')),
    ADD CONSTRAINT ck_concept_refinement_finalization_hash CHECK(finalization_hash IS NULL OR finalization_hash LIKE 'sha256:%'),
    ADD CONSTRAINT ck_concept_refinement_finalization_attempt CHECK(finalization_attempt IS NULL OR finalization_attempt BETWEEN 1 AND 3);
