CREATE TABLE market_interview_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_market_seed_snapshot_id VARCHAR(64) NOT NULL,
    source_selection_id BIGINT NOT NULL,
    source_selection_revision INTEGER NOT NULL,
    source_bm_plan_revision INTEGER NOT NULL,
    task_run_id VARCHAR(64) NOT NULL,
    attempt INTEGER NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    input_hash VARCHAR(71) NOT NULL,
    result_json TEXT,
    failure_code VARCHAR(80),
    state VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_interview_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_interview_run_seed FOREIGN KEY (source_market_seed_snapshot_id) REFERENCES market_analysis_seed_snapshots(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_interview_run_selection FOREIGN KEY (source_selection_id) REFERENCES concept_portfolio_selections(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_interview_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_interview_run_task UNIQUE (task_run_id),
    CONSTRAINT uk_market_interview_run_idempotency UNIQUE (project_id, idempotency_key),
    CONSTRAINT ck_market_interview_run_state CHECK (state IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'STALE')),
    CONSTRAINT ck_market_interview_run_attempt CHECK (attempt BETWEEN 1 AND 3),
    CONSTRAINT ck_market_interview_run_selection_revision CHECK (source_selection_revision >= 0),
    CONSTRAINT ck_market_interview_run_bm_revision CHECK (source_bm_plan_revision >= 0),
    CONSTRAINT ck_market_interview_run_hash CHECK (input_hash LIKE 'sha256:%')
);

CREATE INDEX idx_market_interview_runs_project
    ON market_interview_runs(project_id, created_at DESC);
CREATE INDEX idx_market_interview_runs_source
    ON market_interview_runs(source_market_seed_snapshot_id, source_selection_id, source_selection_revision);
