-- R1C additive foundation for the new six-module pipeline.
-- Legacy tables remain until their JPA entities leave the runtime scan in R7.

ALTER TABLE task_runs ADD CONSTRAINT uk_task_runs_id_project UNIQUE (id, project_id);

CREATE TABLE pipeline_module_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    module VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    run_sequence BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    source_snapshot_id VARCHAR(64),
    source_snapshot_hash VARCHAR(71),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pipeline_module_run_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_pipeline_module_run_task
        FOREIGN KEY (task_run_id, project_id) REFERENCES task_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT uk_pipeline_module_run_project_id UNIQUE (id, project_id),
    CONSTRAINT uk_pipeline_module_run_project_module UNIQUE (id, project_id, module),
    CONSTRAINT uk_pipeline_module_run_sequence UNIQUE (project_id, module, run_sequence),
    CONSTRAINT ck_pipeline_module_run_module CHECK (module IN (
        'IDEA', 'CONCEPT_FACTORY', 'CONCEPT_SELECTION', 'MARKET_ANALYSIS',
        'BUSINESS_PERSONA_TEST', 'MARKETING'
    )),
    CONSTRAINT ck_pipeline_module_run_status CHECK (status IN (
        'NOT_READY', 'READY', 'QUEUED', 'RUNNING', 'NEEDS_INPUT',
        'COMPLETED', 'FAILED', 'STALE', 'NOT_CONNECTED'
    )),
    CONSTRAINT ck_pipeline_module_run_sequence_positive CHECK (run_sequence > 0),
    CONSTRAINT ck_pipeline_module_run_source_hash CHECK (
        source_snapshot_hash IS NULL OR source_snapshot_hash LIKE 'sha256:%'
    )
);

CREATE INDEX idx_pipeline_module_run_project_status
    ON pipeline_module_runs(project_id, module, status, created_at);
CREATE INDEX idx_pipeline_module_run_task
    ON pipeline_module_runs(task_run_id) WHERE task_run_id IS NOT NULL;

CREATE TABLE module_handoffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_module VARCHAR(40) NOT NULL,
    target_module VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    source_module_run_id BIGINT,
    source_snapshot_id VARCHAR(64),
    source_snapshot_hash VARCHAR(71),
    payload_stored_file_id BIGINT,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_module_handoff_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_source_run
        FOREIGN KEY (source_module_run_id, project_id, source_module)
        REFERENCES pipeline_module_runs(id, project_id, module) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_payload_file
        FOREIGN KEY (payload_stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_handoff_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT uk_module_handoff_idempotency UNIQUE (project_id, target_module, idempotency_key),
    CONSTRAINT ck_module_handoff_distinct_modules CHECK (source_module <> target_module),
    CONSTRAINT ck_module_handoff_source_module CHECK (source_module IN (
        'IDEA', 'CONCEPT_FACTORY', 'CONCEPT_SELECTION', 'MARKET_ANALYSIS',
        'BUSINESS_PERSONA_TEST', 'MARKETING'
    )),
    CONSTRAINT ck_module_handoff_target_module CHECK (target_module IN (
        'IDEA', 'CONCEPT_FACTORY', 'CONCEPT_SELECTION', 'MARKET_ANALYSIS',
        'BUSINESS_PERSONA_TEST', 'MARKETING'
    )),
    CONSTRAINT ck_module_handoff_status CHECK (status IN (
        'NOT_READY', 'READY', 'QUEUED', 'RUNNING', 'NEEDS_INPUT',
        'COMPLETED', 'FAILED', 'STALE', 'NOT_CONNECTED'
    )),
    CONSTRAINT ck_module_handoff_source_hash CHECK (
        source_snapshot_hash IS NULL OR source_snapshot_hash LIKE 'sha256:%'
    )
);

CREATE INDEX idx_module_handoff_project_target
    ON module_handoffs(project_id, target_module, status, created_at);
CREATE INDEX idx_module_handoff_source_run
    ON module_handoffs(source_module_run_id) WHERE source_module_run_id IS NOT NULL;

CREATE TABLE module_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    module_run_id BIGINT NOT NULL,
    module VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    result_type VARCHAR(80) NOT NULL,
    result_sequence BIGINT NOT NULL,
    source_snapshot_id VARCHAR(64),
    source_snapshot_hash VARCHAR(71),
    result_snapshot_id VARCHAR(64),
    result_snapshot_hash VARCHAR(71),
    result_stored_file_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_module_result_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_module_result_run
        FOREIGN KEY (module_run_id, project_id, module)
        REFERENCES pipeline_module_runs(id, project_id, module) ON DELETE NO ACTION,
    CONSTRAINT fk_module_result_file
        FOREIGN KEY (result_stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION,
    CONSTRAINT uk_module_result_sequence UNIQUE (module_run_id, result_sequence),
    CONSTRAINT uk_module_result_snapshot UNIQUE (project_id, result_snapshot_id),
    CONSTRAINT uk_module_result_project_id UNIQUE (id, project_id),
    CONSTRAINT ck_module_result_module CHECK (module IN (
        'IDEA', 'CONCEPT_FACTORY', 'CONCEPT_SELECTION', 'MARKET_ANALYSIS',
        'BUSINESS_PERSONA_TEST', 'MARKETING'
    )),
    CONSTRAINT ck_module_result_status CHECK (status IN (
        'NOT_READY', 'READY', 'QUEUED', 'RUNNING', 'NEEDS_INPUT',
        'COMPLETED', 'FAILED', 'STALE', 'NOT_CONNECTED'
    )),
    CONSTRAINT ck_module_result_sequence_positive CHECK (result_sequence > 0),
    CONSTRAINT ck_module_result_source_hash CHECK (
        source_snapshot_hash IS NULL OR source_snapshot_hash LIKE 'sha256:%'
    ),
    CONSTRAINT ck_module_result_snapshot_hash CHECK (
        result_snapshot_hash IS NULL OR result_snapshot_hash LIKE 'sha256:%'
    )
);

CREATE INDEX idx_module_result_project_module
    ON module_results(project_id, module, status, created_at);

CREATE TABLE planning_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    snapshot_sequence BIGINT NOT NULL,
    parent_snapshot_id BIGINT,
    source_module_result_id BIGINT,
    source_snapshot_id VARCHAR(64),
    source_snapshot_hash VARCHAR(71),
    snapshot_hash VARCHAR(71) NOT NULL,
    semantic_label VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL,
    content_json TEXT NOT NULL,
    finalized BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_planning_snapshot_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_snapshot_parent
        FOREIGN KEY (parent_snapshot_id, project_id)
        REFERENCES planning_snapshots(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_snapshot_module_result
        FOREIGN KEY (source_module_result_id, project_id)
        REFERENCES module_results(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT fk_planning_snapshot_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT uk_planning_snapshot_sequence UNIQUE (project_id, snapshot_sequence),
    CONSTRAINT uk_planning_snapshot_hash UNIQUE (project_id, snapshot_hash),
    CONSTRAINT uk_planning_snapshot_project_id UNIQUE (id, project_id),
    CONSTRAINT ck_planning_snapshot_sequence_positive CHECK (snapshot_sequence > 0),
    CONSTRAINT ck_planning_snapshot_hash CHECK (snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_planning_snapshot_source_hash CHECK (
        source_snapshot_hash IS NULL OR source_snapshot_hash LIKE 'sha256:%'
    )
);

CREATE INDEX idx_planning_snapshot_project_current
    ON planning_snapshots(project_id, finalized, snapshot_sequence DESC);
CREATE INDEX idx_planning_snapshot_parent
    ON planning_snapshots(parent_snapshot_id) WHERE parent_snapshot_id IS NOT NULL;
