-- R2B canonical Idea Brief persistence. Confirmed rows are immutable snapshots;
-- later edits create a new draft row linked by parent_brief_id.

CREATE TABLE idea_briefs (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    brief_sequence BIGINT NOT NULL,
    parent_brief_id VARCHAR(64),
    active_task_run_id VARCHAR(64),
    confirmed_snapshot_id VARCHAR(64),
    snapshot_hash VARCHAR(71),
    created_by_user_id BIGINT NOT NULL,
    last_command VARCHAR(30),
    last_idempotency_key VARCHAR(100),
    last_request_hash VARCHAR(71),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_brief_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_parent FOREIGN KEY (parent_brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_confirmed FOREIGN KEY (confirmed_snapshot_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_brief_task FOREIGN KEY (active_task_run_id, project_id) REFERENCES task_runs(id, project_id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_brief_sequence UNIQUE (project_id, brief_sequence),
    CONSTRAINT ck_idea_brief_sequence_positive CHECK (brief_sequence > 0),
    CONSTRAINT ck_idea_brief_status CHECK (status IN ('DRAFT', 'DERIVING', 'NEEDS_INPUT', 'READY_FOR_REVIEW', 'CONFIRMED', 'FAILED', 'STALE')),
    CONSTRAINT ck_idea_brief_snapshot_hash CHECK (snapshot_hash IS NULL OR snapshot_hash LIKE 'sha256:%'),
    CONSTRAINT ck_idea_brief_request_hash CHECK (last_request_hash IS NULL OR last_request_hash LIKE 'sha256:%'),
    CONSTRAINT ck_idea_brief_confirmed_snapshot CHECK (
        (status = 'CONFIRMED' AND confirmed_snapshot_id = id AND snapshot_hash IS NOT NULL)
        OR status <> 'CONFIRMED'
    )
);

CREATE INDEX idx_idea_brief_project_current ON idea_briefs(project_id, brief_sequence DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_idea_brief_active_task ON idea_briefs(active_task_run_id) WHERE active_task_run_id IS NOT NULL;

CREATE TABLE idea_brief_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id VARCHAR(64) NOT NULL,
    field_key VARCHAR(80) NOT NULL,
    field_value TEXT,
    decision_state VARCHAR(20) NOT NULL,
    provenance VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_field_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_field_key UNIQUE (brief_id, field_key),
    CONSTRAINT ck_idea_field_decision CHECK (decision_state IN ('LOCKED', 'PREFERRED', 'OPEN', 'ASSUMPTION')),
    CONSTRAINT ck_idea_field_provenance CHECK (provenance IN ('USER_CONFIRMED', 'SOURCE_EXTRACTED', 'AI_PROPOSED', 'MISSING'))
);

CREATE INDEX idx_idea_field_brief ON idea_brief_fields(brief_id, id);

CREATE TABLE idea_questions (
    id VARCHAR(64) PRIMARY KEY,
    brief_id VARCHAR(64) NOT NULL,
    target_field_key VARCHAR(80),
    question_type VARCHAR(30) NOT NULL,
    prompt TEXT NOT NULL,
    options_json TEXT,
    display_order INTEGER NOT NULL,
    answered BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_question_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_question_order UNIQUE (brief_id, display_order),
    CONSTRAINT ck_idea_question_type CHECK (question_type IN ('FREE_TEXT', 'SINGLE_SELECT', 'MULTI_SELECT', 'UNDECIDED')),
    CONSTRAINT ck_idea_question_order CHECK (display_order >= 0)
);

CREATE INDEX idx_idea_question_brief ON idea_questions(brief_id, display_order);

CREATE TABLE idea_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id VARCHAR(64) NOT NULL,
    question_id VARCHAR(64) NOT NULL,
    answer_json TEXT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_idea_answer_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_answer_question FOREIGN KEY (question_id) REFERENCES idea_questions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_idea_answer_idempotency UNIQUE (brief_id, question_id, idempotency_key)
);

CREATE INDEX idx_idea_answer_brief ON idea_answers(brief_id, id);

CREATE TABLE idea_brief_attachments (
    brief_id VARCHAR(64) NOT NULL,
    stored_file_id BIGINT NOT NULL,
    PRIMARY KEY (brief_id, stored_file_id),
    CONSTRAINT fk_idea_attachment_brief FOREIGN KEY (brief_id) REFERENCES idea_briefs(id) ON DELETE NO ACTION,
    CONSTRAINT fk_idea_attachment_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id) ON DELETE NO ACTION
);
