package com.aivle.backend.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    AUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED, "로그인이 필요합니다.", false),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "아이디 또는 비밀번호를 확인해 주세요.", false),
    ACCESS_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "인증 토큰이 올바르지 않습니다.", false),
    REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "갱신 토큰이 올바르지 않습니다.", false),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 사용 중인 이메일입니다.", false),
    USERNAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 사용 중인 아이디입니다.", false),
    USERNAME_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "사용할 수 없는 아이디입니다. 다른 아이디를 입력해 주세요.", false),
    LOGIN_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "로그인 시도가 여러 번 실패했습니다. 잠시 후 다시 시도해 주세요.", false),
    USER_INACTIVE(HttpStatus.UNAUTHORIZED, "현재 로그인할 수 없는 계정입니다.", false),
    PASSWORD_POLICY_VIOLATION(HttpStatus.BAD_REQUEST, "비밀번호 정책을 확인해 주세요.", false),
    MISSING_FIELD_NOT_FOUND(HttpStatus.NOT_FOUND, "보완 항목을 찾을 수 없습니다.", false),
    PLAN_NOT_EDITABLE(HttpStatus.CONFLICT, "확정된 구조화 계획은 수정할 수 없습니다.", false),
    PLAN_INCOMPLETE(HttpStatus.UNPROCESSABLE_ENTITY, "필수 보완 항목을 완료해 주세요.", false),
    PLAN_ALREADY_CONFIRMED(HttpStatus.CONFLICT, "이미 확정된 구조화 계획입니다.", false),
    RESOURCE_VERSION_CONFLICT(HttpStatus.CONFLICT, "다른 변경이 먼저 저장되었습니다.", true),
    JOB_RETRY_NOT_ALLOWED(HttpStatus.CONFLICT, "현재 작업은 수동 재시도할 수 없습니다.", false),
    STRUCTURED_PLAN_NOT_FOUND(HttpStatus.NOT_FOUND, "구조화된 사업계획 결과를 찾을 수 없습니다.", false),
    FILE_REQUIRED(HttpStatus.BAD_REQUEST, "업로드할 파일이 필요합니다.", false),
    FILE_EMPTY(HttpStatus.BAD_REQUEST, "빈 파일은 업로드할 수 없습니다.", false),
    FILE_NAME_INVALID(HttpStatus.BAD_REQUEST, "파일 이름이 올바르지 않습니다.", false),
    FILE_STORAGE_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "파일을 안전하게 저장하지 못했습니다.", true),
    DOCUMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "문서를 찾을 수 없습니다.", false),
    DOCUMENT_VERSION_NOT_FOUND(HttpStatus.NOT_FOUND, "문서 버전을 찾을 수 없습니다.", false),
    DOCUMENT_UPLOAD_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "현재 프로젝트 상태에서는 문서를 업로드할 수 없습니다.", false),
    IDEMPOTENCY_KEY_INVALID(HttpStatus.BAD_REQUEST, "Idempotency-Key 형식이 올바르지 않습니다.", false),
    IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "동일한 Idempotency-Key가 다른 요청에 사용되었습니다.", false),
    JOB_NOT_FOUND(HttpStatus.NOT_FOUND, "작업을 찾을 수 없습니다.", false),
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "요청 형식이 올바르지 않습니다.", false),
    VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "입력값을 확인해 주세요.", false),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "요청한 자원을 찾을 수 없습니다.", false),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, "접근 권한이 없습니다.", false),
    ADMIN_ACCESS_REQUIRED(HttpStatus.FORBIDDEN, "관리자 권한이 필요합니다.", false),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "사용자를 찾을 수 없습니다.", false),
    USER_ALREADY_LOCKED(HttpStatus.CONFLICT, "이미 잠긴 계정입니다.", false),
    USER_NOT_LOCKED(HttpStatus.CONFLICT, "잠긴 계정이 아닙니다.", false),
    LAST_ACTIVE_ADMIN_REQUIRED(HttpStatus.CONFLICT, "활성 관리자 계정이 최소 한 명 필요합니다.", false),
    SELF_ADMIN_ROLE_CHANGE_NOT_ALLOWED(HttpStatus.CONFLICT, "자신의 관리자 권한은 변경할 수 없습니다.", false),
    SELF_SESSION_REVOKE_NOT_ALLOWED(HttpStatus.CONFLICT, "자신의 모든 세션은 종료할 수 없습니다.", false),
    SELF_ADMIN_ACCOUNT_CHANGE_NOT_ALLOWED(HttpStatus.CONFLICT, "자신의 관리자 계정 상태는 변경할 수 없습니다.", false),
    ACCOUNT_DELETION_PASSWORD_INVALID(HttpStatus.UNAUTHORIZED, "현재 비밀번호가 올바르지 않습니다.", false),
    ACCOUNT_DELETION_CONFIRMATION_INVALID(HttpStatus.BAD_REQUEST, "회원 탈퇴 확인 문구가 올바르지 않습니다.", false),
    ACCOUNT_ALREADY_DELETED(HttpStatus.CONFLICT, "이미 탈퇴 처리된 계정입니다.", false),
    ADMIN_SELF_DELETE_NOT_ALLOWED(HttpStatus.CONFLICT, "관리자는 자신의 계정을 삭제할 수 없습니다.", false),
    LAST_ACTIVE_ADMIN_DELETE_NOT_ALLOWED(HttpStatus.CONFLICT, "마지막 활성 관리자 계정은 삭제할 수 없습니다.", false),
    USER_DELETE_REAUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED, "사용자 삭제를 수행하려면 관리자 재인증이 필요합니다.", false),
    CLUSTER_PERSONA_DISABLED(HttpStatus.CONFLICT, "군집 페르소나 기능이 비활성화되어 있습니다.", false),
    CLUSTER_PERSONA_NOT_ALLOWED(HttpStatus.CONFLICT, "현재 사용자에게 제공되지 않는 페르소나입니다.", false),
    CLUSTER_PERSONA_NOT_FOUND(HttpStatus.NOT_FOUND, "군집 페르소나를 찾을 수 없습니다.", false),
    CLUSTER_PERSONA_SELECTION_REQUIRED(HttpStatus.CONFLICT, "군집 페르소나를 하나 이상 노출해야 합니다.", false),
    CLUSTER_PERSONA_LIMIT_EXCEEDED(HttpStatus.CONFLICT, "군집 페르소나는 최대 6개까지 노출할 수 있습니다.", false),
    PROJECT_PERSONA_SELECTION_NOT_ALLOWED(HttpStatus.CONFLICT, "현재 프로젝트에서는 이 페르소나를 선택할 수 없습니다.", false),
    MARKETING_CONTENT_NOT_FOUND(HttpStatus.NOT_FOUND, "마케팅 콘텐츠를 찾을 수 없습니다.", false),
    MARKETING_CONTENT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "이 마케팅 콘텐츠에 접근할 수 없습니다.", false),
    MARKETING_CONTENT_INVALID_SIZE(HttpStatus.BAD_REQUEST, "콘텐츠 규격이 올바르지 않습니다.", false),
    MARKETING_CONTENT_INVALID_FORMAT(HttpStatus.BAD_REQUEST, "지원하지 않는 콘텐츠 형식입니다.", false),
    MARKETING_CONTENT_SOURCE_UNAVAILABLE(HttpStatus.CONFLICT, "Marketing Source를 확정할 수 없습니다.", false),
    MARKETING_CONTENT_COPY_GENERATION_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "콘텐츠 초안을 만들 수 없습니다.", true),
    MARKETING_CONTENT_VERSION_CONFLICT(HttpStatus.CONFLICT, "다른 변경이 먼저 저장되었습니다.", true),
    MARKETING_PANEL_INTERVIEW_INVALID(HttpStatus.BAD_REQUEST, "이 프로젝트에서 사용할 수 없는 패널 인터뷰입니다.", false),
    MARKETING_MARKET_RESPONSE_INVALID(HttpStatus.BAD_REQUEST, "이 프로젝트에서 사용할 수 없는 시장 반응 결과입니다.", false),
    MARKETING_VALIDATION_RESULT_NOT_COMPLETED(HttpStatus.CONFLICT, "완료된 검증 결과만 마케팅 콘텐츠에 반영할 수 있습니다.", false),
    MARKETING_SOURCE_REFRESH_FAILED(HttpStatus.CONFLICT, "검증 결과를 다시 불러오지 못했습니다.", true),
    MARKETING_EXPORT_OVERFLOW(HttpStatus.UNPROCESSABLE_ENTITY, "긴 문구가 출력 영역을 벗어납니다.", false),
    MARKETING_ASSET_INVALID(HttpStatus.BAD_REQUEST, "마케팅 이미지 파일이 올바르지 않습니다.", false),
    MARKETING_PROHIBITED_CLAIM(HttpStatus.UNPROCESSABLE_ENTITY, "법률 결과에서 금지한 표현이 포함되어 있습니다.", false),
    PANEL_INTERVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "패널 인터뷰를 찾을 수 없습니다.", false),
    PANEL_INTERVIEW_INVALID_PERSONA(HttpStatus.BAD_REQUEST, "인터뷰 대상 Persona가 올바르지 않습니다.", false),
    PANEL_INTERVIEW_PERSONA_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "인터뷰 Persona는 최대 3개까지 선택할 수 있습니다.", false),
    PANEL_INTERVIEW_QUESTION_REQUIRED(HttpStatus.BAD_REQUEST, "인터뷰 질문은 최소 3개가 필요합니다.", false),
    PANEL_INTERVIEW_QUESTION_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "인터뷰 질문은 최대 10개까지 입력할 수 있습니다.", false),
    PANEL_INTERVIEW_RUN_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "예상 인터뷰를 생성하지 못했습니다.", true),
    MARKET_RESPONSE_NOT_FOUND(HttpStatus.NOT_FOUND, "시장 반응 예측을 찾을 수 없습니다.", false),
    MARKET_RESPONSE_INVALID_PERSONA(HttpStatus.BAD_REQUEST, "시장 반응 대상 Persona가 올바르지 않습니다.", false),
    MARKET_RESPONSE_MESSAGE_REQUIRED(HttpStatus.BAD_REQUEST, "비교할 메시지가 최소 1개 필요합니다.", false),
    MARKET_RESPONSE_MESSAGE_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "비교 메시지는 최대 3개까지 입력할 수 있습니다.", false),
    MARKET_RESPONSE_RUN_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "예상 시장 반응을 생성하지 못했습니다.", true),
    REGISTRATION_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "현재 신규 회원가입이 일시 중지되었습니다.", false),
    DOCUMENT_PROCESSING_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "현재 문서 처리가 일시 중지되었습니다.", false),
    MAINTENANCE_MODE_ENABLED(HttpStatus.SERVICE_UNAVAILABLE, "현재 서비스가 유지보수 중입니다.", false),
    REAUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED, "위험 작업을 수행하려면 재인증이 필요합니다.", false),
    REAUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED, "관리자 재인증에 실패했습니다.", false),
    REAUTHENTICATION_EXPIRED(HttpStatus.UNAUTHORIZED, "관리자 재인증이 만료되었거나 이미 사용되었습니다.", false),
    ADMIN_REAUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED, "관리자 재인증에 실패했습니다.", false),
    ADMIN_REAUTHENTICATION_EXPIRED(HttpStatus.UNAUTHORIZED, "관리자 재인증 시간이 만료되었습니다.", false),
    ADMIN_REAUTHENTICATION_PURPOSE_MISMATCH(HttpStatus.UNAUTHORIZED, "현재 인증 정보는 이 작업에 사용할 수 없습니다.", false),
    ADMIN_ACTION_TOKEN_ALREADY_USED(HttpStatus.UNAUTHORIZED, "이미 사용된 관리자 인증 정보입니다.", false),
    SERVICE_SETTING_ALREADY_APPLIED(HttpStatus.CONFLICT, "이미 적용된 설정 값입니다.", false),
    SERVICE_SETTING_NOT_FOUND(HttpStatus.NOT_FOUND, "서비스 설정을 찾을 수 없습니다.", false),
    SERVICE_SETTING_INVALID(HttpStatus.BAD_REQUEST, "서비스 설정 값이 올바르지 않습니다.", false),
    AI_OPERATIONS_NOT_AVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "AI 운영 기능이 아직 연결되지 않았습니다.", false),
    VERSION_CONFLICT(HttpStatus.CONFLICT, "다른 변경과 충돌했습니다.", true),
    USER_EMAIL_DUPLICATED(HttpStatus.CONFLICT, "이미 사용 중인 이메일입니다.", false),
    PROJECT_NOT_FOUND(HttpStatus.NOT_FOUND, "프로젝트를 찾을 수 없습니다.", false),
    AUDIT_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "감사 기록을 찾을 수 없습니다.", false),
    PROJECT_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "같은 이름의 프로젝트가 이미 있습니다.", false),
    PROJECT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "해당 프로젝트에 접근할 권한이 없습니다.", false),
    PROJECT_STAGE_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "현재 프로젝트 단계에서 수행할 수 없습니다.", false),
    FILE_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE, "파일 크기가 제한을 초과했습니다.", false),
    FILE_TYPE_UNSUPPORTED(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "지원하지 않는 파일 형식입니다.", false),
    FILE_SIGNATURE_INVALID(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "파일 내용과 형식이 일치하지 않습니다.", false),
    EVIDENCE_ARTIFACT_NOT_FOUND(HttpStatus.NOT_FOUND, "근거 파일을 찾을 수 없습니다.", false),
    DOCUMENT_PARSE_FAILED(HttpStatus.UNPROCESSABLE_ENTITY, "문서 구조화에 실패했습니다.", true),
    STRUCTURED_PLAN_MISSING_REQUIRED_FIELDS(HttpStatus.UNPROCESSABLE_ENTITY, "필수 정보 보완이 필요합니다.", false),
    ANALYSIS_ALREADY_RUNNING(HttpStatus.CONFLICT, "동일한 분석이 이미 실행 중입니다.", false),
    ANALYSIS_INPUT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "분석 입력이 올바르지 않습니다.", false),
    EXTERNAL_AI_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "AI 서비스에 일시적으로 연결할 수 없습니다.", true),
    LEGAL_REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "법률·규제 사전검토 결과를 찾을 수 없습니다.", false),
    LEGAL_REVIEW_INPUT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "확정된 사업계획과 프로젝트 단계를 확인해 주세요.", false),
    LEGAL_JURISDICTION_UNSUPPORTED(HttpStatus.UNPROCESSABLE_ENTITY,
        "현재 공식 법률 검토는 대한민국을 대상으로 지원합니다. 대상 지역을 대한민국으로 변경하면 계속 진행할 수 있습니다.", false),
    FEASIBILITY_ASSESSMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "사업 타당성 사전분석 결과를 찾을 수 없습니다.", false),
    FEASIBILITY_INPUT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "확정된 사업계획과 최신 법률 사전검토 결과를 확인해 주세요.", false),
    PERSONA_RECOMMENDATION_NOT_FOUND(HttpStatus.NOT_FOUND, "페르소나 추천 결과를 찾을 수 없습니다.", false),
    PERSONA_INPUT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "확정 계획과 최신 타당성 분석 입력을 확인해 주세요.", false),
    FINANCIAL_ANALYSIS_NOT_FOUND(HttpStatus.NOT_FOUND, "재무 분석을 찾을 수 없습니다.", false),
    FINANCIAL_FEASIBILITY_REQUIRED(HttpStatus.CONFLICT, "완료된 사업 타당성 분석이 필요합니다.", false),
    FINANCIAL_SOURCE_INVALID(HttpStatus.BAD_REQUEST, "재무 분석 근거가 현재 프로젝트와 일치하지 않습니다.", false),
    FINANCIAL_ASSUMPTION_INVALID(HttpStatus.BAD_REQUEST, "재무 가정을 확인해 주세요.", false),
    FINANCIAL_SCENARIO_REQUIRED(HttpStatus.BAD_REQUEST, "보수·기준·낙관 시나리오가 필요합니다.", false),
    FINANCIAL_SCENARIO_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "시나리오는 최대 3개까지 설정할 수 있습니다.", false),
    FINANCIAL_CALCULATION_UNAVAILABLE(HttpStatus.UNPROCESSABLE_ENTITY, "현재 가정으로는 재무 계산을 완료할 수 없습니다.", false),
    FINANCIAL_ALREADY_COMPLETED(HttpStatus.CONFLICT, "완료된 재무 분석은 수정할 수 없습니다. 복제해 새 분석을 만드세요.", false),
    IDEA_NOT_FOUND(HttpStatus.NOT_FOUND, "저장된 아이디어를 찾을 수 없습니다.", false),
    IDEA_NOT_CONFIRMED(HttpStatus.CONFLICT, "법률 검토 전에 아이디어를 확정해 주세요.", false),
    AI_CONFIGURATION_INVALID(HttpStatus.SERVICE_UNAVAILABLE, "AI Provider 설정 또는 API Key를 확인해 주세요.", false),
    AI_RESULT_INVALID(HttpStatus.BAD_GATEWAY, "AI 응답을 유효한 구조로 해석할 수 없습니다.", false),
    CONCEPT_NOT_SELECTABLE(HttpStatus.UNPROCESSABLE_ENTITY, "현재 공개된 컨셉 중 하나를 선택해 주세요.", false),
    CONCEPT_SELECTION_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY, "시장분석 전달 전에 컨셉 선택을 확정해 주세요.", false),
    HYPOTHESIS_NOT_FOUND(HttpStatus.NOT_FOUND, "결정할 가설을 찾을 수 없습니다.", false),
    HYPOTHESIS_LOCKED(HttpStatus.CONFLICT, "사용자가 이미 확정한 값은 가설 결정에서 변경할 수 없습니다.", false),
    HYPOTHESIS_VERSION_CONFLICT(HttpStatus.CONFLICT, "새로운 대안이 생성되었습니다. 최신 제안을 확인해 주세요.", true),
    HYPOTHESIS_VALUE_INVALID(HttpStatus.BAD_REQUEST, "가설 값을 확인해 주세요.", false),
    HYPOTHESIS_DECISIONS_INCOMPLETE(HttpStatus.CONFLICT, "선택한 컨셉의 필수 가설 결정을 먼저 완료해 주세요.", false),
    TECH_OPS_PREPARATION_REQUIRED(HttpStatus.CONFLICT, "기술·운영 입력 준비를 먼저 시작해 주세요.", false),
    TECH_OPS_INPUT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "기술·운영 입력값을 확인해 주세요.", false),
    TECH_OPS_PROPOSAL_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "기술·운영 제안 값을 확인해 주세요.", false),
    TECH_OPS_EVIDENCE_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "기술·운영 근거 자료를 확인해 주세요.", false),
    TECH_OPS_SNAPSHOT_NOT_READY(HttpStatus.CONFLICT, "기술·운영 분석에 필요한 입력과 결정을 완료해 주세요.", false),
    TECH_OPS_SNAPSHOT_IMMUTABLE(HttpStatus.CONFLICT, "확정된 기술·운영 입력 Snapshot은 수정할 수 없습니다.", false),
    FINANCIAL_PREPARATION_REQUIRED(HttpStatus.CONFLICT, "재무 입력 준비를 먼저 시작해 주세요.", false),
    FINANCIAL_INPUT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "재무 입력값을 확인해 주세요.", false),
    FINANCIAL_SNAPSHOT_NOT_READY(HttpStatus.CONFLICT, "재무 분석에 필요한 입력을 완료해 주세요.", false),
    FINANCIAL_SNAPSHOT_IMMUTABLE(HttpStatus.CONFLICT, "확정된 재무 입력 Snapshot은 수정할 수 없습니다.", false),
    MODULE_INPUT_STALE(HttpStatus.CONFLICT, "현재 선택과 다른 입력 Snapshot입니다.", false),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "서버 오류가 발생했습니다.", true);

    private final HttpStatus httpStatus;
    private final String message;
    private final boolean retryable;
}
