package com.aivle.backend.journey.conceptcore;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;

import com.aivle.backend.jobevent.JobEventRepository;
import com.aivle.backend.journey.boundary.*;
import com.aivle.backend.journey.brief.*;
import com.aivle.backend.journey.conversation.ConversationService;
import com.aivle.backend.project.entity.Project;
import com.aivle.backend.project.repository.ProjectRepository;
import com.aivle.backend.taskrun.domain.TaskRun;
import com.aivle.backend.taskrun.domain.TaskRunState;
import com.aivle.backend.taskrun.integration.InternalAiExecutionClient;
import com.aivle.backend.taskrun.integration.InternalAiExecutionClient.ExecutionResponse;
import com.aivle.backend.taskrun.service.TaskRunService;
import com.aivle.backend.user.entity.User;
import com.aivle.backend.user.repository.UserRepository;
import java.util.*;
import java.time.Duration;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import tools.jackson.databind.*;
import tools.jackson.databind.node.*;

@SpringBootTest(properties="spring.task.scheduling.enabled=false") @ActiveProfiles("test")
class ConceptExplorationTests {
 @Autowired UserRepository users;@Autowired ProjectRepository projects;@Autowired ConversationService conversations;@Autowired OpportunityBriefService briefs;@Autowired RegulatoryBoundaryService boundaryFoundation;@Autowired BoundaryRuleRepository boundaryRules;@Autowired ConceptExplorationApplicationService service;@Autowired ConceptExplorationWorker worker;@Autowired ConceptExplorationBatchRepository batches;@Autowired ConceptSlotRepository slots;@Autowired ConceptAttemptRepository attempts;@Autowired ExplorationConceptRepository concepts;@Autowired TaskRunService tasks;@Autowired JobEventRepository events;@Autowired ObjectMapper mapper;@MockitoBean InternalAiExecutionClient client;

 @Test void onlyCurrentConfirmedBriefAndReadyMatchingBoundaryCanStartAndReplay(){Context draft=context(false);assertThat(service.start(draft.owner().getId(),draft.project().getId(),draft.brief().getId(),1L).code()).isEqualTo("CONCEPT_BRIEF_NOT_CONFIRMED");Context ready=context(true);var first=service.start(ready.owner().getId(),ready.project().getId(),ready.brief().getId(),ready.boundary().getId());var replay=service.start(ready.owner().getId(),ready.project().getId(),ready.brief().getId(),ready.boundary().getId());assertThat(first.status()).isEqualTo("QUEUED");assertThat(replay.batchId()).isEqualTo(first.batchId());assertThat(replay.jobId()).isEqualTo(first.jobId());tasks.cancel(ready.owner().getId(),ready.project().getId(),first.jobId());}

 @Test void mixedSlotFailuresPreserveValidSlotsAndPublishExactlyThreePublicConcepts(){Context c=context(true);var start=service.start(c.owner().getId(),c.project().getId(),c.brief().getId(),c.boundary().getId());when(client.execute(any(),anyString(),any())).thenAnswer(inv->response(inv.getArgument(0),inv.getArgument(1),mixedResult()));assertThat(worker.processOne()).isTrue();assertThat(tasks.getOwned(c.owner().getId(),c.project().getId(),start.jobId()).getState()).isEqualTo(TaskRunState.SUCCEEDED);assertThat(batches.findById(start.batchId()).orElseThrow().getStatus()).isEqualTo(ConceptExplorationBatch.Status.COMPLETED);assertThat(service.concepts(c.owner().getId(),c.project().getId())).hasSize(3).allSatisfy(value->{assertThat(value.oneLineSummary()).startsWith("Summary");assertThat(value.solutionMechanism()).startsWith("mechanism");assertThat(value.requiredControls().isArray()).isTrue();assertThat(value.requiredPartnersOrLicenses().isArray()).isTrue();assertThat(value.prohibitedVariants().isArray()).isTrue();assertThat(value.unresolvedAssumptions().isArray()).isTrue();assertThat(value.validatedSnapshotHash()).startsWith("sha256:");});assertThat(slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(start.batchId())).extracting(ConceptSlot::getAttemptCount).containsExactly(1,2,2);assertThat(events.findTopByJobIdAndProjectIdAndDeletedAtIsNullOrderBySequenceDesc(start.jobId(),c.project().getId()).orElseThrow().getMessageKey()).isEqualTo("job.concept.batch.completed");}

 @Test void permanentFailureDoesNotBlockReplacementAndInternalDraftIsNotPublic(){Context c=context(true);var start=service.start(c.owner().getId(),c.project().getId(),c.brief().getId(),c.boundary().getId());when(client.execute(any(),anyString(),any())).thenAnswer(inv->response(inv.getArgument(0),inv.getArgument(1),replacementResult()));worker.processOne();assertThat(slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(start.batchId())).hasSize(4);assertThat(service.concepts(c.owner().getId(),c.project().getId())).hasSize(3).noneMatch(value->value.conceptName().equals("failed"));assertThat(attempts.findBySlotIdAndDeletedAtIsNullOrderByAttemptNumber(slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(start.batchId()).get(0).getId()).get(0).getOutcome()).isEqualTo(ConceptAttempt.Outcome.PERMANENT_PROVIDER_FAILURE);}

 @Test void hardBlockCandidateIsRejectedAndNeverPublished(){Context c=context(true);boundaryRules.save(BoundaryRule.create(c.boundary(),"RULE-HARD",BoundaryRule.RuleType.PROHIBITED_ACTIVITY,"physicalCollection","Direct collection","No direct collection","Do not perform physicalCollection","[]","[\"E1\"]","HIGH","COMPLETE","{}","Avoid direct activity","[]","[]",null,null,false,"[]"));var start=service.start(c.owner().getId(),c.project().getId(),c.brief().getId(),c.boundary().getId());when(client.execute(any(),anyString(),any())).thenAnswer(inv->response(inv.getArgument(0),inv.getArgument(1),validResult()));worker.processOne();assertThat(batches.findById(start.batchId()).orElseThrow().getStatus()).isEqualTo(ConceptExplorationBatch.Status.FAILED);assertThat(service.concepts(c.owner().getId(),c.project().getId())).isEmpty();assertThat(slots.findByBatchIdAndDeletedAtIsNullOrderBySlotIndex(start.batchId())).allMatch(value->value.getLegalState()==ConceptSlot.LegalState.HARD_BLOCK);}

 @Test void unresolvedBoundaryFactsProduceNeedsInputInsteadOfCompleted(){Context c=context(true);boundaryRules.save(BoundaryRule.create(c.boundary(),"RULE-OPEN",BoundaryRule.RuleType.UNRESOLVED_FACT,"operatorQualification","Operator unknown","Operator qualification is unknown","Confirm who operates the service","[]","[\"E2\"]","MEDIUM","COMPLETE","{}","Confirm operator qualification","[]","[]",null,null,false,"[]"));var start=service.start(c.owner().getId(),c.project().getId(),c.brief().getId(),c.boundary().getId());when(client.execute(any(),anyString(),any())).thenAnswer(inv->response(inv.getArgument(0),inv.getArgument(1),validResult()));worker.processOne();assertThat(batches.findById(start.batchId()).orElseThrow().getStatus()).isEqualTo(ConceptExplorationBatch.Status.NEEDS_INPUT);assertThat(service.concepts(c.owner().getId(),c.project().getId())).isEmpty();assertThat(events.findTopByJobIdAndProjectIdAndDeletedAtIsNullOrderBySequenceDesc(start.jobId(),c.project().getId()).orElseThrow().getMessageKey()).isEqualTo("job.concept.batch.needs_input");}

 @Test void safeViewsExposeGateHashesAndRetryFailedBatchWithTheSameTask(){Context c=context(true);var start=service.start(c.owner().getId(),c.project().getId(),c.brief().getId(),c.boundary().getId());assertThat(start.confirmedBriefVersionId()).isEqualTo(c.brief().getId());assertThat(start.briefHash()).isEqualTo(c.brief().getSnapshotHash());assertThat(start.regulatoryBoundaryVersionId()).isEqualTo(c.boundary().getId());assertThat(start.boundaryHash()).isEqualTo(c.boundary().getSnapshotHash());var claim=tasks.claim(start.jobId(),"g6-test",Duration.ofMinutes(1),Duration.ofMinutes(1));tasks.startExecution(claim.taskRunId(),claim.taskAttemptId(),claim.claimToken());tasks.fail(claim.taskRunId(),claim.taskAttemptId(),claim.claimToken(),"DEPENDENCY_TIMEOUT","DEPENDENCY_TIMEOUT",true);var batch=batches.findById(start.batchId()).orElseThrow();batch.generating();batch.fail("DEPENDENCY_TIMEOUT");batches.save(batch);var retried=service.retry(c.owner().getId(),c.project().getId(),start.batchId(),"g6-retry-1");assertThat(retried.status()).isEqualTo("QUEUED");assertThat(retried.jobId()).isEqualTo(start.jobId());assertThat(tasks.getOwned(c.owner().getId(),c.project().getId(),start.jobId()).getState()).isEqualTo(TaskRunState.QUEUED);tasks.cancel(c.owner().getId(),c.project().getId(),start.jobId());}

 private Context context(boolean confirmed){String suffix=UUID.randomUUID().toString();User owner=users.saveAndFlush(User.create("concept-"+suffix+"@example.com","hash","owner"));Project project=projects.saveAndFlush(Project.create(owner,"concept",null,"AI"));var conversation=conversations.create(owner.getId(),project.getId(),null);OpportunityBriefVersion brief=briefs.createDraft(owner.getId(),project.getId(),conversation.getId(),null,"{\"problem\":\"waste\"}",List.of(new OpportunityBriefService.FieldInput("problem","\"waste\"",FieldDecisionStatus.PREFERRED,FieldSourceType.USER_CONFIRMED,"user")));if(!confirmed)return new Context(owner,project,brief,null);briefs.confirm(owner.getId(),project.getId(),brief.getId());RegulatoryBoundaryRun run=boundaryFoundation.createRun(owner.getId(),project.getId(),brief.getId(),null);boundaryFoundation.start(owner.getId(),project.getId(),run.getId());boundaryFoundation.succeed(owner.getId(),project.getId(),run.getId());RegulatoryBoundaryVersion boundary=boundaryFoundation.createVersion(owner.getId(),project.getId(),run.getId(),RegulatoryBoundaryVersion.Status.READY,"{\"status\":\"READY\"}");return new Context(owner,project,brief,boundary);}
 private ExecutionResponse response(TaskRun run,String attempt,JsonNode result){return new ExecutionResponse("1.0",run.getTaskType().name(),"1.0",run.getId(),attempt,run.getCorrelationId(),run.getInputHash(),"1.0",result,mapper.createArrayNode(),mapper.createArrayNode(),null);}
 private ObjectNode validResult(){ObjectNode root=mapper.createObjectNode();ArrayNode values=root.putArray("slots");for(int i=0;i<3;i++)values.add(slot(i,"VALID",List.of("VALID")));root.putArray("acceptedSlotIndices").add(0).add(1).add(2);root.put("eligibleCandidateCount",3);root.put("exhausted",false);return root;}
 private ObjectNode mixedResult(){ObjectNode root=mapper.createObjectNode();ArrayNode values=root.putArray("slots");values.add(slot(0,"VALID",List.of("VALID")));values.add(slot(1,"VALID",List.of("SCHEMA_INVALID","VALID")));values.add(slot(2,"VALID",List.of("TRANSIENT_PROVIDER_FAILURE","VALID")));root.putArray("acceptedSlotIndices").add(0).add(1).add(2);root.put("eligibleCandidateCount",3);root.put("exhausted",false);return root;}
 private ObjectNode replacementResult(){ObjectNode root=mapper.createObjectNode();ArrayNode values=root.putArray("slots");values.add(slot(0,"PERMANENT_PROVIDER_FAILURE",List.of("PERMANENT_PROVIDER_FAILURE")));for(int i=1;i<4;i++)values.add(slot(i,"VALID",List.of("VALID")));root.putArray("acceptedSlotIndices").add(1).add(2).add(3);root.put("eligibleCandidateCount",3);root.put("exhausted",false);return root;}
 private ObjectNode slot(int index,String finalOutcome,List<String> outcomes){ObjectNode s=mapper.createObjectNode();s.put("slotIndex",index);s.put("variationFocus",List.of("TARGET_AND_USER_EXPERIENCE","OPERATING_MODEL_AND_PARTNERS","REVENUE_AND_CHANNELS").get(index%3));ArrayNode as=s.putArray("attempts");for(int i=0;i<outcomes.size();i++){String outcome=outcomes.get(i);ObjectNode a=as.addObject();a.put("attemptNumber",i+1);a.put("phase",i==0?(index<3?"INITIAL":"REPLACEMENT"):"SCHEMA_INVALID".equals(outcomes.get(0))?"REPAIR":"INITIAL");a.put("outcome",outcome);if("VALID".equals(outcome))a.set("candidate",candidate(index));else a.putNull("candidate");if("VALID".equals(outcome))a.putNull("safeFailureType");else a.put("safeFailureType",outcome);if("VALID".equals(outcome))a.put("duplicateStatus","UNIQUE");else a.putNull("duplicateStatus");a.set("negativeConstraint",mapper.createObjectNode());}s.put("accepted","VALID".equals(finalOutcome));return s;}
 private ObjectNode candidate(int i){ObjectNode c=mapper.createObjectNode();c.put("conceptName","Concept "+i);c.put("oneLineSummary","Summary "+i);c.putObject("targetSegment").put("segment","segment-"+i);c.put("problemScenario","waste problem");c.put("valueProposition","less waste");c.put("solutionMechanism","mechanism-"+i);ObjectNode role=c.putArray("actorRoles").addObject();role.put("actor","operator");role.put("role","platform");role.putArray("responsibilities").add("matching");role.putArray("permissions").add("schedule");role.putArray("prohibitedResponsibilities").add("unlicensed work");c.put("platformRole","matching only");ObjectNode tx=c.putArray("transactionFlow").addObject();tx.put("step",1);tx.put("actor","user");tx.put("action","request");tx.put("assetOrPayment","request");tx.put("responsibility","accurate input");c.putArray("dataFlow");ObjectNode physical=c.putArray("physicalActivities").addObject();physical.put("activity","physicalCollection");physical.put("performer","licensed partner");physical.put("requiredQualificationHypothesis","license");physical.put("partnerDependency","partner");c.putArray("partnerRequirements").add("partner-"+i);c.putArray("featureSet").add("matching");c.putArray("channelHypothesis").add("web");c.putObject("pricingHypothesis").put("model","subscription");c.putObject("revenueModelHypothesis").put("model","fee-"+i);c.putObject("operatingModel").put("operator","platform-"+i);c.putArray("assumptions");c.putArray("risks").add("adoption");c.put("legalImplementationHypothesis","licensed partner performs regulated work");return c;}
 record Context(User owner,Project project,OpportunityBriefVersion brief,RegulatoryBoundaryVersion boundary){}
}
