package com.aivle.backend.document.structure;

public enum BusinessPlanSectionCode {
    BUSINESS_OVERVIEW,
    MARKET_SIZE,
    TARGET_CUSTOMER,
    COMPETITIVE_ANALYSIS,
    PRODUCT_SERVICE,
    BUSINESS_MODEL,
    COST_PROFITABILITY,
    SALES_GOALS_FINANCIAL_PROJECTIONS,
    TECHNOLOGY_PRODUCTION,
    LEGAL_PERMITS,
    SCHEDULE_RISK,
    EVIDENCE_LIST
}
