import { useEffect,useMemo,useState } from 'react';import { Link,useParams } from 'react-router-dom';import { useApiClient } from '../../shared/api/ApiClientProvider.jsx';import { getUserErrorMessage } from '../../shared/api/apiError.js';import { createJourneyApi } from './journeyApi.js';import './journey.css';
function useJourney(){const{projectId}=useParams();const client=useApiClient();return{projectId,api:useMemo(()=>createJourneyApi(client,projectId),[client,projectId])};}function ErrorBanner({error}){return error?<div className="journey-error no-print" role="alert"><strong>요청을 완료하지 못했습니다.</strong><span>{error}</span><button type="button" onClick={()=>window.location.reload()}>현재 단계 다시 불러오기</button></div>:null;}function Busy({children}){return <div className="journey-overlay no-print" role="status"><span className="journey-spinner"/><strong>{children}</strong></div>;}function Items({items}){return items?.length?<ul>{items.map((v,i)=><li key={i}>{typeof v==='string'?v:<Structured value={v}/>}</li>)}</ul>:<p className="journey-muted">기록된 항목이 없습니다.</p>;}
function label(key){return key.replace(/([A-Z])/g,' $1').replace(/^./,v=>v.toUpperCase());}
function Structured({value}){if(value==null)return <span>-</span>;if(typeof value==='string'||typeof value==='number'||typeof value==='boolean')return <span>{String(value)}</span>;if(Array.isArray(value))return <Items items={value}/>;return <dl className="structured-fields">{Object.entries(value).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd><Structured value={v}/></dd></div>)}</dl>;}
const TYPES=['POSITIONING','CORE_MESSAGE','SLOGAN','SOCIAL_COPY','LANDING_HERO','EMAIL_COPY','CHANNEL_PLAN'];const TYPE_LABEL={POSITIONING:'Positioning',CORE_MESSAGE:'Core Message',SLOGAN:'Slogan',SOCIAL_COPY:'Social Copy',LANDING_HERO:'Landing Hero',EMAIL_COPY:'Email Copy',CHANNEL_PLAN:'Channel Plan'};
function AssetContent({asset}){const c=asset.content;if(asset.assetType==='LANDING_HERO'&&c&&typeof c==='object')return <div className="landing-preview"><small>Landing Page Preview</small><h2>{c.headline}</h2><p>{c.subheadline}</p><button type="button">{c.cta}</button></div>;return <Structured value={c}/>;}
export function MarketingJourneyPage(){const{projectId,api}=useJourney();const[workspace,setWorkspace]=useState(null);const[comparison,setComparison]=useState(null);const[synthesis,setSynthesis]=useState(null);const[tab,setTab]=useState('POSITIONING');const[busy,setBusy]=useState('');const[error,setError]=useState('');
 useEffect(()=>{let active=true;Promise.all([api.currentInterviewSynthesis(),api.marketingWorkspace(),api.currentMarketingComparison()]).then(([s,w,c])=>{if(active){setSynthesis(s);setWorkspace(w);setComparison(c);if(w?.assets?.length)setTab(w.assets[0].assetType);}}).catch(e=>active&&setError(getUserErrorMessage(e)));return()=>{active=false;};},[api]);
 async function generate(){setBusy('실제 AI가 Marketing Asset을 생성하고 있습니다.');setError('');try{const w=await api.generateMarketing();setWorkspace(w);setTab(w.assets?.[0]?.assetType||'POSITIONING');}catch(e){setError(getUserErrorMessage(e));}finally{setBusy('');}}
 async function select(id){setError('');try{setWorkspace(await api.selectMarketingAsset(id));}catch(e){setError(getUserErrorMessage(e));}}
 async function compare(){setBusy('합성 Persona 관점에서 Asset을 질적으로 비교하고 있습니다.');setError('');try{setComparison(await api.compareMarketing());}catch(e){setError(getUserErrorMessage(e));}finally{setBusy('');}}
 if(synthesis?.state!=='SUCCEEDED')return <div className="journey-page"><section className="journey-empty"><h3>Interview Synthesis가 필요합니다.</h3><Link className="journey-button" to={`/app/projects/${projectId}/journey/interview`}>Interview로 이동</Link></section></div>;
 const visible=workspace?.assets?.filter(v=>v.assetType===tab)||[];const comparisons=comparison?.result?.comparisons||[];
 return <div className="journey-page marketing-page">{busy&&<Busy>{busy}</Busy>}<header className="journey-page__heading"><div><span>8단계 · Marketing</span><h2>Persona 연구를 메시지와 채널 가설로 전환하세요</h2><p>모든 Asset은 실제 AI 초안이며 통계적 승자나 구매 전환율 예측으로 해석하지 않습니다.</p></div><span className={`journey-save-state ${workspace?.state==='READY'?'is-saved':''}`}>{workspace?.state==='READY'?'Asset 저장됨':'생성 전'}</span></header><ErrorBanner error={error}/>
  <section className="journey-card journey-run-card no-print"><div><h3>Marketing Asset Generation</h3><p>확정 Idea, 법률 조건, 선택 Concept, 심층 분석, Persona와 Interview Synthesis를 함께 사용합니다.</p></div><button className="journey-button" disabled={busy||workspace?.state==='READY'} onClick={()=>void generate()}>{workspace?.state==='READY'?'생성 완료':'Marketing 생성'}</button></section>
  {workspace?.state==='READY'?<><section className="journey-card marketing-workspace"><header><div><span>Workspace</span><h3>{workspace.conceptName}</h3></div><span>Asset Version 1</span></header><div className="asset-tabs" role="tablist">{TYPES.map(type=><button key={type} className={tab===type?'active':''} onClick={()=>setTab(type)}>{TYPE_LABEL[type]}<small>{workspace.assets.filter(v=>v.assetType===type).length}</small></button>)}</div><div className="asset-grid">{visible.map(asset=><article className={`asset-card ${asset.selected?'selected':''}`} key={asset.id}><header><div><span className="journey-badge">{TYPE_LABEL[asset.assetType]}</span><h4>{asset.title}</h4></div><span>v{asset.version}</span></header><AssetContent asset={asset}/><button className={`journey-button ${asset.selected?'secondary':''}`} onClick={()=>void select(asset.id)}>{asset.selected?'선택됨':'이 Asset 선택'}</button></article>)}</div>{workspace.strategy&&<div className="marketing-evidence"><section><h4>Persona별 메시지</h4>{workspace.strategy.personaMessages?.map((m,i)=><article key={i}><strong>{m.personaName}</strong><p>{m.message}</p><small>{m.rationale}</small></article>)}</section><section><h4>가정</h4><Items items={workspace.strategy.assumptions}/><h4>주의사항</h4><Items items={workspace.strategy.warnings}/></section></div>}</section>
  <section className="journey-card journey-run-card no-print"><div><h3>Persona별 질적 Comparison</h3><p>적합성, 장점, 위험과 활용 맥락을 비교하며 통계적 실험 결과가 아닙니다.</p></div><button className="journey-button" disabled={busy||comparison?.state==='SUCCEEDED'} onClick={()=>void compare()}>{comparison?.state==='SUCCEEDED'?'비교 완료':'Comparison 실행'}</button></section>
  {comparisons.length>0&&<section className="journey-card"><h3>Marketing Comparison Matrix</h3><div className="comparison-matrix">{comparisons.map(item=>{const asset=workspace.assets.find(v=>v.id===item.assetId);return <article key={item.assetId}><header><div><span className="journey-badge">{TYPE_LABEL[item.assetType]}</span><strong>{asset?.title}</strong></div><button className="journey-text-button" onClick={()=>void select(item.assetId)}>선택</button></header><div className="persona-fit-row">{item.personaFit?.map((fit,i)=><section key={i}><span className={`fit-${fit.fit?.toLowerCase()}`}>{fit.fit}</span><strong>{fit.personaName}</strong><p>{fit.rationale}</p></section>)}</div><div className="comparison-notes"><section><h4>장점</h4><Items items={item.strengths}/></section><section><h4>잠재 위험</h4><Items items={item.risks}/></section><section><h4>추천 활용 맥락</h4><Items items={item.recommendedContexts}/></section></div><p className="selection-suggestion"><strong>선택 제안</strong> {item.selectionSuggestion}</p></article>;})}</div><div className="journey-next"><div><strong>Asset 선택을 확인하세요.</strong><p>최종 보고서는 사용자가 선택한 Asset만 의사결정 근거로 포함합니다.</p></div><Link className="journey-button" to={`/app/projects/${projectId}/journey/final-report`}>Final Report로 이동</Link></div></section>}</>:<section className="journey-empty"><h3>Marketing Asset이 없습니다.</h3><p>Provider 결과가 저장되기 전에는 가짜 Asset을 표시하지 않습니다.</p></section>}
 </div>;}

const DECISIONS=['GO','CONDITIONAL_GO','REWORK','HOLD','STOP'];const REPORT_SECTIONS=[['idea','Idea'],['legalReview','Legal Review'],['selectedConcept','Selected Concept'],['analysis','Detailed Analysis'],['personaInsights','Persona Insights'],['marketingStrategy','Marketing Strategy']];
export function FinalReportJourneyPage(){const{projectId,api}=useJourney();const[workspace,setWorkspace]=useState(null);const[report,setReport]=useState(null);const[decision,setDecision]=useState('');const[reasons,setReasons]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');
 useEffect(()=>{let active=true;Promise.all([api.marketingWorkspace(),api.currentFinalReport()]).then(([w,r])=>{if(active){setWorkspace(w);setReport(r);setDecision(r?.userDecision||r?.aiDecision||'');setReasons((r?.userDecisionReasons||[]).join('\n'));}}).catch(e=>active&&setError(getUserErrorMessage(e)));return()=>{active=false;};},[api]);
 async function generate(){setBusy('실제 AI가 저장된 Journey 결과를 최종 보고서로 구성하고 있습니다.');setError('');try{const r=await api.generateFinalReport();setReport(r);setDecision(r.userDecision||r.aiDecision||'');}catch(e){setError(getUserErrorMessage(e));}finally{setBusy('');}}
 async function saveDecision(){setError('');try{setReport(await api.decideFinalReport(report.id,{decision,reasons:reasons.split('\n').map(v=>v.trim()).filter(Boolean)}));}catch(e){setError(getUserErrorMessage(e));}}
 if(!workspace?.assets?.some(v=>v.selected))return <div className="journey-page"><section className="journey-empty"><h3>선택된 Marketing Asset이 필요합니다.</h3><Link className="journey-button" to={`/app/projects/${projectId}/journey/marketing`}>Marketing Workspace</Link></section></div>;
 const result=report?.result;
 return <div className="journey-page final-report-page">{busy&&<Busy>{busy}</Busy>}<header className="report-header"><div><span>9단계 · Final Report</span><h1>Business Journey 최종 보고서</h1><p>{workspace.conceptName}</p></div><div><span>Version {report?.version||'-'}</span><span>{report?.generatedAt?new Date(report.generatedAt).toLocaleString():'생성 전'}</span><button className="journey-button secondary no-print" onClick={()=>window.print()}>인쇄 / PDF 저장</button></div></header><ErrorBanner error={error}/>
  {!result?<section className="journey-card journey-run-card no-print"><div><h3>Final Report Generation</h3><p>선택 Asset과 전체 Journey 근거를 Section 기반 보고서로 저장합니다.</p></div><button className="journey-button" disabled={busy} onClick={()=>void generate()}>Final Report 생성</button></section>:<article className="report-document"><section className="report-executive"><span>Executive Summary</span><h2>의사결정 요약</h2><p>{result.executiveSummary}</p></section>{REPORT_SECTIONS.map(([key,title])=><section className="report-section" key={key}><h2>{title}</h2><Structured value={result[key]}/></section>)}<div className="report-two-column"><section><h2>Facts</h2><Items items={result.facts}/></section><section><h2>Assumptions</h2><Items items={result.assumptions}/></section><section><h2>Research Needs</h2><Items items={result.researchNeeds}/></section><section><h2>Risks</h2><Items items={result.risks}/></section></div><section className="report-decision"><div><span>AI Decision Proposal</span><h2>{result.decision}</h2><Items items={result.decisionReasons}/></div><div className="user-decision no-print"><h3>사용자 Decision</h3><p>AI 제안을 자동 확정하지 않습니다. 담당자가 직접 결정하고 근거를 저장하세요.</p><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">선택</option>{DECISIONS.map(v=><option key={v}>{v}</option>)}</select></label><label>결정 근거<textarea rows="5" value={reasons} onChange={e=>setReasons(e.target.value)} placeholder="한 줄에 하나씩 입력하세요."/></label><button className="journey-button" disabled={!decision||!reasons.trim()} onClick={()=>void saveDecision()}>사용자 Decision 저장</button></div>{report.userDecision&&<div className="saved-decision"><span>사용자 확정 Decision</span><h2>{report.userDecision}</h2><Items items={report.userDecisionReasons}/></div>}</section><section className="report-section"><h2>Next Actions</h2><Items items={result.nextActions}/></section></article>}
 </div>;}
