spring:
  datasource:
    url: jdbc:h2:file:./data/aivle;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

app:
  object-storage:
    provider: ${OBJECT_STORAGE_PROVIDER:local}
