const uploadTasks = ['파일 정보 확인', 'DOCX 형식 확인', '프로젝트에 문서 연결', '업로드 완료'];
const phaseTasks = { structuring: ['사업 개요 추출', '목표 고객 추출', '시장 근거 분류', '수익 모델 확인', '기술·운영 확인'], reviewing: ['법률·규제 점검', '시장성 분석', '비즈니스 모델 분석', '기술·운영 분석'], personas: ['사업 타깃 조건 확인', '소비 성향 군집 비교', '서비스 이용 가능성 분석', '추천 근거 생성'], integrating: ['구조화 결과 연결', '선택한 위험 항목 연결', '페르소나 검증 질문 생성', '다음 행동 우선순위 정리'] };

export default function DemoProgressPanel({ state, progress, sample }) {
  const tasks = state === 'uploading' ? uploadTasks : phaseTasks[state];
  const title = state === 'uploading' ? '파일 업로드 중' : state === 'structuring' ? '문서의 핵심 내용을 찾고 있습니다' : state === 'reviewing' ? '위험과 사업 가정을 검토하고 있습니다' : state === 'personas' ? '검증에 적합한 고객군을 찾고 있습니다' : '선택한 검증 항목을 하나로 정리하고 있습니다';
  const overall = state === 'uploading' ? progress : state === 'structuring' ? 36 + Math.round(progress * .12) : state === 'reviewing' ? 48 + Math.round(progress * .12) : state === 'personas' ? 66 + Math.round(progress * .14) : 84 + Math.round(progress * .16);
  return <section className="demo-progress-panel" aria-live="polite"><p>전체 진행률 {overall}%</p><h3>{title}</h3><span>{sample.fileName}</span><div className="demo-overall-progress" role="progressbar" aria-label="데모 처리 진행률" aria-valuemin="0" aria-valuemax="100" aria-valuenow={overall}><i style={{ width: `${overall}%` }} /></div><strong>{state === 'uploading' ? `업로드 진행률 ${progress}%` : `현재 단계 진행률 ${progress}%`}</strong><ul>{tasks.map((task, index) => { const done = progress >= (index + 1) * (100 / tasks.length); const working = !done && progress >= index * (100 / tasks.length); return <li className={done ? 'is-done' : working ? 'is-working' : ''} key={task}>{done ? '✓' : working ? '…' : '○'} {task}{done && ' 완료'}{working && ' 중'}</li>; })}</ul>{state === 'structuring' && progress >= 45 && <div className="demo-keyword-report"><b>가상 추출 결과</b><p>{sample.overview}</p><span>{sample.keywords.map((item) => <i key={item}>{item}</i>)}</span></div>}{state === 'reviewing' && progress >= 45 && <div className="demo-keyword-report"><b>가상 검토 키워드</b><span>{['개인정보', '정기결제', '환불 정책', '구독 서비스', '고객 유지'].map((item) => <i key={item}>{item}</i>)}</span></div>}</section>;
}
