import { personas, risks } from '../../data/demoExperienceData.js';

export function UploadReview({ sample, onStructure, onReset }) { return <section className="demo-review"><p className="demo-review__eyebrow">문서 업로드가 완료되었습니다</p><h3>{sample.fileName}</h3><dl><div><dt>문서 페이지</dt><dd>{sample.pages}</dd></div><div><dt>예상 핵심 항목</dt><dd>사업 개요, 고객, 시장, 수익 모델, 운영 계획</dd></div></dl><div className="demo-action-row"><button className="landing-button" type="button" onClick={onStructure}>문서 구조화 시작</button><button className="landing-text-button" type="button" onClick={onReset}>다른 파일 선택</button></div></section>; }

export function StructureReview({ showGaps, onToggleGaps, onReview }) { return <section className="demo-review"><p className="demo-review__eyebrow">문서 구조화가 완료되었습니다</p><h3>완료 항목 10개 · 보완 필요 항목 2개</h3><p>확인된 원문 근거 14개를 바탕으로 핵심 내용을 구조화했습니다. 아래 항목은 가상 데모 예시입니다.</p><button className="demo-disclosure" type="button" aria-expanded={showGaps} onClick={onToggleGaps}>보완 항목 확인 <span>{showGaps ? '−' : '+'}</span></button>{showGaps && <ul className="demo-gap-list"><li>가격 근거가 부족합니다.</li><li>시장 규모의 출처 확인이 필요합니다.</li></ul>}<div className="demo-action-row"><button className="landing-button" type="button" onClick={onReview}>법률·사업성 검토 시작</button></div></section>; }

export function RiskSelection({ selected, onToggle, onPersonas }) { return <section className="demo-review"><p className="demo-review__eyebrow">사전 검토 결과</p><h3>우선 확인 위험 4개 · 사업 가정 5개</h3><p>선택한 항목은 최종 검증 과제에 포함됩니다.</p><div className="demo-selection-list">{risks.map((risk) => <label key={risk.id}><input type="checkbox" checked={selected.includes(risk.id)} onChange={() => onToggle(risk.id)} /><span><b>{risk.title}</b><small>{risk.status} · {risk.detail}</small></span></label>)}</div><div className="demo-action-row"><button className="landing-button" type="button" onClick={onPersonas}>선택 항목으로 고객 검증 설계</button></div></section>; }

export function PersonaSelection({ selected, onToggle, onIntegrate }) { const canContinue = selected.length > 0; return <section className="demo-review"><p className="demo-review__eyebrow">추천 페르소나 후보 3개</p><h3>우선 검증할 고객군을 선택하세요</h3><p>최대 두 개의 고객군을 선택할 수 있습니다.</p><div className="demo-persona-options">{personas.map((persona) => <label className={selected.includes(persona.id) ? 'is-selected' : ''} key={persona.id}><input type="checkbox" checked={selected.includes(persona.id)} onChange={() => onToggle(persona.id)} /><span><b>{persona.title}</b><small>{persona.meta}</small><em>{persona.traits.join(' · ')}</em></span></label>)}</div>{!canContinue && <p className="demo-selection-help" role="status">최소 1개의 고객군을 선택해 주세요.</p>}<div className="demo-action-row"><button className="landing-button" type="button" disabled={!canContinue} onClick={onIntegrate}>선택한 고객군으로 결과 만들기</button></div></section>; }
