package com.aivle.backend.admin;

public enum AdminAuditAction {
    ADMIN_REAUTHENTICATION_SUCCEEDED,
    ADMIN_REAUTHENTICATION_FAILED,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    USER_SESSION_REVOKED,
    USER_SELF_DELETED,
    USER_DELETED_BY_ADMIN,
    CLUSTER_PERSONA_POLICY_CHANGED,
    CLUSTER_PERSONA_VISIBILITY_CHANGED,
    CLUSTER_PERSONA_ORDER_CHANGED,
    SERVICE_SETTING_CHANGED
}
